/*
 * Shared reference data for the Convercession visa platform.
 * Loaded on every page (homepage + generated visa pages) before common.js.
 * To extend country coverage, add entries here AND to data/countries.js
 * (the build-time data used by build.js to generate real pages).
 */
window.ConvercessionData = (() => {
  "use strict";

  const POPULAR_COUNTRIES = [
    "Kenya", "United States", "United Kingdom", "Canada", "Australia",
    "United Arab Emirates", "Singapore", "Thailand", "France", "Germany",
    "South Korea", "Saudi Arabia"
  ];

  // 215 sovereign states + widely-requested territories/dependencies, so the
  // list clears 200 entries without inventing countries that don't exist.
  // This block is rewritten automatically by build.js from data/all-countries.json
  // (the single source of truth for both the search dropdown and the generated
  // pages) — don't hand-edit between the markers, edit that JSON file instead.
  const COUNTRIES = [
    /* COUNTRIES:START */
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong SAR",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau SAR",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "US Virgin Islands",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
    /* COUNTRIES:END */
  ];

  const EMBASSY_CITIES = [
    "New Delhi", "Mumbai", "Chennai", "Kolkata", "Hyderabad",
    "Bengaluru", "Ahmedabad", "Kochi", "Chandigarh", "Pune", "Jaipur", "Lucknow"
  ];

  const VISA_TYPES = [
    "Tourist Visa", "Business Visa", "Family Visit Visa", "Employment / Work Visa",
    "Student Visa", "Medical Visa", "Transit Visa", "Conference Visa",
    "Dependent Visa", "Official Visa", "Diplomatic Visa", "Journalist Visa",
    "Research Visa", "Internship Visa", "Crew Visa", "Religious Visa",
    "Investment Visa", "Long-Term Visa", "Permanent Residence"
  ];

  // Country + visa-type combinations that have an actual generated page under /visa/.
  // This block is rewritten automatically by build.js every time you run
  // `node build.js` — it reads data/countries.js as the single source of
  // truth, so this list can never drift out of sync with what's actually
  // on disk. Do not hand-edit between the markers; edit data/countries.js
  // and rebuild instead.
  const GENERATED_PAGES = [
    /* GENERATED_PAGES:START */
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "antigua-and-barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia-and-herzegovina",
    "botswana",
    "brazil",
    "british-virgin-islands",
    "brunei",
    "bulgaria",
    "burkina-faso",
    "burundi",
    "cabo-verde",
    "cambodia",
    "cameroon",
    "canada",
    "cayman-islands",
    "central-african-republic",
    "chad",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo-congo-brazzaville",
    "cook-islands",
    "costa-rica",
    "croatia",
    "cuba",
    "curacao",
    "cyprus",
    "czechia",
    "democratic-republic-of-the-congo",
    "denmark",
    "djibouti",
    "dominica",
    "dominican-republic",
    "ecuador",
    "egypt",
    "el-salvador",
    "equatorial-guinea",
    "eritrea",
    "estonia",
    "eswatini",
    "ethiopia",
    "faroe-islands",
    "fiji",
    "finland",
    "france",
    "french-polynesia",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guatemala",
    "guernsey",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "honduras",
    "hong-kong-sar",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle-of-man",
    "israel",
    "italy",
    "ivory-coast",
    "jamaica",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macau-sar",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall-islands",
    "mauritania",
    "mauritius",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new-caledonia",
    "new-zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "north-korea",
    "north-macedonia",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "palestine",
    "panama",
    "papua-new-guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "puerto-rico",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "saint-kitts-and-nevis",
    "saint-lucia",
    "saint-vincent-and-the-grenadines",
    "samoa",
    "san-marino",
    "sao-tome-and-principe",
    "saudi-arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra-leone",
    "singapore",
    "slovakia",
    "slovenia",
    "solomon-islands",
    "somalia",
    "south-africa",
    "south-korea",
    "south-sudan",
    "spain",
    "sri-lanka",
    "sudan",
    "suriname",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor-leste",
    "togo",
    "tonga",
    "trinidad-and-tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "tuvalu",
    "uganda",
    "ukraine",
    "united-arab-emirates",
    "united-kingdom",
    "united-states",
    "uruguay",
    "us-virgin-islands",
    "uzbekistan",
    "vanuatu",
    "vatican-city",
    "venezuela",
    "vietnam",
    "yemen",
    "zambia",
    "zimbabwe"
    /* GENERATED_PAGES:END */
  ];

  function slugify(value) {
    return String(value)
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/&/g, "and")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  return {
    POPULAR_COUNTRIES, COUNTRIES, EMBASSY_CITIES, VISA_TYPES, GENERATED_PAGES,
    slugify
  };
})();
