<?php
declare(strict_types=1);

/**
 * Factual reference data only: name / ISO codes / region / capital / currency.
 * Visa-specific content (fees, processing times, documents) lives in
 * country_visa_categories and is seeded separately, only where verified.
 * Row shape: [slug, name, iso2, iso3, region, capital, currency]
 */
function all_countries_data(): array
{
    return [
        // Africa
        ['algeria', 'Algeria', 'DZ', 'DZA', 'Africa', 'Algiers', 'Algerian Dinar'],
        ['angola', 'Angola', 'AO', 'AGO', 'Africa', 'Luanda', 'Angolan Kwanza'],
        ['benin', 'Benin', 'BJ', 'BEN', 'Africa', 'Porto-Novo', 'West African CFA Franc'],
        ['botswana', 'Botswana', 'BW', 'BWA', 'Africa', 'Gaborone', 'Botswana Pula'],
        ['burkina-faso', 'Burkina Faso', 'BF', 'BFA', 'Africa', 'Ouagadougou', 'West African CFA Franc'],
        ['burundi', 'Burundi', 'BI', 'BDI', 'Africa', 'Gitega', 'Burundian Franc'],
        ['cabo-verde', 'Cabo Verde', 'CV', 'CPV', 'Africa', 'Praia', 'Cape Verdean Escudo'],
        ['cameroon', 'Cameroon', 'CM', 'CMR', 'Africa', 'Yaoundé', 'Central African CFA Franc'],
        ['central-african-republic', 'Central African Republic', 'CF', 'CAF', 'Africa', 'Bangui', 'Central African CFA Franc'],
        ['chad', 'Chad', 'TD', 'TCD', 'Africa', "N'Djamena", 'Central African CFA Franc'],
        ['comoros', 'Comoros', 'KM', 'COM', 'Africa', 'Moroni', 'Comorian Franc'],
        ['congo-republic', 'Congo (Republic)', 'CG', 'COG', 'Africa', 'Brazzaville', 'Central African CFA Franc'],
        ['dr-congo', 'DR Congo', 'CD', 'COD', 'Africa', 'Kinshasa', 'Congolese Franc'],
        ['cote-divoire', "Côte d'Ivoire", 'CI', 'CIV', 'Africa', 'Yamoussoukro', 'West African CFA Franc'],
        ['djibouti', 'Djibouti', 'DJ', 'DJI', 'Africa', 'Djibouti City', 'Djiboutian Franc'],
        ['egypt', 'Egypt', 'EG', 'EGY', 'Africa', 'Cairo', 'Egyptian Pound'],
        ['equatorial-guinea', 'Equatorial Guinea', 'GQ', 'GNQ', 'Africa', 'Malabo', 'Central African CFA Franc'],
        ['eritrea', 'Eritrea', 'ER', 'ERI', 'Africa', 'Asmara', 'Eritrean Nakfa'],
        ['eswatini', 'Eswatini', 'SZ', 'SWZ', 'Africa', 'Mbabane', 'Swazi Lilangeni'],
        ['ethiopia', 'Ethiopia', 'ET', 'ETH', 'Africa', 'Addis Ababa', 'Ethiopian Birr'],
        ['gabon', 'Gabon', 'GA', 'GAB', 'Africa', 'Libreville', 'Central African CFA Franc'],
        ['gambia', 'Gambia', 'GM', 'GMB', 'Africa', 'Banjul', 'Gambian Dalasi'],
        ['ghana', 'Ghana', 'GH', 'GHA', 'Africa', 'Accra', 'Ghanaian Cedi'],
        ['guinea', 'Guinea', 'GN', 'GIN', 'Africa', 'Conakry', 'Guinean Franc'],
        ['guinea-bissau', 'Guinea-Bissau', 'GW', 'GNB', 'Africa', 'Bissau', 'West African CFA Franc'],
        ['kenya', 'Kenya', 'KE', 'KEN', 'Africa', 'Nairobi', 'Kenyan Shilling'],
        ['lesotho', 'Lesotho', 'LS', 'LSO', 'Africa', 'Maseru', 'Lesotho Loti'],
        ['liberia', 'Liberia', 'LR', 'LBR', 'Africa', 'Monrovia', 'Liberian Dollar'],
        ['libya', 'Libya', 'LY', 'LBY', 'Africa', 'Tripoli', 'Libyan Dinar'],
        ['madagascar', 'Madagascar', 'MG', 'MDG', 'Africa', 'Antananarivo', 'Malagasy Ariary'],
        ['malawi', 'Malawi', 'MW', 'MWI', 'Africa', 'Lilongwe', 'Malawian Kwacha'],
        ['mali', 'Mali', 'ML', 'MLI', 'Africa', 'Bamako', 'West African CFA Franc'],
        ['mauritania', 'Mauritania', 'MR', 'MRT', 'Africa', 'Nouakchott', 'Mauritanian Ouguiya'],
        ['mauritius', 'Mauritius', 'MU', 'MUS', 'Africa', 'Port Louis', 'Mauritian Rupee'],
        ['morocco', 'Morocco', 'MA', 'MAR', 'Africa', 'Rabat', 'Moroccan Dirham'],
        ['mozambique', 'Mozambique', 'MZ', 'MOZ', 'Africa', 'Maputo', 'Mozambican Metical'],
        ['namibia', 'Namibia', 'NA', 'NAM', 'Africa', 'Windhoek', 'Namibian Dollar'],
        ['niger', 'Niger', 'NE', 'NER', 'Africa', 'Niamey', 'West African CFA Franc'],
        ['nigeria', 'Nigeria', 'NG', 'NGA', 'Africa', 'Abuja', 'Nigerian Naira'],
        ['rwanda', 'Rwanda', 'RW', 'RWA', 'Africa', 'Kigali', 'Rwandan Franc'],
        ['sao-tome-and-principe', 'Sao Tome and Principe', 'ST', 'STP', 'Africa', 'São Tomé', 'São Tomé and Príncipe Dobra'],
        ['senegal', 'Senegal', 'SN', 'SEN', 'Africa', 'Dakar', 'West African CFA Franc'],
        ['seychelles', 'Seychelles', 'SC', 'SYC', 'Africa', 'Victoria', 'Seychellois Rupee'],
        ['sierra-leone', 'Sierra Leone', 'SL', 'SLE', 'Africa', 'Freetown', 'Sierra Leonean Leone'],
        ['somalia', 'Somalia', 'SO', 'SOM', 'Africa', 'Mogadishu', 'Somali Shilling'],
        ['south-africa', 'South Africa', 'ZA', 'ZAF', 'Africa', 'Pretoria', 'South African Rand'],
        ['south-sudan', 'South Sudan', 'SS', 'SSD', 'Africa', 'Juba', 'South Sudanese Pound'],
        ['sudan', 'Sudan', 'SD', 'SDN', 'Africa', 'Khartoum', 'Sudanese Pound'],
        ['tanzania', 'Tanzania', 'TZ', 'TZA', 'Africa', 'Dodoma', 'Tanzanian Shilling'],
        ['togo', 'Togo', 'TG', 'TGO', 'Africa', 'Lomé', 'West African CFA Franc'],
        ['tunisia', 'Tunisia', 'TN', 'TUN', 'Africa', 'Tunis', 'Tunisian Dinar'],
        ['uganda', 'Uganda', 'UG', 'UGA', 'Africa', 'Kampala', 'Ugandan Shilling'],
        ['zambia', 'Zambia', 'ZM', 'ZMB', 'Africa', 'Lusaka', 'Zambian Kwacha'],
        ['zimbabwe', 'Zimbabwe', 'ZW', 'ZWE', 'Africa', 'Harare', 'Zimbabwean Dollar'],

        // Asia
        ['afghanistan', 'Afghanistan', 'AF', 'AFG', 'Asia', 'Kabul', 'Afghan Afghani'],
        ['armenia', 'Armenia', 'AM', 'ARM', 'Asia', 'Yerevan', 'Armenian Dram'],
        ['azerbaijan', 'Azerbaijan', 'AZ', 'AZE', 'Asia', 'Baku', 'Azerbaijani Manat'],
        ['bahrain', 'Bahrain', 'BH', 'BHR', 'Asia', 'Manama', 'Bahraini Dinar'],
        ['bangladesh', 'Bangladesh', 'BD', 'BGD', 'Asia', 'Dhaka', 'Bangladeshi Taka'],
        ['bhutan', 'Bhutan', 'BT', 'BTN', 'Asia', 'Thimphu', 'Bhutanese Ngultrum'],
        ['brunei', 'Brunei', 'BN', 'BRN', 'Asia', 'Bandar Seri Begawan', 'Brunei Dollar'],
        ['cambodia', 'Cambodia', 'KH', 'KHM', 'Asia', 'Phnom Penh', 'Cambodian Riel'],
        ['china', 'China', 'CN', 'CHN', 'Asia', 'Beijing', 'Chinese Yuan'],
        ['cyprus', 'Cyprus', 'CY', 'CYP', 'Asia', 'Nicosia', 'Euro'],
        ['georgia', 'Georgia', 'GE', 'GEO', 'Asia', 'Tbilisi', 'Georgian Lari'],
        ['hong-kong', 'Hong Kong', 'HK', 'HKG', 'Asia', 'Hong Kong', 'Hong Kong Dollar'],
        ['india', 'India', 'IN', 'IND', 'Asia', 'New Delhi', 'Indian Rupee'],
        ['indonesia', 'Indonesia', 'ID', 'IDN', 'Asia', 'Jakarta', 'Indonesian Rupiah'],
        ['iran', 'Iran', 'IR', 'IRN', 'Asia', 'Tehran', 'Iranian Rial'],
        ['iraq', 'Iraq', 'IQ', 'IRQ', 'Asia', 'Baghdad', 'Iraqi Dinar'],
        ['israel', 'Israel', 'IL', 'ISR', 'Asia', 'Jerusalem', 'Israeli New Shekel'],
        ['japan', 'Japan', 'JP', 'JPN', 'Asia', 'Tokyo', 'Japanese Yen'],
        ['jordan', 'Jordan', 'JO', 'JOR', 'Asia', 'Amman', 'Jordanian Dinar'],
        ['kazakhstan', 'Kazakhstan', 'KZ', 'KAZ', 'Asia', 'Astana', 'Kazakhstani Tenge'],
        ['kuwait', 'Kuwait', 'KW', 'KWT', 'Asia', 'Kuwait City', 'Kuwaiti Dinar'],
        ['kyrgyzstan', 'Kyrgyzstan', 'KG', 'KGZ', 'Asia', 'Bishkek', 'Kyrgyzstani Som'],
        ['laos', 'Laos', 'LA', 'LAO', 'Asia', 'Vientiane', 'Lao Kip'],
        ['lebanon', 'Lebanon', 'LB', 'LBN', 'Asia', 'Beirut', 'Lebanese Pound'],
        ['macau', 'Macau', 'MO', 'MAC', 'Asia', 'Macau', 'Macanese Pataca'],
        ['malaysia', 'Malaysia', 'MY', 'MYS', 'Asia', 'Kuala Lumpur', 'Malaysian Ringgit'],
        ['maldives', 'Maldives', 'MV', 'MDV', 'Asia', 'Malé', 'Maldivian Rufiyaa'],
        ['mongolia', 'Mongolia', 'MN', 'MNG', 'Asia', 'Ulaanbaatar', 'Mongolian Tögrög'],
        ['myanmar', 'Myanmar', 'MM', 'MMR', 'Asia', 'Naypyidaw', 'Myanmar Kyat'],
        ['nepal', 'Nepal', 'NP', 'NPL', 'Asia', 'Kathmandu', 'Nepalese Rupee'],
        ['north-korea', 'North Korea', 'KP', 'PRK', 'Asia', 'Pyongyang', 'North Korean Won'],
        ['oman', 'Oman', 'OM', 'OMN', 'Asia', 'Muscat', 'Omani Rial'],
        ['pakistan', 'Pakistan', 'PK', 'PAK', 'Asia', 'Islamabad', 'Pakistani Rupee'],
        ['palestine', 'Palestine', 'PS', 'PSE', 'Asia', 'Ramallah', 'Israeli New Shekel'],
        ['philippines', 'Philippines', 'PH', 'PHL', 'Asia', 'Manila', 'Philippine Peso'],
        ['qatar', 'Qatar', 'QA', 'QAT', 'Asia', 'Doha', 'Qatari Riyal'],
        ['saudi-arabia', 'Saudi Arabia', 'SA', 'SAU', 'Asia', 'Riyadh', 'Saudi Riyal'],
        ['singapore', 'Singapore', 'SG', 'SGP', 'Asia', 'Singapore', 'Singapore Dollar'],
        ['south-korea', 'South Korea', 'KR', 'KOR', 'Asia', 'Seoul', 'South Korean Won'],
        ['sri-lanka', 'Sri Lanka', 'LK', 'LKA', 'Asia', 'Colombo', 'Sri Lankan Rupee'],
        ['syria', 'Syria', 'SY', 'SYR', 'Asia', 'Damascus', 'Syrian Pound'],
        ['taiwan', 'Taiwan', 'TW', 'TWN', 'Asia', 'Taipei', 'New Taiwan Dollar'],
        ['tajikistan', 'Tajikistan', 'TJ', 'TJK', 'Asia', 'Dushanbe', 'Tajikistani Somoni'],
        ['thailand', 'Thailand', 'TH', 'THA', 'Asia', 'Bangkok', 'Thai Baht'],
        ['timor-leste', 'Timor-Leste', 'TL', 'TLS', 'Asia', 'Dili', 'United States Dollar'],
        ['turkey', 'Turkey', 'TR', 'TUR', 'Asia', 'Ankara', 'Turkish Lira'],
        ['turkmenistan', 'Turkmenistan', 'TM', 'TKM', 'Asia', 'Ashgabat', 'Turkmenistan Manat'],
        ['uae', 'United Arab Emirates', 'AE', 'ARE', 'Asia', 'Abu Dhabi', 'UAE Dirham'],
        ['uzbekistan', 'Uzbekistan', 'UZ', 'UZB', 'Asia', 'Tashkent', 'Uzbekistani Som'],
        ['vietnam', 'Vietnam', 'VN', 'VNM', 'Asia', 'Hanoi', 'Vietnamese Đồng'],
        ['yemen', 'Yemen', 'YE', 'YEM', 'Asia', "Sana'a", 'Yemeni Rial'],

        // Europe
        ['albania', 'Albania', 'AL', 'ALB', 'Europe', 'Tirana', 'Albanian Lek'],
        ['andorra', 'Andorra', 'AD', 'AND', 'Europe', 'Andorra la Vella', 'Euro'],
        ['austria', 'Austria', 'AT', 'AUT', 'Europe', 'Vienna', 'Euro'],
        ['belarus', 'Belarus', 'BY', 'BLR', 'Europe', 'Minsk', 'Belarusian Ruble'],
        ['belgium', 'Belgium', 'BE', 'BEL', 'Europe', 'Brussels', 'Euro'],
        ['bosnia-and-herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH', 'Europe', 'Sarajevo', 'Convertible Mark'],
        ['bulgaria', 'Bulgaria', 'BG', 'BGR', 'Europe', 'Sofia', 'Bulgarian Lev'],
        ['croatia', 'Croatia', 'HR', 'HRV', 'Europe', 'Zagreb', 'Euro'],
        ['czech-republic', 'Czech Republic', 'CZ', 'CZE', 'Europe', 'Prague', 'Czech Koruna'],
        ['denmark', 'Denmark', 'DK', 'DNK', 'Europe', 'Copenhagen', 'Danish Krone'],
        ['estonia', 'Estonia', 'EE', 'EST', 'Europe', 'Tallinn', 'Euro'],
        ['finland', 'Finland', 'FI', 'FIN', 'Europe', 'Helsinki', 'Euro'],
        ['france', 'France', 'FR', 'FRA', 'Europe', 'Paris', 'Euro'],
        ['germany', 'Germany', 'DE', 'DEU', 'Europe', 'Berlin', 'Euro'],
        ['greece', 'Greece', 'GR', 'GRC', 'Europe', 'Athens', 'Euro'],
        ['hungary', 'Hungary', 'HU', 'HUN', 'Europe', 'Budapest', 'Hungarian Forint'],
        ['iceland', 'Iceland', 'IS', 'ISL', 'Europe', 'Reykjavík', 'Icelandic Króna'],
        ['ireland', 'Ireland', 'IE', 'IRL', 'Europe', 'Dublin', 'Euro'],
        ['italy', 'Italy', 'IT', 'ITA', 'Europe', 'Rome', 'Euro'],
        ['kosovo', 'Kosovo', 'XK', 'XKX', 'Europe', 'Pristina', 'Euro'],
        ['latvia', 'Latvia', 'LV', 'LVA', 'Europe', 'Riga', 'Euro'],
        ['liechtenstein', 'Liechtenstein', 'LI', 'LIE', 'Europe', 'Vaduz', 'Swiss Franc'],
        ['lithuania', 'Lithuania', 'LT', 'LTU', 'Europe', 'Vilnius', 'Euro'],
        ['luxembourg', 'Luxembourg', 'LU', 'LUX', 'Europe', 'Luxembourg', 'Euro'],
        ['malta', 'Malta', 'MT', 'MLT', 'Europe', 'Valletta', 'Euro'],
        ['moldova', 'Moldova', 'MD', 'MDA', 'Europe', 'Chișinău', 'Moldovan Leu'],
        ['monaco', 'Monaco', 'MC', 'MCO', 'Europe', 'Monaco', 'Euro'],
        ['montenegro', 'Montenegro', 'ME', 'MNE', 'Europe', 'Podgorica', 'Euro'],
        ['netherlands', 'Netherlands', 'NL', 'NLD', 'Europe', 'Amsterdam', 'Euro'],
        ['north-macedonia', 'North Macedonia', 'MK', 'MKD', 'Europe', 'Skopje', 'Macedonian Denar'],
        ['norway', 'Norway', 'NO', 'NOR', 'Europe', 'Oslo', 'Norwegian Krone'],
        ['poland', 'Poland', 'PL', 'POL', 'Europe', 'Warsaw', 'Polish Złoty'],
        ['portugal', 'Portugal', 'PT', 'PRT', 'Europe', 'Lisbon', 'Euro'],
        ['romania', 'Romania', 'RO', 'ROU', 'Europe', 'Bucharest', 'Romanian Leu'],
        ['russia', 'Russia', 'RU', 'RUS', 'Europe', 'Moscow', 'Russian Ruble'],
        ['san-marino', 'San Marino', 'SM', 'SMR', 'Europe', 'San Marino', 'Euro'],
        ['serbia', 'Serbia', 'RS', 'SRB', 'Europe', 'Belgrade', 'Serbian Dinar'],
        ['slovakia', 'Slovakia', 'SK', 'SVK', 'Europe', 'Bratislava', 'Euro'],
        ['slovenia', 'Slovenia', 'SI', 'SVN', 'Europe', 'Ljubljana', 'Euro'],
        ['spain', 'Spain', 'ES', 'ESP', 'Europe', 'Madrid', 'Euro'],
        ['sweden', 'Sweden', 'SE', 'SWE', 'Europe', 'Stockholm', 'Swedish Krona'],
        ['switzerland', 'Switzerland', 'CH', 'CHE', 'Europe', 'Bern', 'Swiss Franc'],
        ['ukraine', 'Ukraine', 'UA', 'UKR', 'Europe', 'Kyiv', 'Ukrainian Hryvnia'],
        ['uk', 'United Kingdom', 'GB', 'GBR', 'Europe', 'London', 'British Pound'],
        ['vatican-city', 'Vatican City', 'VA', 'VAT', 'Europe', 'Vatican City', 'Euro'],

        // North America & Caribbean
        ['antigua-and-barbuda', 'Antigua and Barbuda', 'AG', 'ATG', 'North America', "Saint John's", 'East Caribbean Dollar'],
        ['bahamas', 'Bahamas', 'BS', 'BHS', 'North America', 'Nassau', 'Bahamian Dollar'],
        ['barbados', 'Barbados', 'BB', 'BRB', 'North America', 'Bridgetown', 'Barbadian Dollar'],
        ['belize', 'Belize', 'BZ', 'BLZ', 'North America', 'Belmopan', 'Belize Dollar'],
        ['canada', 'Canada', 'CA', 'CAN', 'North America', 'Ottawa', 'Canadian Dollar'],
        ['costa-rica', 'Costa Rica', 'CR', 'CRI', 'North America', 'San José', 'Costa Rican Colón'],
        ['cuba', 'Cuba', 'CU', 'CUB', 'North America', 'Havana', 'Cuban Peso'],
        ['dominica', 'Dominica', 'DM', 'DMA', 'North America', 'Roseau', 'East Caribbean Dollar'],
        ['dominican-republic', 'Dominican Republic', 'DO', 'DOM', 'North America', 'Santo Domingo', 'Dominican Peso'],
        ['el-salvador', 'El Salvador', 'SV', 'SLV', 'North America', 'San Salvador', 'United States Dollar'],
        ['grenada', 'Grenada', 'GD', 'GRD', 'North America', "St. George's", 'East Caribbean Dollar'],
        ['guatemala', 'Guatemala', 'GT', 'GTM', 'North America', 'Guatemala City', 'Guatemalan Quetzal'],
        ['haiti', 'Haiti', 'HT', 'HTI', 'North America', 'Port-au-Prince', 'Haitian Gourde'],
        ['honduras', 'Honduras', 'HN', 'HND', 'North America', 'Tegucigalpa', 'Honduran Lempira'],
        ['jamaica', 'Jamaica', 'JM', 'JAM', 'North America', 'Kingston', 'Jamaican Dollar'],
        ['mexico', 'Mexico', 'MX', 'MEX', 'North America', 'Mexico City', 'Mexican Peso'],
        ['nicaragua', 'Nicaragua', 'NI', 'NIC', 'North America', 'Managua', 'Nicaraguan Córdoba'],
        ['panama', 'Panama', 'PA', 'PAN', 'North America', 'Panama City', 'Panamanian Balboa'],
        ['saint-kitts-and-nevis', 'Saint Kitts and Nevis', 'KN', 'KNA', 'North America', 'Basseterre', 'East Caribbean Dollar'],
        ['saint-lucia', 'Saint Lucia', 'LC', 'LCA', 'North America', 'Castries', 'East Caribbean Dollar'],
        ['saint-vincent-and-the-grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'North America', 'Kingstown', 'East Caribbean Dollar'],
        ['trinidad-and-tobago', 'Trinidad and Tobago', 'TT', 'TTO', 'North America', 'Port of Spain', 'Trinidad and Tobago Dollar'],
        ['usa', 'United States', 'US', 'USA', 'North America', 'Washington, D.C.', 'United States Dollar'],

        // South America
        ['argentina', 'Argentina', 'AR', 'ARG', 'South America', 'Buenos Aires', 'Argentine Peso'],
        ['bolivia', 'Bolivia', 'BO', 'BOL', 'South America', 'Sucre', 'Bolivian Boliviano'],
        ['brazil', 'Brazil', 'BR', 'BRA', 'South America', 'Brasília', 'Brazilian Real'],
        ['chile', 'Chile', 'CL', 'CHL', 'South America', 'Santiago', 'Chilean Peso'],
        ['colombia', 'Colombia', 'CO', 'COL', 'South America', 'Bogotá', 'Colombian Peso'],
        ['ecuador', 'Ecuador', 'EC', 'ECU', 'South America', 'Quito', 'United States Dollar'],
        ['guyana', 'Guyana', 'GY', 'GUY', 'South America', 'Georgetown', 'Guyanese Dollar'],
        ['paraguay', 'Paraguay', 'PY', 'PRY', 'South America', 'Asunción', 'Paraguayan Guaraní'],
        ['peru', 'Peru', 'PE', 'PER', 'South America', 'Lima', 'Peruvian Sol'],
        ['suriname', 'Suriname', 'SR', 'SUR', 'South America', 'Paramaribo', 'Surinamese Dollar'],
        ['uruguay', 'Uruguay', 'UY', 'URY', 'South America', 'Montevideo', 'Uruguayan Peso'],
        ['venezuela', 'Venezuela', 'VE', 'VEN', 'South America', 'Caracas', 'Venezuelan Bolívar'],

        // Oceania
        ['australia', 'Australia', 'AU', 'AUS', 'Oceania', 'Canberra', 'Australian Dollar'],
        ['fiji', 'Fiji', 'FJ', 'FJI', 'Oceania', 'Suva', 'Fijian Dollar'],
        ['kiribati', 'Kiribati', 'KI', 'KIR', 'Oceania', 'Tarawa', 'Australian Dollar'],
        ['marshall-islands', 'Marshall Islands', 'MH', 'MHL', 'Oceania', 'Majuro', 'United States Dollar'],
        ['micronesia', 'Micronesia', 'FM', 'FSM', 'Oceania', 'Palikir', 'United States Dollar'],
        ['nauru', 'Nauru', 'NR', 'NRU', 'Oceania', 'Yaren', 'Australian Dollar'],
        ['new-zealand', 'New Zealand', 'NZ', 'NZL', 'Oceania', 'Wellington', 'New Zealand Dollar'],
        ['palau', 'Palau', 'PW', 'PLW', 'Oceania', 'Ngerulmud', 'United States Dollar'],
        ['papua-new-guinea', 'Papua New Guinea', 'PG', 'PNG', 'Oceania', 'Port Moresby', 'Papua New Guinean Kina'],
        ['samoa', 'Samoa', 'WS', 'WSM', 'Oceania', 'Apia', 'Samoan Tālā'],
        ['solomon-islands', 'Solomon Islands', 'SB', 'SLB', 'Oceania', 'Honiara', 'Solomon Islands Dollar'],
        ['tonga', 'Tonga', 'TO', 'TON', 'Oceania', "Nuku'alofa", 'Tongan Paʻanga'],
        ['tuvalu', 'Tuvalu', 'TV', 'TUV', 'Oceania', 'Funafuti', 'Australian Dollar'],
        ['vanuatu', 'Vanuatu', 'VU', 'VUT', 'Oceania', 'Port Vila', 'Vanuatu Vatu'],
    ];
}
