<?php
/**
 * Static country dataset (data-ready structure).
 * Swap this for a real `countries` DB table later — every consumer
 * (nav mega-menu, homepage sections, country explorer, country pages)
 * reads this array, not hard-coded markup, so that swap only touches
 * this one file.
 */
$VISA_AGENCY_COUNTRIES = [
    ['name' => 'Afghanistan', 'slug' => 'afghanistan', 'region' => 'Asia', 'flag' => '🇦🇫', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Albania', 'slug' => 'albania', 'region' => 'Europe', 'flag' => '🇦🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Algeria', 'slug' => 'algeria', 'region' => 'Africa', 'flag' => '🇩🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Andorra', 'slug' => 'andorra', 'region' => 'Europe', 'flag' => '🇦🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Angola', 'slug' => 'angola', 'region' => 'Africa', 'flag' => '🇦🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Antigua and Barbuda', 'slug' => 'antigua-and-barbuda', 'region' => 'North America', 'flag' => '🇦🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Argentina', 'slug' => 'argentina', 'region' => 'South America', 'flag' => '🇦🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Armenia', 'slug' => 'armenia', 'region' => 'Asia', 'flag' => '🇦🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Aruba', 'slug' => 'aruba', 'region' => 'North America', 'flag' => '🇦🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Australia', 'slug' => 'australia', 'region' => 'Oceania', 'flag' => '🇦🇺', 'types' => ['Tourist', 'Work', 'Family']],
    ['name' => 'Austria', 'slug' => 'austria', 'region' => 'Europe', 'flag' => '🇦🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Azerbaijan', 'slug' => 'azerbaijan', 'region' => 'Asia', 'flag' => '🇦🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bahamas', 'slug' => 'bahamas', 'region' => 'North America', 'flag' => '🇧🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bahrain', 'slug' => 'bahrain', 'region' => 'Middle East', 'flag' => '🇧🇭', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bangladesh', 'slug' => 'bangladesh', 'region' => 'Asia', 'flag' => '🇧🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Barbados', 'slug' => 'barbados', 'region' => 'North America', 'flag' => '🇧🇧', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Belarus', 'slug' => 'belarus', 'region' => 'Europe', 'flag' => '🇧🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Belgium', 'slug' => 'belgium', 'region' => 'Europe', 'flag' => '🇧🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Belize', 'slug' => 'belize', 'region' => 'North America', 'flag' => '🇧🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Benin', 'slug' => 'benin', 'region' => 'Africa', 'flag' => '🇧🇯', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bhutan', 'slug' => 'bhutan', 'region' => 'Asia', 'flag' => '🇧🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bolivia', 'slug' => 'bolivia', 'region' => 'South America', 'flag' => '🇧🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bosnia and Herzegovina', 'slug' => 'bosnia-and-herzegovina', 'region' => 'Europe', 'flag' => '🇧🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Botswana', 'slug' => 'botswana', 'region' => 'Africa', 'flag' => '🇧🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Brazil', 'slug' => 'brazil', 'region' => 'South America', 'flag' => '🇧🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Brunei', 'slug' => 'brunei', 'region' => 'Asia', 'flag' => '🇧🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Bulgaria', 'slug' => 'bulgaria', 'region' => 'Europe', 'flag' => '🇧🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Burkina Faso', 'slug' => 'burkina-faso', 'region' => 'Africa', 'flag' => '🇧🇫', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Burundi', 'slug' => 'burundi', 'region' => 'Africa', 'flag' => '🇧🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Cabo Verde', 'slug' => 'cabo-verde', 'region' => 'Africa', 'flag' => '🇨🇻', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Cambodia', 'slug' => 'cambodia', 'region' => 'Asia', 'flag' => '🇰🇭', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Cameroon', 'slug' => 'cameroon', 'region' => 'Africa', 'flag' => '🇨🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Canada', 'slug' => 'canada', 'region' => 'North America', 'flag' => '🇨🇦', 'types' => ['Tourist', 'Work', 'Family']],
    ['name' => 'Central African Republic', 'slug' => 'central-african-republic', 'region' => 'Africa', 'flag' => '🇨🇫', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Chad', 'slug' => 'chad', 'region' => 'Africa', 'flag' => '🇹🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Chile', 'slug' => 'chile', 'region' => 'South America', 'flag' => '🇨🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'China', 'slug' => 'china', 'region' => 'Asia', 'flag' => '🇨🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Colombia', 'slug' => 'colombia', 'region' => 'South America', 'flag' => '🇨🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Comoros', 'slug' => 'comoros', 'region' => 'Africa', 'flag' => '🇰🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Congo Republic', 'slug' => 'congo-republic', 'region' => 'Africa', 'flag' => '🇨🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Cook Islands', 'slug' => 'cook-islands', 'region' => 'Oceania', 'flag' => '🇨🇰', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Costa Rica', 'slug' => 'costa-rica', 'region' => 'North America', 'flag' => '🇨🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Croatia', 'slug' => 'croatia', 'region' => 'Europe', 'flag' => '🇭🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Cuba', 'slug' => 'cuba', 'region' => 'North America', 'flag' => '🇨🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Curacao', 'slug' => 'curacao', 'region' => 'North America', 'flag' => '🇨🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Cyprus', 'slug' => 'cyprus', 'region' => 'Europe', 'flag' => '🇨🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Czech Republic', 'slug' => 'czech-republic', 'region' => 'Europe', 'flag' => '🇨🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Denmark', 'slug' => 'denmark', 'region' => 'Europe', 'flag' => '🇩🇰', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Djibouti', 'slug' => 'djibouti', 'region' => 'Africa', 'flag' => '🇩🇯', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Dominica', 'slug' => 'dominica', 'region' => 'North America', 'flag' => '🇩🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Dominican Republic', 'slug' => 'dominican-republic', 'region' => 'North America', 'flag' => '🇩🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'DR Congo', 'slug' => 'dr-congo', 'region' => 'Africa', 'flag' => '🇨🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Ecuador', 'slug' => 'ecuador', 'region' => 'South America', 'flag' => '🇪🇨', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Egypt', 'slug' => 'egypt', 'region' => 'Africa', 'flag' => '🇪🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'El Salvador', 'slug' => 'el-salvador', 'region' => 'North America', 'flag' => '🇸🇻', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Equatorial Guinea', 'slug' => 'equatorial-guinea', 'region' => 'Africa', 'flag' => '🇬🇶', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Eritrea', 'slug' => 'eritrea', 'region' => 'Africa', 'flag' => '🇪🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Estonia', 'slug' => 'estonia', 'region' => 'Europe', 'flag' => '🇪🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Eswatini', 'slug' => 'eswatini', 'region' => 'Africa', 'flag' => '🇸🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Ethiopia', 'slug' => 'ethiopia', 'region' => 'Africa', 'flag' => '🇪🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Fiji', 'slug' => 'fiji', 'region' => 'Oceania', 'flag' => '🇫🇯', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Finland', 'slug' => 'finland', 'region' => 'Europe', 'flag' => '🇫🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'France', 'slug' => 'france', 'region' => 'Europe', 'flag' => '🇫🇷', 'types' => ['Tourist', 'Business']],
    ['name' => 'French Polynesia', 'slug' => 'french-polynesia', 'region' => 'Oceania', 'flag' => '🇵🇫', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Gabon', 'slug' => 'gabon', 'region' => 'Africa', 'flag' => '🇬🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Gambia', 'slug' => 'gambia', 'region' => 'Africa', 'flag' => '🇬🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Georgia', 'slug' => 'georgia', 'region' => 'Asia', 'flag' => '🇬🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Germany', 'slug' => 'germany', 'region' => 'Europe', 'flag' => '🇩🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Ghana', 'slug' => 'ghana', 'region' => 'Africa', 'flag' => '🇬🇭', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Greece', 'slug' => 'greece', 'region' => 'Europe', 'flag' => '🇬🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Greenland', 'slug' => 'greenland', 'region' => 'North America', 'flag' => '🇬🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Grenada', 'slug' => 'grenada', 'region' => 'North America', 'flag' => '🇬🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Guatemala', 'slug' => 'guatemala', 'region' => 'North America', 'flag' => '🇬🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Guinea', 'slug' => 'guinea', 'region' => 'Africa', 'flag' => '🇬🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Guinea-Bissau', 'slug' => 'guinea-bissau', 'region' => 'Africa', 'flag' => '🇬🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Guyana', 'slug' => 'guyana', 'region' => 'South America', 'flag' => '🇬🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Haiti', 'slug' => 'haiti', 'region' => 'North America', 'flag' => '🇭🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Honduras', 'slug' => 'honduras', 'region' => 'North America', 'flag' => '🇭🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Hong Kong', 'slug' => 'hong-kong', 'region' => 'Asia', 'flag' => '🇭🇰', 'types' => ['Tourist', 'Business']],
    ['name' => 'Hungary', 'slug' => 'hungary', 'region' => 'Europe', 'flag' => '🇭🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Iceland', 'slug' => 'iceland', 'region' => 'Europe', 'flag' => '🇮🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'India', 'slug' => 'india', 'region' => 'Asia', 'flag' => '🇮🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Indonesia', 'slug' => 'indonesia', 'region' => 'Asia', 'flag' => '🇮🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Iran', 'slug' => 'iran', 'region' => 'Middle East', 'flag' => '🇮🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Iraq', 'slug' => 'iraq', 'region' => 'Middle East', 'flag' => '🇮🇶', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Ireland', 'slug' => 'ireland', 'region' => 'Europe', 'flag' => '🇮🇪', 'types' => ['Tourist', 'Work']],
    ['name' => 'Israel', 'slug' => 'israel', 'region' => 'Middle East', 'flag' => '🇮🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Italy', 'slug' => 'italy', 'region' => 'Europe', 'flag' => '🇮🇹', 'types' => ['Tourist', 'Business']],
    ['name' => 'Ivory Coast', 'slug' => 'ivory-coast', 'region' => 'Africa', 'flag' => '🇨🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Jamaica', 'slug' => 'jamaica', 'region' => 'North America', 'flag' => '🇯🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Japan', 'slug' => 'japan', 'region' => 'Asia', 'flag' => '🇯🇵', 'types' => ['Tourist', 'Business']],
    ['name' => 'Jordan', 'slug' => 'jordan', 'region' => 'Middle East', 'flag' => '🇯🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Kazakhstan', 'slug' => 'kazakhstan', 'region' => 'Asia', 'flag' => '🇰🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Kenya', 'slug' => 'kenya', 'region' => 'Africa', 'flag' => '🇰🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Kiribati', 'slug' => 'kiribati', 'region' => 'Oceania', 'flag' => '🇰🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Kuwait', 'slug' => 'kuwait', 'region' => 'Middle East', 'flag' => '🇰🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Kyrgyzstan', 'slug' => 'kyrgyzstan', 'region' => 'Asia', 'flag' => '🇰🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Laos', 'slug' => 'laos', 'region' => 'Asia', 'flag' => '🇱🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Latvia', 'slug' => 'latvia', 'region' => 'Europe', 'flag' => '🇱🇻', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Lebanon', 'slug' => 'lebanon', 'region' => 'Middle East', 'flag' => '🇱🇧', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Lesotho', 'slug' => 'lesotho', 'region' => 'Africa', 'flag' => '🇱🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Liberia', 'slug' => 'liberia', 'region' => 'Africa', 'flag' => '🇱🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Libya', 'slug' => 'libya', 'region' => 'Africa', 'flag' => '🇱🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Liechtenstein', 'slug' => 'liechtenstein', 'region' => 'Europe', 'flag' => '🇱🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Lithuania', 'slug' => 'lithuania', 'region' => 'Europe', 'flag' => '🇱🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Luxembourg', 'slug' => 'luxembourg', 'region' => 'Europe', 'flag' => '🇱🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Macau', 'slug' => 'macau', 'region' => 'Asia', 'flag' => '🇲🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Madagascar', 'slug' => 'madagascar', 'region' => 'Africa', 'flag' => '🇲🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Malaysia', 'slug' => 'malaysia', 'region' => 'Asia', 'flag' => '🇲🇾', 'types' => ['Tourist', 'E-Visa']],
    ['name' => 'Maldives', 'slug' => 'maldives', 'region' => 'Asia', 'flag' => '🇲🇻', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Mali', 'slug' => 'mali', 'region' => 'Africa', 'flag' => '🇲🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Malta', 'slug' => 'malta', 'region' => 'Europe', 'flag' => '🇲🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Marshall Islands', 'slug' => 'marshall-islands', 'region' => 'Oceania', 'flag' => '🇲🇭', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Mauritania', 'slug' => 'mauritania', 'region' => 'Africa', 'flag' => '🇲🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Mauritius', 'slug' => 'mauritius', 'region' => 'Africa', 'flag' => '🇲🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Mexico', 'slug' => 'mexico', 'region' => 'North America', 'flag' => '🇲🇽', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Micronesia', 'slug' => 'micronesia', 'region' => 'Oceania', 'flag' => '🇫🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Moldova', 'slug' => 'moldova', 'region' => 'Europe', 'flag' => '🇲🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Monaco', 'slug' => 'monaco', 'region' => 'Europe', 'flag' => '🇲🇨', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Mongolia', 'slug' => 'mongolia', 'region' => 'Asia', 'flag' => '🇲🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Montenegro', 'slug' => 'montenegro', 'region' => 'Europe', 'flag' => '🇲🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Morocco', 'slug' => 'morocco', 'region' => 'Africa', 'flag' => '🇲🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Mozambique', 'slug' => 'mozambique', 'region' => 'Africa', 'flag' => '🇲🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Myanmar', 'slug' => 'myanmar', 'region' => 'Asia', 'flag' => '🇲🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Namibia', 'slug' => 'namibia', 'region' => 'Africa', 'flag' => '🇳🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Nauru', 'slug' => 'nauru', 'region' => 'Oceania', 'flag' => '🇳🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Nepal', 'slug' => 'nepal', 'region' => 'Asia', 'flag' => '🇳🇵', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Netherlands', 'slug' => 'netherlands', 'region' => 'Europe', 'flag' => '🇳🇱', 'types' => ['Tourist', 'Business']],
    ['name' => 'New Caledonia', 'slug' => 'new-caledonia', 'region' => 'Oceania', 'flag' => '🇳🇨', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'New Zealand', 'slug' => 'new-zealand', 'region' => 'Oceania', 'flag' => '🇳🇿', 'types' => ['Tourist', 'Work', 'Family']],
    ['name' => 'Nicaragua', 'slug' => 'nicaragua', 'region' => 'North America', 'flag' => '🇳🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Niger', 'slug' => 'niger', 'region' => 'Africa', 'flag' => '🇳🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Nigeria', 'slug' => 'nigeria', 'region' => 'Africa', 'flag' => '🇳🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Niue', 'slug' => 'niue', 'region' => 'Oceania', 'flag' => '🇳🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'North Macedonia', 'slug' => 'north-macedonia', 'region' => 'Europe', 'flag' => '🇲🇰', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Norway', 'slug' => 'norway', 'region' => 'Europe', 'flag' => '🇳🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Oman', 'slug' => 'oman', 'region' => 'Middle East', 'flag' => '🇴🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Pakistan', 'slug' => 'pakistan', 'region' => 'Asia', 'flag' => '🇵🇰', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Palau', 'slug' => 'palau', 'region' => 'Oceania', 'flag' => '🇵🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Palestine', 'slug' => 'palestine', 'region' => 'Middle East', 'flag' => '🇵🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Panama', 'slug' => 'panama', 'region' => 'North America', 'flag' => '🇵🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Papua New Guinea', 'slug' => 'papua-new-guinea', 'region' => 'Oceania', 'flag' => '🇵🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Paraguay', 'slug' => 'paraguay', 'region' => 'South America', 'flag' => '🇵🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Peru', 'slug' => 'peru', 'region' => 'South America', 'flag' => '🇵🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Philippines', 'slug' => 'philippines', 'region' => 'Asia', 'flag' => '🇵🇭', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Poland', 'slug' => 'poland', 'region' => 'Europe', 'flag' => '🇵🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Portugal', 'slug' => 'portugal', 'region' => 'Europe', 'flag' => '🇵🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Qatar', 'slug' => 'qatar', 'region' => 'Middle East', 'flag' => '🇶🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Romania', 'slug' => 'romania', 'region' => 'Europe', 'flag' => '🇷🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Russia', 'slug' => 'russia', 'region' => 'Europe', 'flag' => '🇷🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Rwanda', 'slug' => 'rwanda', 'region' => 'Africa', 'flag' => '🇷🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Saint Kitts and Nevis', 'slug' => 'saint-kitts-and-nevis', 'region' => 'North America', 'flag' => '🇰🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Saint Lucia', 'slug' => 'saint-lucia', 'region' => 'North America', 'flag' => '🇱🇨', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Saint Vincent and the Grenadines', 'slug' => 'saint-vincent-and-the-grenadines', 'region' => 'North America', 'flag' => '🇻🇨', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Samoa', 'slug' => 'samoa', 'region' => 'Oceania', 'flag' => '🇼🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'San Marino', 'slug' => 'san-marino', 'region' => 'Europe', 'flag' => '🇸🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Sao Tome and Principe', 'slug' => 'sao-tome-and-principe', 'region' => 'Africa', 'flag' => '🇸🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Saudi Arabia', 'slug' => 'saudi-arabia', 'region' => 'Middle East', 'flag' => '🇸🇦', 'types' => ['Business', 'Work', 'Medical']],
    ['name' => 'Senegal', 'slug' => 'senegal', 'region' => 'Africa', 'flag' => '🇸🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Serbia', 'slug' => 'serbia', 'region' => 'Europe', 'flag' => '🇷🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Seychelles', 'slug' => 'seychelles', 'region' => 'Africa', 'flag' => '🇸🇨', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Sierra Leone', 'slug' => 'sierra-leone', 'region' => 'Africa', 'flag' => '🇸🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Singapore', 'slug' => 'singapore', 'region' => 'Asia', 'flag' => '🇸🇬', 'types' => ['Tourist', 'Business', 'Transit']],
    ['name' => 'Slovakia', 'slug' => 'slovakia', 'region' => 'Europe', 'flag' => '🇸🇰', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Slovenia', 'slug' => 'slovenia', 'region' => 'Europe', 'flag' => '🇸🇮', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Solomon Islands', 'slug' => 'solomon-islands', 'region' => 'Oceania', 'flag' => '🇸🇧', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Somalia', 'slug' => 'somalia', 'region' => 'Africa', 'flag' => '🇸🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'South Africa', 'slug' => 'south-africa', 'region' => 'Africa', 'flag' => '🇿🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'South Korea', 'slug' => 'south-korea', 'region' => 'Asia', 'flag' => '🇰🇷', 'types' => ['Tourist', 'Business', 'E-Visa']],
    ['name' => 'South Sudan', 'slug' => 'south-sudan', 'region' => 'Africa', 'flag' => '🇸🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Spain', 'slug' => 'spain', 'region' => 'Europe', 'flag' => '🇪🇸', 'types' => ['Tourist', 'Business']],
    ['name' => 'Sri Lanka', 'slug' => 'sri-lanka', 'region' => 'Asia', 'flag' => '🇱🇰', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Sudan', 'slug' => 'sudan', 'region' => 'Africa', 'flag' => '🇸🇩', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Suriname', 'slug' => 'suriname', 'region' => 'South America', 'flag' => '🇸🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Sweden', 'slug' => 'sweden', 'region' => 'Europe', 'flag' => '🇸🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Switzerland', 'slug' => 'switzerland', 'region' => 'Europe', 'flag' => '🇨🇭', 'types' => ['Tourist', 'Business']],
    ['name' => 'Syria', 'slug' => 'syria', 'region' => 'Middle East', 'flag' => '🇸🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Taiwan', 'slug' => 'taiwan', 'region' => 'Asia', 'flag' => '🇹🇼', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Tajikistan', 'slug' => 'tajikistan', 'region' => 'Asia', 'flag' => '🇹🇯', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Tanzania', 'slug' => 'tanzania', 'region' => 'Africa', 'flag' => '🇹🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Thailand', 'slug' => 'thailand', 'region' => 'Asia', 'flag' => '🇹🇭', 'types' => ['Tourist', 'E-Visa']],
    ['name' => 'Timor-Leste', 'slug' => 'timor-leste', 'region' => 'Asia', 'flag' => '🇹🇱', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Togo', 'slug' => 'togo', 'region' => 'Africa', 'flag' => '🇹🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Tonga', 'slug' => 'tonga', 'region' => 'Oceania', 'flag' => '🇹🇴', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Trinidad and Tobago', 'slug' => 'trinidad-and-tobago', 'region' => 'North America', 'flag' => '🇹🇹', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Tunisia', 'slug' => 'tunisia', 'region' => 'Africa', 'flag' => '🇹🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Turkey', 'slug' => 'turkey', 'region' => 'Middle East', 'flag' => '🇹🇷', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Turkmenistan', 'slug' => 'turkmenistan', 'region' => 'Asia', 'flag' => '🇹🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Tuvalu', 'slug' => 'tuvalu', 'region' => 'Oceania', 'flag' => '🇹🇻', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'UAE', 'slug' => 'uae', 'region' => 'Middle East', 'flag' => '🇦🇪', 'types' => ['Tourist', 'Business', 'Work', 'Transit']],
    ['name' => 'Uganda', 'slug' => 'uganda', 'region' => 'Africa', 'flag' => '🇺🇬', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Ukraine', 'slug' => 'ukraine', 'region' => 'Europe', 'flag' => '🇺🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'United Kingdom', 'slug' => 'uk', 'region' => 'Europe', 'flag' => '🇬🇧', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'United States', 'slug' => 'usa', 'region' => 'North America', 'flag' => '🇺🇸', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Uruguay', 'slug' => 'uruguay', 'region' => 'South America', 'flag' => '🇺🇾', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Uzbekistan', 'slug' => 'uzbekistan', 'region' => 'Asia', 'flag' => '🇺🇿', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Vanuatu', 'slug' => 'vanuatu', 'region' => 'Oceania', 'flag' => '🇻🇺', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Vatican City', 'slug' => 'vatican-city', 'region' => 'Europe', 'flag' => '🇻🇦', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Venezuela', 'slug' => 'venezuela', 'region' => 'South America', 'flag' => '🇻🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Vietnam', 'slug' => 'vietnam', 'region' => 'Asia', 'flag' => '🇻🇳', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Yemen', 'slug' => 'yemen', 'region' => 'Middle East', 'flag' => '🇾🇪', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Zambia', 'slug' => 'zambia', 'region' => 'Africa', 'flag' => '🇿🇲', 'types' => ['Tourist', 'Business', 'Work']],
    ['name' => 'Zimbabwe', 'slug' => 'zimbabwe', 'region' => 'Africa', 'flag' => '🇿🇼', 'types' => ['Tourist', 'Business', 'Work']],
];
