<?php
/**
 * Phase 4 of the state/city location pages — completes coverage of the
 * remaining states and union territories: Jammu & Kashmir, Chandigarh,
 * Puducherry, Ladakh, Andaman & Nicobar Islands, Lakshadweep, Dadra and
 * Nagar Haveli and Daman and Diu, Arunachal Pradesh, Manipur, Meghalaya,
 * Mizoram, Nagaland, Sikkim and Tripura.
 *
 * These are smaller/lower-population states and UTs than phases 1-3, so
 * most get a state-level page only rather than a forced second-tier city
 * page — inventing a "distinguishing fact" for a city we have no genuine
 * information about would be exactly the kind of thin/fabricated content
 * the brief warns against. Same remote-service disclosure as every other
 * phase; no location here is ever described as a physical office.
 *
 * Loaded by location_seed_all() in includes/location-db.php.
 */
function location_seed_states_def_phase4(): array
{
    return [
        [
            'slug' => 'jammu-and-kashmir',
            'name' => 'Jammu and Kashmir',
            'kind' => 'union_territory',
            'sort_order' => 23,
            'intro_html' => '<p>Jammu and Kashmir sends us residents\' own outbound tourist, business and family-visit visa applications. As with our other pilgrimage/tourism-significant locations, our role is helping J&amp;K residents travel abroad &mdash; not inbound tourist visas for people visiting the region.</p>',
            'service_model_html' => '<p>We do not have a physical office in Jammu and Kashmir. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Jammu and Kashmir | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Jammu and Kashmir — tourist, business and family visa application assistance, served remotely.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Jammu and Kashmir?', 'a' => '<p>No. Jammu and Kashmir is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'ladakh',
            'name' => 'Ladakh',
            'kind' => 'union_territory',
            'sort_order' => 24,
            'intro_html' => '<p>Ladakh is one of the smaller, more remote union territories we serve. We support Ladakh residents\' own outbound tourist, business and family-visit visa applications, entirely remotely.</p>',
            'service_model_html' => '<p>We do not have a physical office in Ladakh. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Ladakh | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Ladakh — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Ladakh?', 'a' => '<p>No. Ladakh is served remotely from our Patna office, the same as every location outside Bihar.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'chandigarh',
            'name' => 'Chandigarh',
            'kind' => 'union_territory',
            'sort_order' => 25,
            'intro_html' => '<p>Chandigarh, a planned city serving as the joint capital of Punjab and Haryana, sends us tourist, business and family-visit applicants, including some of the same Canada/UK/Australia family-visit demand pattern seen in neighbouring Punjab.</p>',
            'service_model_html' => '<p>We do not have a physical office in Chandigarh. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Chandigarh | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Chandigarh — tourist, business and family visa application assistance, served remotely.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Chandigarh?', 'a' => '<p>No. Chandigarh is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'puducherry',
            'name' => 'Puducherry',
            'kind' => 'union_territory',
            'sort_order' => 26,
            'intro_html' => '<p>Puducherry, a former French colonial territory with a distinct heritage and a meaningful historical connection to France, sends us tourist, business and family-visit applicants &mdash; including some with genuine family or cultural ties to France specifically.</p>',
            'service_model_html' => '<p>We do not have a physical office in Puducherry. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Puducherry | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Puducherry — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Puducherry?', 'a' => '<p>No. Puducherry is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'andaman-and-nicobar-islands',
            'name' => 'Andaman and Nicobar Islands',
            'kind' => 'union_territory',
            'sort_order' => 27,
            'intro_html' => '<p>The Andaman and Nicobar Islands are one of the more remote union territories we serve. We support residents\' own outbound tourist, business and family-visit visa applications, entirely remotely, with courier logistics adjusted for the islands\' location.</p>',
            'service_model_html' => '<p>We do not have a physical office in the Andaman and Nicobar Islands. Applicants are supported remotely &mdash; phone and video consultations and document review over WhatsApp/email, with courier timelines for original documents adjusted for the islands\' location.</p>',
            'seo_title' => 'Visa Consultant in Andaman and Nicobar Islands | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of the Andaman and Nicobar Islands — tourist, business and family visa application assistance, served remotely.',
            'faqs' => [['q' => 'Can you courier documents to/from the Andaman and Nicobar Islands?', 'a' => '<p>Yes, though courier timelines are naturally longer given the islands\' location &mdash; we\'ll give you a realistic estimate as part of your consultation.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'lakshadweep',
            'name' => 'Lakshadweep',
            'kind' => 'union_territory',
            'sort_order' => 28,
            'intro_html' => '<p>Lakshadweep is the smallest union territory we serve. We support residents\' own outbound tourist, business and family-visit visa applications, entirely remotely, with courier logistics adjusted for the islands\' location.</p>',
            'service_model_html' => '<p>We do not have a physical office in Lakshadweep. Applicants are supported remotely &mdash; phone and video consultations and document review over WhatsApp/email, with courier timelines for original documents adjusted for the islands\' location.</p>',
            'seo_title' => 'Visa Consultant in Lakshadweep | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Lakshadweep — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Lakshadweep?', 'a' => '<p>No. Lakshadweep is served remotely from our Patna office, with courier timelines adjusted for the islands\' location.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'dadra-and-nagar-haveli-and-daman-and-diu',
            'name' => 'Dadra and Nagar Haveli and Daman and Diu',
            'kind' => 'union_territory',
            'sort_order' => 29,
            'intro_html' => '<p>Dadra and Nagar Haveli and Daman and Diu sends us tourist, business and family-visit applicants, including business travellers connected to the union territory\'s manufacturing and industrial base.</p>',
            'service_model_html' => '<p>We do not have a physical office in Dadra and Nagar Haveli and Daman and Diu. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Dadra and Nagar Haveli and Daman and Diu | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Dadra and Nagar Haveli and Daman and Diu — tourist, business and family visa application assistance.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Dadra and Nagar Haveli and Daman and Diu?', 'a' => '<p>No. This union territory is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'arunachal-pradesh',
            'name' => 'Arunachal Pradesh',
            'sort_order' => 30,
            'intro_html' => '<p>Arunachal Pradesh, India\'s north-easternmost state, sends us residents\' own outbound tourist, business and family-visit visa applications, entirely remotely.</p>',
            'service_model_html' => '<p>We do not have a physical office in Arunachal Pradesh. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Arunachal Pradesh | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Arunachal Pradesh — tourist, business and family visa application assistance, served remotely.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Arunachal Pradesh?', 'a' => '<p>No. Arunachal Pradesh is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'manipur',
            'name' => 'Manipur',
            'sort_order' => 31,
            'intro_html' => '<p>Manipur sends us residents\' own outbound tourist, business and family-visit visa applications, entirely remotely, the same as every state we serve outside Bihar.</p>',
            'service_model_html' => '<p>We do not have a physical office in Manipur. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Manipur | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Manipur — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Manipur?', 'a' => '<p>No. Manipur is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'meghalaya',
            'name' => 'Meghalaya',
            'sort_order' => 32,
            'intro_html' => '<p>Meghalaya, known for its own significant domestic and international tourism draw, sends us residents\' own outbound tourist, business and family-visit visa applications.</p>',
            'service_model_html' => '<p>We do not have a physical office in Meghalaya. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Meghalaya | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Meghalaya — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Meghalaya?', 'a' => '<p>No. Meghalaya is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'mizoram',
            'name' => 'Mizoram',
            'sort_order' => 33,
            'intro_html' => '<p>Mizoram sends us residents\' own outbound tourist, business and family-visit visa applications, entirely remotely, the same as every state we serve outside Bihar.</p>',
            'service_model_html' => '<p>We do not have a physical office in Mizoram. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Mizoram | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Mizoram — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Mizoram?', 'a' => '<p>No. Mizoram is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'nagaland',
            'name' => 'Nagaland',
            'sort_order' => 34,
            'intro_html' => '<p>Nagaland sends us residents\' own outbound tourist, business and family-visit visa applications, entirely remotely, the same as every state we serve outside Bihar.</p>',
            'service_model_html' => '<p>We do not have a physical office in Nagaland. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Nagaland | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Nagaland — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Nagaland?', 'a' => '<p>No. Nagaland is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'sikkim',
            'name' => 'Sikkim',
            'sort_order' => 35,
            'intro_html' => '<p>Sikkim, one of India\'s smallest states by population and a significant tourism destination itself, sends us residents\' own outbound tourist, business and family-visit visa applications.</p>',
            'service_model_html' => '<p>We do not have a physical office in Sikkim. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Sikkim | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Sikkim — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Sikkim?', 'a' => '<p>No. Sikkim is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
        [
            'slug' => 'tripura',
            'name' => 'Tripura',
            'sort_order' => 36,
            'intro_html' => '<p>Tripura sends us residents\' own outbound tourist, business and family-visit visa applications, entirely remotely, the same as every state we serve outside Bihar.</p>',
            'service_model_html' => '<p>We do not have a physical office in Tripura. Applicants are supported remotely &mdash; phone and video consultations, document review over WhatsApp/email, and courier collection where an original document is required.</p>',
            'seo_title' => 'Visa Consultant in Tripura | Visa Agency',
            'meta_description' => 'Visa consultancy for residents of Tripura — tourist, business and family visa application assistance, served remotely from our Patna office.',
            'faqs' => [['q' => 'Does VisaAgency.in have an office in Tripura?', 'a' => '<p>No. Tripura is served remotely from our Patna office.</p>']],
            'cities' => [],
        ],
    ];
}
