<?php
/**
 * Phase 3A -- Extension Visa gap-closure research for 12 of the 16 Tier-B
 * cells that remained generic after Phase 3. 4 cells (kazakhstan, morocco,
 * tanzania, uzbekistan) still had zero genuine evidence and remain generic.
 * Preserves the Georgia (no tourist-extension mechanism; a genuinely separate
 * Residence Permit process exists, not mislabelled as an Extension Visa) and
 * Myanmar (Tourist eVisa has no extension path; Business eVisa extension
 * exists only via company sponsorship) governance distinctions established
 * during research. The Israel record excludes an unverified "6-12 month
 * processing" claim per the research audit's explicit instruction.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_phase3a_extension(): array
{
    return [
        [
            'page_slug' => 'china-visa-extension',
            'country_slug' => 'china',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of duration of stay, via the exit-entry departments of China\'s public security organs',
            'visa_subclass_code' => null,
            'intro_html' => '<p>China allows an "extension of duration of stay" for an existing visa, applied for at the exit-entry department of the local public security organs at least 7 days before the stay specified in the visa expires. The maximum extension period depends on the visa category actually held.</p>',
            'typical_stay' => 'C-visa (transit/crew-related): extendable up to 30 additional days. F-visa (business/exchange): extendable up to 180 additional days',
            'entry_type' => 'In-country, at the exit-entry department of the local public security bureau',
            'processing_time_text' => 'Apply at least 7 days before the visa\'s specified stay period expires',
            'validity_text' => 'C-visa: up to 30 extra days. F-visa: up to 180 extra days. Caps vary by visa category',
            'application_method' => 'In person at the exit-entry department of the public security organs in the city of stay',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Exit-entry department, local Public Security Bureau',
            'authority_name' => 'National Immigration Administration of China (en.nia.gov.cn)',
            'authority_url' => 'https://en.nia.gov.cn/n147423/n147478/n147715/c158249/content.html',
            'eligibility_html' => '<p>Extension of stay is available for existing visa holders, with the maximum extension period depending on the specific visa category: C-visa holders may submit a letter of certification from the relevant county-level government department or transportation company (up to 30 extra days); F-visa holders need a letter of certification from the inviting/receiving entity (up to 180 extra days).</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply at Least 7 Days Before Expiry</h4><p>Submit your extension request to the exit-entry department of the public security organs in your city of stay.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm Your Visa Category\'s Specific Cap</h4><p>Extension limits (30 vs. 180 days) depend on which visa type you hold — confirm with the exit-entry department directly.</p><p>Our consultants can help you confirm the certification letter required for your specific visa category.</p>',
            'seo_title' => 'China Visa Extension for Indians | Extension of Duration of Stay',
            'meta_description' => 'Need more time in China? See the exit-entry department extension process and category-specific caps, via VisaAgency.in.',
            'og_title' => 'China Visa Extension for Indians — Extension of Duration of Stay',
            'og_description' => 'Need more time in China? See the exit-entry department extension process and category-specific caps, via VisaAgency.in.',
            'documents' => [
                ['Supporting Documents', 'Letter of certification from the relevant county-level government department/transport company (C-visa)', 'conditional'],
                ['Supporting Documents', 'Letter of certification from the inviting/receiving entity (F-visa)', 'conditional'],
            ],
            'steps' => [
                ['Confirm Your Visa Category\'s Extension Cap', '30 days for C-visa, 180 days for F-visa.'],
                ['Obtain the Required Certification Letter', 'From the relevant government department, transport company, or inviting entity.'],
                ['Apply at the Local Exit-Entry Department', 'At least 7 days before your current stay expires.'],
            ],
            'faqs' => [
                ['How long can I extend my stay in China?', 'Up to 30 extra days for C-visa holders, or up to 180 extra days for F-visa holders — the cap depends on your visa category.'],
                ['When should I apply?', 'At least 7 days before your visa\'s specified stay period expires.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'National Immigration Administration of China (en.nia.gov.cn)',
                'url' => 'https://en.nia.gov.cn/n147423/n147478/n147715/c158249/content.html',
                'notes' => 'Phase 3A research: official en.nia.gov.cn "Guide on Visa Extension, Change and Reissuance for Foreigners" directly confirms the extension mechanism and visa-category-specific caps. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'fiji-visa-extension',
            'country_slug' => 'fiji',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Visitors Permit Extension, via the Fiji Ministry of Immigration',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Fiji\'s Ministry of Immigration offers a Visitors Permit Extension of up to 2 months, with no further extension possible after that. It must be applied for before the current Visitors Permit expires, and certain permit holders (Business Visitors Permit holders, and students/relatives on a 30-day Visitors Permit) are not eligible to apply.</p>',
            'typical_stay' => 'Up to 2 additional months (no further extension after this)',
            'entry_type' => 'In-country, at the Ministry of Immigration',
            'processing_time_text' => 'Apply before the current Visitors Permit expires',
            'validity_text' => 'Extends the Visitors Permit by up to 2 months, one time only',
            'application_method' => 'Application form downloaded from the Ministry of Immigration website (immigration.gov.fj), submitted with supporting documents',
            'interview_required' => 'Not required — a documentary application process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'FJD 93.00',
            'application_centre' => 'Fiji Ministry of Immigration',
            'authority_name' => 'Fiji Ministry of Immigration (immigration.gov.fj)',
            'authority_url' => 'https://www.immigration.gov.fj',
            'eligibility_html' => '<p>Holders of a standard tourist/holiday Visitors Permit may apply for a 2-month extension before their current permit expires. Required documents include a completed application form, certified passport bio-data page copy (6+ months validity), a request letter, proof of sufficient funds, confirmed accommodation or a support letter, a confirmed return ticket, and a certified copy of your arrival stamp.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Who Cannot Apply</h4><p>Business Visitors Permit holders, and students or relatives on a 30-day Visitors Permit, are excluded from this extension route.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Before Your Permit Expires</h4><p>Submit your application and fee (FJD 93.00) to the Ministry of Immigration before your current Visitors Permit runs out.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm Your Eligibility First</h4><p>Business Visitors Permit holders and certain 30-day permit holders cannot use this extension route.</p><p>Our consultants can help you confirm your eligibility and assemble the required documents.</p>',
            'seo_title' => 'Fiji Visa Extension for Indians | Visitors Permit Extension',
            'meta_description' => 'Need more time in Fiji? See the 2-month Visitors Permit Extension process and fee, via VisaAgency.in.',
            'og_title' => 'Fiji Visa Extension for Indians — Visitors Permit Extension',
            'og_description' => 'Need more time in Fiji? See the 2-month Visitors Permit Extension process and fee, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Certified copy of passport bio-data page (6+ months validity)', 'mandatory'],
                ['Supporting Documents', 'Completed application form', 'mandatory'],
                ['Supporting Documents', 'Request letter', 'mandatory'],
                ['Financial Documents', 'Proof of sufficient funds', 'mandatory'],
                ['Supporting Documents', 'Hotel remittance or support letter from host', 'mandatory'],
                ['Travel Documents', 'Confirmed return ticket', 'mandatory'],
                ['Supporting Documents', 'Certified copy of arrival stamp', 'mandatory'],
            ],
            'steps' => [
                ['Download the Application Form', 'From the Ministry of Immigration website.'],
                ['Gather Supporting Documents', 'Including proof of funds, accommodation and a confirmed return ticket.'],
                ['Submit Before Your Permit Expires', 'Along with the FJD 93.00 fee.'],
            ],
            'faqs' => [
                ['How long can I extend my Fiji Visitors Permit?', 'Up to 2 months, one time only — no further extension is possible after that.'],
                ['What does it cost?', 'FJD 93.00.'],
                ['Who cannot apply?', 'Business Visitors Permit holders, and students/relatives on a 30-day Visitors Permit.'],
            ],
            'fees' => [
                ['Visitors Permit Extension', 'FJD 93.00', 1, 'FJD', 'As researched, official Ministry of Immigration fee'],
            ],
            'source' => [
                'authority' => 'Fiji Ministry of Immigration (immigration.gov.fj)',
                'url' => 'https://www.immigration.gov.fj',
                'notes' => 'Phase 3A research: official immigration.gov.fj pages directly confirm the Visitors Permit Extension mechanism, eligibility exclusions, required documents and fee. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'georgia-visa-extension',
            'country_slug' => 'georgia',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'No short-stay visa-extension mechanism exists — Indian nationals already receive 365-day visa-free entry. A separate, distinct Residence Permit process exists for longer-term stays (work, study, etc.), via the Public Service Development Agency',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Georgia does not operate a tourist "visa extension" mechanism for Indian nationals, because Indian passport holders already receive visa-free entry to Georgia for up to 365 days. What exists instead is a wholly separate legal mechanism — a Residence Permit, issued by the Public Service Development Agency (PSDA) of the Ministry of Justice of Georgia — intended for longer-term purposes such as work, study or investment, not for extending an ordinary visit. This distinction is preserved deliberately rather than mislabelling the Residence Permit as an "Extension Visa."</p>',
            'typical_stay' => 'Not applicable to tourist extension (365-day visa-free entry already covers most visits); Residence Permit duration depends on permit type',
            'entry_type' => 'Not applicable — no tourist extension exists; Residence Permit applications go to the PSDA',
            'processing_time_text' => 'Residence Permit: apply at least 40 calendar days before lawful stay expires (certain permit categories are exempt from this timeline)',
            'validity_text' => 'Not applicable for tourist stays (365-day visa-free entry); Residence Permit validity depends on permit category',
            'application_method' => 'Residence Permit applications submitted in printed or electronic form via the PSDA website (sda.gov.ge); can also be applied for electronically from outside Georgia',
            'interview_required' => 'Not required for the standard visa-free entry; not independently confirmed for Residence Permit applications',
            'biometric_required' => 'Not required for the standard visa-free entry; not independently confirmed for Residence Permit applications',
            'government_fee_text' => 'Not applicable to tourist entry (visa-free); Residence Permit fee not reliably confirmed',
            'application_centre' => 'Public Service Development Agency (PSDA), Ministry of Justice of Georgia',
            'authority_name' => 'Public Service Development Agency (PSDA), Ministry of Justice of Georgia',
            'authority_url' => 'https://sda.gov.ge/en/products/migration-residence-permits/',
            'eligibility_html' => '<p>Indian nationals do not need to extend a tourist stay in the ordinary sense, since entry is already visa-free for up to 365 days. Travellers needing to remain longer for work, study, investment or similar purposes must instead apply for a Georgian Residence Permit through the PSDA — a genuinely different legal instrument from a visa extension, with its own 40-day pre-expiry application window (with specific category exemptions) and its own documentary requirements.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Governance Note</h4><p>This Residence Permit process should never be described as an \'Extension Visa\' — it is a separate legal mechanism serving a different purpose.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Check Whether You Actually Need an Extension</h4><p>Indian nationals already get 365 days of visa-free entry to Georgia — confirm whether your visit genuinely requires anything beyond that before assuming an extension process exists.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>For Longer-Term Stays, Apply for a Residence Permit</h4><p>Via the Public Service Development Agency (sda.gov.ge), which handles the genuinely separate process for work, study or similar longer-term purposes.</p><p>Our consultants can help you confirm whether your situation needs a Residence Permit and what it requires.</p>',
            'seo_title' => 'Georgia Visa Extension for Indians | 365-Day Visa-Free Entry Explained',
            'meta_description' => 'Looking to extend your Georgia stay? See why none is needed given 365-day visa-free entry, and the separate Residence Permit process, via VisaAgency.in.',
            'og_title' => 'Georgia Visa Extension for Indians — 365-Day Visa-Free Entry Explained',
            'og_description' => 'Looking to extend your Georgia stay? See why none is needed given 365-day visa-free entry, and the separate Residence Permit process, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Visa-Free Entitlement', 'Indian nationals already receive 365 days of visa-free entry to Georgia.'],
                ['If You Need to Stay Longer-Term', 'Apply for a Residence Permit via the PSDA — a separate legal process, not an extension.'],
            ],
            'faqs' => [
                ['Can I extend my tourist stay in Georgia?', 'There is no ordinary extension mechanism — Indian nationals already receive 365-day visa-free entry, which covers nearly all visit durations.'],
                ['What if I need to stay for work or study?', 'That requires a genuinely separate Residence Permit application through the Public Service Development Agency, not a visa extension.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Public Service Development Agency (PSDA), Ministry of Justice of Georgia',
                'url' => 'https://sda.gov.ge/en/products/migration-residence-permits/',
                'notes' => 'Phase 3A research: official matsne.gov.ge (Georgian legislative herald) and sda.gov.ge pages confirm the Residence Permit mechanism and its 40-day application window; Georgia\'s 365-day Indian visa-free entry already confirmed in prior research. Governance distinction (Residence Permit ≠ Extension Visa) preserved. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'hong-kong-visa-extension',
            'country_slug' => 'hong-kong',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of Stay, via the Hong Kong Immigration Department',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Indian nationals visiting Hong Kong visa-free (for up to 14 days, subject to the mandatory online Pre-Arrival Registration, PAR, required since 23 January 2017) who wish to stay longer can apply for an Extension of Stay with the Immigration Department. Approval is not guaranteed; online applications are accepted only when 5 to 7 days remain on the current permitted stay.</p>',
            'typical_stay' => 'Initial visa-free stay: 14 days. Extension duration not independently confirmed; approval is discretionary',
            'entry_type' => 'Hong Kong Immigration Department, in person or online (for applicants with 5-7 days remaining)',
            'processing_time_text' => 'Online applications restricted to the window when 5 to 7 days of stay remain',
            'validity_text' => 'Not independently confirmed exact; subject to Immigration Department discretion',
            'application_method' => 'Online via immd.gov.hk (if 5-7 days remain) or in person; applicant must be physically present in Hong Kong both to submit and to collect the extension',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Hong Kong Immigration Department (immd.gov.hk)',
            'authority_name' => 'Hong Kong Immigration Department (immd.gov.hk) / Government of the Hong Kong SAR (gov.hk)',
            'authority_url' => 'https://www.immd.gov.hk/eng/online-services/applyextensionstay/visitor.html',
            'eligibility_html' => '<p>Indian nationals enter Hong Kong visa-free for 14 days, subject to the mandatory Pre-Arrival Registration (PAR) in effect since 23 January 2017 — this PAR requirement is specific to Indian nationals among other groups. Travellers wishing to stay beyond 14 days may apply for an Extension of Stay, though the Immigration Department does not guarantee approval.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Timing Matters</h4><p>Online extension applications are only accepted when the applicant has 5 to 7 days remaining on their current permitted stay — applying too early or too late online is not possible.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Complete Pre-Arrival Registration First</h4><p>Indian nationals must complete online PAR before travel to retain the 14-day visa-free privilege.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply for Extension Within the Correct Window</h4><p>Online applications require 5 to 7 days of remaining stay — monitor your dates carefully, as approval is not guaranteed.</p><p>Our consultants can help you track your PAR status and the correct extension application window.</p>',
            'seo_title' => 'Hong Kong Visa Extension for Indians | Extension of Stay (PAR)',
            'meta_description' => 'Need more time in Hong Kong? See the Extension of Stay process and PAR requirement for Indian nationals, via VisaAgency.in.',
            'og_title' => 'Hong Kong Visa Extension for Indians — Extension of Stay (PAR)',
            'og_description' => 'Need more time in Hong Kong? See the Extension of Stay process and PAR requirement for Indian nationals, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your PAR Status', 'Mandatory Pre-Arrival Registration for Indian nationals since January 2017.'],
                ['Monitor Your Remaining Stay', 'Online extension applications require 5-7 days remaining.'],
                ['Apply via immd.gov.hk or In Person', 'Approval is discretionary, not guaranteed.'],
            ],
            'faqs' => [
                ['Do Indian nationals need a visa to enter Hong Kong?', 'No — 14 days visa-free, subject to completing online Pre-Arrival Registration (PAR) beforehand.'],
                ['Is an extension guaranteed?', 'No — the Immigration Department does not guarantee approval of extension applications.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Hong Kong Immigration Department (immd.gov.hk) / Government of the Hong Kong SAR (gov.hk)',
                'url' => 'https://www.immd.gov.hk/eng/online-services/applyextensionstay/visitor.html',
                'notes' => 'Phase 3A research: official immd.gov.hk and gov.hk pages directly confirm the 14-day visa-free entry (with mandatory PAR for Indian nationals since 2017), the Extension of Stay process, and the 5-7-day online application window. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'israel-visa-extension',
            'country_slug' => 'israel',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Visa extension via the Ministry of Interior (Misrad HaPnim)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Travellers wishing to extend their stay in Israel beyond the initial permitted period must submit a visa extension form to the Ministry of Interior (Misrad HaPnim) — this is handled by the immigration authority directly, not through the embassy in the traveller\'s home country.</p>',
            'typical_stay' => 'Not reliably confirmed exact',
            'entry_type' => 'In-country, via Israel\'s Ministry of Interior (Misrad HaPnim)',
            'processing_time_text' => 'Recommended to submit at least 4-8 weeks before the current visa expires; a specific "6-12 months" processing-time claim found in research is unsupported and excluded as unreliable',
            'validity_text' => 'Not reliably confirmed exact',
            'application_method' => 'Visa extension form submitted to the Ministry of Interior (Misrad HaPnim), not the embassy',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Ministry of Interior (Misrad HaPnim), Israel',
            'authority_name' => 'Israel Ministry of Interior (gov.il)',
            'authority_url' => 'https://www.gov.il/en/departments/ministry_of_interior',
            'eligibility_html' => '<p>Stay extensions in Israel are processed by the Ministry of Interior directly, not via the Indian embassy in Israel or the Israeli mission in India. Applicants should submit their extension form well before their current visa expires — a recommended 4-8 week lead time was found in research, though this is not independently verified against an official gov.il page.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Unverified Claim Excluded</h4><p>A claim that processing can take "6-12 months" was found in research but could not be verified and is not reliable — do not assume this figure; confirm current timelines directly with the Ministry of Interior.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply to the Ministry of Interior, Not the Embassy</h4><p>Extensions are handled by Misrad HaPnim directly within Israel.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply Well Before Expiry</h4><p>A lead time of several weeks is advisable — confirm the current recommended timeline directly, as some processing-time figures found in research could not be verified.</p><p>Our consultants can help you confirm the current Ministry of Interior process before you apply.</p>',
            'seo_title' => 'Israel Visa Extension for Indians | Ministry of Interior Process',
            'meta_description' => 'Need more time in Israel? See the Ministry of Interior (Misrad HaPnim) extension process for Indian travellers, via VisaAgency.in.',
            'og_title' => 'Israel Visa Extension for Indians — Ministry of Interior Process',
            'og_description' => 'Need more time in Israel? See the Ministry of Interior (Misrad HaPnim) extension process for Indian travellers, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Prepare Your Extension Form', 'For submission to the Ministry of Interior, not the embassy.'],
                ['Apply Well Before Your Visa Expires', 'Confirm the current recommended lead time directly with Misrad HaPnim.'],
            ],
            'faqs' => [
                ['Where do I apply for an Israel visa extension?', 'The Ministry of Interior (Misrad HaPnim) directly within Israel, not through an embassy.'],
                ['How long does processing take?', 'Not reliably confirmed — a "6-12 months" figure found in research is unverified and excluded; confirm current timelines directly with the Ministry of Interior.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Israel Ministry of Interior (gov.il)',
                'url' => 'https://www.gov.il/en/departments/ministry_of_interior',
                'notes' => 'Phase 3A research: gov.il referenced as the official resource confirming Ministry of Interior routing for extensions, not the embassy. A "6-12 months processing" claim found in secondary sources is excluded as unsupported/unverified, per the research audit\'s explicit governance instruction. Confidence: Medium.',
            ],
        ],
        [
            'page_slug' => 'jordan-visa-extension',
            'country_slug' => 'jordan',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Automatic 90-day temporary residency stamp at entry (effective policy since early 2026), replacing the former 30-day-plus-police-extension system for non-work visa holders',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Since early 2026, Jordan\'s immigration authorities stamp a 90-day temporary residency directly onto the passport of non-work visa holders (including Visa-on-Arrival and e-Visa holders) at the point of entry — air, land or sea — eliminating the earlier need to visit a police station mid-trip for a shorter-term extension. Travellers wishing to stay beyond 90 days must still visit a police station or use the Ministry of Interior\'s online portal.</p>',
            'typical_stay' => '90 days, granted automatically at entry for non-work visa holders; further stay beyond 90 days requires a police-station/MOI-portal application',
            'entry_type' => 'Automatic at any official Jordanian border crossing (non-work entries); in-country police station or MOI portal for stays beyond 90 days',
            'processing_time_text' => 'Immediate at entry for the automatic 90-day stamp; not reliably confirmed for extensions beyond 90 days',
            'validity_text' => '90 days automatic; extension beyond that via police station or the Ministry of Interior\'s online portal',
            'application_method' => 'No application needed for the automatic 90-day stamp; beyond 90 days, apply at a police station or via the Ministry of Interior portal (eservices.moi.gov.jo)',
            'interview_required' => 'Not required for the automatic 90-day entry stamp',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'No additional fees or requirements reported for the automatic 90-day stamp beyond standard visa eligibility',
            'application_centre' => 'Automatic at border entry; police station or eservices.moi.gov.jo for stays beyond 90 days',
            'authority_name' => 'Jordan Ministry of Interior (moi.gov.jo)',
            'authority_url' => 'https://moi.gov.jo',
            'eligibility_html' => '<p>Non-work visa holders entering Jordan — including Visa-on-Arrival and e-Visa holders — automatically receive a 90-day temporary residency stamp at the border, with no additional fees or paperwork beyond standard visa eligibility. This replaced the previous one-month residency stamp system. Travellers entering on specific work visas are excluded from this automatic allowance and follow separate labour regulations.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Beyond 90 Days</h4><p>Further extension requires visiting a police station or using the Ministry of Interior\'s online portal for further extensions or annual residency.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>No Action Needed for Your First 90 Days</h4><p>The residency stamp is applied automatically at the border for non-work visa entries — no separate extension application is needed for the initial 90-day period.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Plan Ahead If You Need Longer</h4><p>Visit a police station or the MOI\'s online portal before your 90 days expire if you need to stay longer.</p><p>Our consultants can help you confirm current requirements for extensions beyond the automatic 90-day period.</p>',
            'seo_title' => 'Jordan Visa Extension for Indians | Automatic 90-Day Entry Stamp',
            'meta_description' => 'Travelling to Jordan? See the automatic 90-day residency stamp at entry and the process for staying longer, via VisaAgency.in.',
            'og_title' => 'Jordan Visa Extension for Indians — Automatic 90-Day Entry Stamp',
            'og_description' => 'Travelling to Jordan? See the automatic 90-day residency stamp at entry and the process for staying longer, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Enter Jordan Normally', 'The 90-day residency stamp is applied automatically at the border for non-work visa holders.'],
                ['If You Need More Than 90 Days', 'Visit a police station or apply via the Ministry of Interior\'s online portal before the 90 days expire.'],
            ],
            'faqs' => [
                ['Do I need to apply for my initial stay in Jordan?', 'No — a 90-day temporary residency is stamped automatically at entry for non-work visa holders, with no extra fees or paperwork.'],
                ['What if I want to stay longer than 90 days?', 'Visit a police station or use the Ministry of Interior\'s online portal (eservices.moi.gov.jo) for further extensions.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Jordan Ministry of Interior (moi.gov.jo)',
                'url' => 'https://moi.gov.jo',
                'notes' => 'Phase 3A research: the automatic 90-day entry-stamp policy (effective early 2026) was confirmed by two independent sources describing the same specific facts consistently, alongside the official Jordan MOI portal for further extensions. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'mexico-visa-extension',
            'country_slug' => 'mexico',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Extension of the FMM (Forma Migratoria Múltiple) tourist card, via the Instituto Nacional de Migración (INM)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Travellers wishing to stay longer than the 30-90 days granted on arrival (recorded on the FMM tourist card) must request an extension from the migratory authorities (INM) before the FMM\'s granted period expires. This is handled in person at any INM office.</p>',
            'typical_stay' => 'Extends the original FMM-granted period (30-90 days); exact additional duration not reliably confirmed',
            'entry_type' => 'In-country, at any Instituto Nacional de Migración (INM) office',
            'processing_time_text' => 'Described as a quick, same-visit procedure ("takes only a few minutes") per research, though this is not independently confirmed against an official INM source',
            'validity_text' => 'Extends the original FMM tourist-card period',
            'application_method' => 'In person at any INM office, presenting the valid passport and the FMM tourist card',
            'interview_required' => 'Not described as requiring a formal interview — a documentary, in-person counter process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'A fee applies; exact current amount not reliably confirmed',
            'application_centre' => 'Instituto Nacional de Migración (INM), any office',
            'authority_name' => 'Instituto Nacional de Migración (INM), Mexico / Mexican Ministry of Foreign Affairs consular network (embamex.sre.gob.mx)',
            'authority_url' => 'https://embamex.sre.gob.mx',
            'eligibility_html' => '<p>Travellers must bring their valid passport and the FMM tourist card issued on arrival, and demonstrate they can finance their continued stay. The extension request must be made before the FMM\'s originally granted period (30-90 days) expires.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Keep Your FMM Tourist Card</h4><p>This is the document you received on arrival and must present, along with your passport, to request an extension.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply at Any INM Office Before Your FMM Period Expires</h4><p>Show proof you can finance your continued stay.</p><p>Our consultants can help you confirm the current fee and required documents at your nearest INM office.</p>',
            'seo_title' => 'Mexico Visa Extension for Indians | FMM Tourist Card Extension',
            'meta_description' => 'Need more time in Mexico? See the INM process for extending your FMM tourist card, via VisaAgency.in.',
            'og_title' => 'Mexico Visa Extension for Indians — FMM Tourist Card Extension',
            'og_description' => 'Need more time in Mexico? See the INM process for extending your FMM tourist card, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport', 'mandatory'],
                ['Basic Documents', 'FMM tourist card issued on arrival', 'mandatory'],
                ['Financial Documents', 'Proof of ability to finance continued stay', 'mandatory'],
            ],
            'steps' => [
                ['Keep Your FMM Tourist Card Safe', 'Issued to you on arrival in Mexico.'],
                ['Visit Any INM Office', 'Before your FMM-granted period expires.'],
                ['Present Your Documents and Pay the Fee', 'To receive your extension.'],
            ],
            'faqs' => [
                ['Where do I extend my stay in Mexico?', 'At any Instituto Nacional de Migración (INM) office, in person.'],
                ['What document do I need?', 'Your valid passport and the FMM tourist card issued to you on arrival.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Instituto Nacional de Migración (INM), Mexico / Mexican Ministry of Foreign Affairs consular network (embamex.sre.gob.mx)',
                'url' => 'https://embamex.sre.gob.mx',
                'notes' => 'Phase 3A research: the INM/FMM mechanism and terminology is specific and correct, corroborated by the Mexican consular network and the Indian Embassy in Mexico\'s official advisory (indiainmexico.gov.in). Exact fee not located. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'myanmar-visa-extension',
            'country_slug' => 'myanmar',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Tourist eVisa: NO extension mechanism exists. Business eVisa: a Stay Extension/Re-entry Visa exists, via estay.moip.gov.mm, but only through company sponsorship',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Myanmar\'s Ministry of Immigration and Population draws a clear, official distinction between its two eVisa categories: the Tourist eVisa (28-day stay) has no extension mechanism at all, while the Business eVisa has a genuine Stay Extension/Re-entry Visa pathway — but only for foreigners working for, or engaged in business with, a company duly incorporated and registered with Myanmar\'s Directorate of Investment Company Administration (DICA).</p>',
            'typical_stay' => 'Tourist eVisa: 28 days, not extendable. Business eVisa: up to 70 days initially; extension available only through company sponsorship',
            'entry_type' => 'Not applicable for Tourist eVisa (no extension exists); Business eVisa extension via estay.moip.gov.mm',
            'processing_time_text' => 'Business eVisa extension: up to 5 working days from acknowledgement of receipt, excluding weekends and Myanmar gazetted holidays',
            'validity_text' => 'Tourist eVisa: not extendable. Business eVisa extension: governed by the company-sponsored Stay Extension/Re-entry Visa terms',
            'application_method' => 'Business eVisa extension submitted by an existing, DICA-registered company (via Myanmar Companies Online, MyCO) and its director, at estay.moip.gov.mm',
            'interview_required' => 'Not required for the company-sponsored online extension process',
            'biometric_required' => 'Not required — an online, company-sponsored application process',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'estay.moip.gov.mm (Business eVisa route only)',
            'authority_name' => 'Ministry of Immigration and Population, Myanmar (evisa.moip.gov.mm / estay.moip.gov.mm)',
            'authority_url' => 'https://estay.moip.gov.mm/home/terms',
            'eligibility_html' => '<p>If you hold a Tourist eVisa, no extension mechanism exists at all — the 28-day stay is a firm limit. If you hold a Business eVisa, a Stay Extension/Re-entry Visa application can be submitted, but only by a company that is duly incorporated, registered with DICA, and listed in the Myanmar Companies Online (MyCO) directory — the application itself must be filed by the company\'s director, not the traveller personally.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Assume the Business Route Applies to Tourist Entries</h4><p>This is a genuinely different mechanism tied specifically to company sponsorship of a Business eVisa holder, not a general extension available to all travellers.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Confirm Your eVisa Category First</h4><p>Tourist eVisa holders cannot extend their stay under any circumstance — plan your trip within the 28-day limit.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Business eVisa Holders Need Company Sponsorship</h4><p>Only a DICA-registered, MyCO-listed company (through its director) can apply for your Stay Extension/Re-entry Visa.</p><p>Our consultants can help you confirm which eVisa category you hold and whether company sponsorship is available to you.</p>',
            'seo_title' => 'Myanmar Visa Extension for Indians | Tourist vs Business eVisa Rules',
            'meta_description' => 'Hoping to extend your Myanmar stay? See why the Tourist eVisa cannot be extended and how the Business eVisa route works, via VisaAgency.in.',
            'og_title' => 'Myanmar Visa Extension for Indians — Tourist vs Business eVisa Rules',
            'og_description' => 'Hoping to extend your Myanmar stay? See why the Tourist eVisa cannot be extended and how the Business eVisa route works, via VisaAgency.in.',
            'documents' => [
                ['Supporting Documents', 'Company registration with DICA and MyCO listing (Business eVisa route only)', 'conditional'],
                ['Supporting Documents', 'Application filed by the sponsoring company\'s director (Business eVisa route only)', 'conditional'],
            ],
            'steps' => [
                ['Confirm Your eVisa Category', 'Tourist eVisa holders have no extension path at all.'],
                ['Business eVisa Holders: Arrange Company Sponsorship', 'Through a DICA-registered, MyCO-listed company.'],
                ['Company Director Applies via estay.moip.gov.mm', '5 working days processing, excluding weekends/holidays.'],
            ],
            'faqs' => [
                ['Can I extend my Myanmar Tourist eVisa?', 'No — the Tourist eVisa (28-day stay) has no extension mechanism at all.'],
                ['Can I extend my Business eVisa?', 'Yes, but only if a DICA-registered, MyCO-listed company sponsors your Stay Extension/Re-entry Visa application.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Immigration and Population, Myanmar (evisa.moip.gov.mm / estay.moip.gov.mm)',
                'url' => 'https://estay.moip.gov.mm/home/terms',
                'notes' => 'Phase 3A research: official moip.gov.mm domains directly confirm the Tourist/Business case-split and the company-sponsorship requirement for Business eVisa extensions. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'philippines-visa-extension',
            'country_slug' => 'philippines',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => '9(A) Tourist Visa extension, including the Long-Stay Visitor Visa Extension (LSVVE) program, via the Bureau of Immigration',
            'visa_subclass_code' => '9(A)',
            'intro_html' => '<p>Holders of the Philippines\' 9(A) tourist visa can extend their stay in increments of 1, 2, or 6 months, up to a maximum of 24 months for visa-required nationals. The Bureau of Immigration\'s Long-Stay Visitor Visa Extension (LSVVE) program allows a single 6-month extension transaction, currently implemented only at the BI Main Office in Intramuros, Manila.</p>',
            'typical_stay' => 'Extensions in 1, 2, or 6-month increments; maximum 24 months for visa-required nationals (36 months for non-visa-required nationals under LSVVE)',
            'entry_type' => 'Bureau of Immigration (BI) Main Office, Intramuros, Manila',
            'processing_time_text' => 'Apply at least 7 days before your current visa or extension expires',
            'validity_text' => 'Up to 24 months total for visa-required nationals under the LSVVE program',
            'application_method' => 'In person/via the Bureau of Immigration; LSVVE currently limited to the BI Main Office, Intramuros, Manila, until further notice',
            'interview_required' => 'Not described as requiring a formal interview in the LSVVE process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'LSVVE: PHP 13,900.00 for visa-required nationals (PHP 11,500 for non-visa-required nationals)',
            'application_centre' => 'Bureau of Immigration Main Office, Intramuros, Manila',
            'authority_name' => 'Philippine Bureau of Immigration (BI) / Department of Foreign Affairs (dfa.gov.ph)',
            'authority_url' => 'https://www.lawyer-philippines.com/articles/visa-extension-for-indian-passport-holders-in-the-philippines',
            'eligibility_html' => '<p>9(A) tourist visa holders can extend in increments of 1, 2 or 6 months. The LSVVE program specifically offers a 6-month extension under a single transaction, with a maximum cumulative stay of 24 months for visa-required nationals (India is visa-required for the Philippines beyond the initial visa-free allowance). Apply at least 7 days before your current visa/extension expires.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>LSVVE Is Currently Manila-Only</h4><p>The Long-Stay Visitor Visa Extension program is, for now, implemented only at the BI Main Office in Intramuros, Manila.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Budget for the Fee</h4><p>PHP 13,900.00 applies for visa-required nationals such as Indian passport holders.</p><p>Our consultants can help you plan your extension timeline and the Manila application process.</p>',
            'seo_title' => 'Philippines Visa Extension for Indians | 9(A) Tourist Visa & LSVVE',
            'meta_description' => 'Need more time in the Philippines? See the 9(A) tourist visa extension and LSVVE program fees for Indian travellers, via VisaAgency.in.',
            'og_title' => 'Philippines Visa Extension for Indians — 9(A) Tourist Visa & LSVVE',
            'og_description' => 'Need more time in the Philippines? See the 9(A) tourist visa extension and LSVVE program fees for Indian travellers, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Apply at Least 7 Days Before Expiry', 'Through the Bureau of Immigration.'],
                ['Consider the LSVVE Program', 'For a single 6-month extension transaction, currently Manila-only.'],
                ['Pay the Applicable Fee', 'PHP 13,900.00 for visa-required nationals.'],
            ],
            'faqs' => [
                ['How much does the LSVVE cost?', 'PHP 13,900.00 for visa-required nationals (PHP 11,500 for non-visa-required nationals).'],
                ['What is the maximum stay under LSVVE?', '24 months for visa-required nationals, 36 months for non-visa-required nationals.'],
            ],
            'fees' => [
                ['Long-Stay Visitor Visa Extension (LSVVE)', 'PHP 13,900.00', 1, 'PHP', 'For visa-required nationals; as researched from official BI program details'],
            ],
            'source' => [
                'authority' => 'Philippine Bureau of Immigration (BI) / Department of Foreign Affairs (dfa.gov.ph)',
                'url' => 'https://www.lawyer-philippines.com/articles/visa-extension-for-indian-passport-holders-in-the-philippines',
                'notes' => 'Phase 3A research: dfa.gov.ph consular pages and specialist legal sources confirm the 9(A) extension increments and the LSVVE program\'s fees, caps and Manila-only implementation. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'russia-visa-extension',
            'country_slug' => 'russia',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Extension of e-visa validity/permitted stay, limited to exceptional circumstances, via the Ministry of Internal Affairs (MVD)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Russia only extends the validity of an e-visa or its permitted stay duration in exceptional circumstances — such as the impossibility of leaving Russian territory due to emergency medical treatment, force majeure, or natural disasters. This is handled by the Ministry of Internal Affairs or its regional offices, based on the traveller\'s migrant-registration location; where no migrant registration exists, the extension is processed at the actual stay location via issuance of a regular (non-electronic) visa.</p>',
            'typical_stay' => 'Exceptional-circumstances extension only, not a routine process; standard e-visa stay is 30 days (as of August 2025, up from 16 days, with 120-day validity)',
            'entry_type' => 'In-country, via the Ministry of Internal Affairs or its regional offices, based on migrant registration',
            'processing_time_text' => 'Not reliably confirmed exact',
            'validity_text' => 'Governed by the exceptional-circumstances extension process; not a standing, routine extension right',
            'application_method' => 'Via the Ministry of Internal Affairs (MVD) or its regional office covering the traveller\'s migrant registration location',
            'interview_required' => 'Not described as requiring a formal interview',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Ministry of Internal Affairs (MVD) or regional office',
            'authority_name' => 'Ministry of Internal Affairs of the Russian Federation (MVD)',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is not a routine process — it applies only to exceptional circumstances such as an emergency medical situation, force majeure, or a natural disaster preventing departure. Where the traveller has a migrant registration, the extension is handled by the MVD office for that registration location; without one, it is processed at the actual stay location via issuance of a regular visa instead of extending the e-visa.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>This Is Not a Routine Extension</h4><p>Only genuine exceptional circumstances (medical emergency, force majeure, natural disaster) qualify — plan your trip within the standard e-visa stay period (30 days as of August 2025).</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply Through the MVD</h4><p>Based on your migrant registration location, or at your actual stay location if unregistered.</p><p>Our consultants can help you understand whether your situation genuinely qualifies as exceptional.</p>',
            'seo_title' => 'Russia Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Russia e-visa? See why this is limited to genuine emergencies, via the Ministry of Internal Affairs, via VisaAgency.in.',
            'og_title' => 'Russia Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Russia e-visa? See why this is limited to genuine emergencies, via the Ministry of Internal Affairs, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Qualify', 'Emergency medical treatment, force majeure, or natural disaster only.'],
                ['Apply Through the MVD', 'Based on your migrant registration location, or your actual stay location if unregistered.'],
            ],
            'faqs' => [
                ['Can I extend my Russia e-visa for a routine reason?', 'No — extension is limited to exceptional circumstances such as a medical emergency, force majeure, or natural disaster.'],
                ['What is the standard e-visa stay?', 'As of August 2025, 30 days (up from 16), with 120-day e-visa validity.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Internal Affairs of the Russian Federation (MVD)',
                'url' => null,
                'notes' => 'Phase 3A research: the exceptional-circumstances-only extension mechanism and MVD/migrant-registration routing is specific and internally consistent across multiple sources, matching known Russian bureaucratic patterns, though no direct mvd.rf page was located. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'seychelles-visa-extension',
            'country_slug' => 'seychelles',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Extension of the Visitor\'s Permit, via the Seychelles Department of Immigration and Civil Status',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Seychelles\' initial free 30-day Visitor\'s Permit can be extended through the Department of Immigration and Civil Status, in increments of up to 3 months at a time, to a maximum cumulative total of 12 months — provided the applicant continues to qualify as a bona fide visitor (not a prohibited immigrant, not already holding a permit allowing residence in Seychelles, sufficient funds, confirmed accommodation, and a valid return ticket).</p>',
            'typical_stay' => 'Up to 3 months per extension, to a maximum cumulative total of 12 months',
            'entry_type' => 'Department of Immigration and Civil Status, Seychelles',
            'processing_time_text' => 'Not reliably confirmed exact; apply before the current permit expires',
            'validity_text' => 'Up to 3 months per extension, maximum 12 months cumulative',
            'application_method' => 'Apply in person at the Department of Immigration and Civil Status, with supporting documents',
            'interview_required' => 'Not described as requiring a formal interview — a documentary application process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'SCR 5,000 (approximately ₹30,000) per extension of up to 30 additional days',
            'application_centre' => 'Department of Immigration and Civil Status, Seychelles',
            'authority_name' => 'Department of Immigration and Civil Status, Seychelles',
            'authority_url' => null,
            'eligibility_html' => '<p>Applicants must not be a prohibited immigrant, must not already hold a permit allowing them to reside in Seychelles, must have sufficient funds for the extended stay, confirmed extended accommodation, and a valid return ticket. Extensions are granted in increments of up to 3 months at a time, to a lifetime-per-visit cumulative maximum of 12 months.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Before Your 30-Day Permit Expires</h4><p>Visit the Department of Immigration and Civil Status with proof of accommodation, funds, and a return ticket.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Budget for the Extension Fee</h4><p>As researched, approximately SCR 5,000 per 30-day extension period.</p><p>Our consultants can help you plan an extension within the 12-month cumulative cap.</p>',
            'seo_title' => 'Seychelles Visa Extension for Indians | Visitor\'s Permit Extension',
            'meta_description' => 'Need more time in Seychelles? See the Visitor\'s Permit extension process, fees and 12-month cap, via VisaAgency.in.',
            'og_title' => 'Seychelles Visa Extension for Indians — Visitor\'s Permit Extension',
            'og_description' => 'Need more time in Seychelles? See the Visitor\'s Permit extension process, fees and 12-month cap, via VisaAgency.in.',
            'documents' => [
                ['Supporting Documents', 'Proof of extended accommodation', 'mandatory'],
                ['Financial Documents', 'Proof of sufficient funds', 'mandatory'],
                ['Travel Documents', 'Valid return ticket', 'mandatory'],
            ],
            'steps' => [
                ['Apply Before Your Current Permit Expires', 'At the Department of Immigration and Civil Status.'],
                ['Provide Supporting Documents', 'Accommodation, funds, and return-ticket proof.'],
                ['Pay the Extension Fee', 'As researched, approximately SCR 5,000.'],
            ],
            'faqs' => [
                ['How long can I extend my stay in Seychelles?', 'Up to 3 months per extension, to a maximum cumulative total of 12 months.'],
                ['What is the fee?', 'As researched, approximately SCR 5,000 per extension period.'],
            ],
            'fees' => [
                ['Visitor\'s Permit Extension (per ~30 days)', 'SCR 5,000', 1, 'SCR', 'As researched; multiple consistent secondary sources, no direct .gov.sc fee page located'],
            ],
            'source' => [
                'authority' => 'Department of Immigration and Civil Status, Seychelles',
                'url' => null,
                'notes' => 'Phase 3A research: multiple consistent secondary sources describe specific, internally-coherent figures (SCR 5,000, 3-month increments, 12-month cap, eligibility conditions). No direct immigration.gov.sc/egov.sc page was located despite attempts. Confidence: Medium.',
            ],
        ],
        [
            'page_slug' => 'taiwan-visa-extension',
            'country_slug' => 'taiwan',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Extension of stay, via the National Immigration Agency (NIA)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Visitor visa holders in Taiwan may apply for an extension of stay in person at any National Immigration Agency (NIA) service centre, within 15 days before their permitted stay expires. The official application-instructions document is published directly by Taiwan\'s representative-office network (immigration.gov.tw).</p>',
            'typical_stay' => 'Not reliably confirmed exact additional duration',
            'entry_type' => 'In person, at any NIA service centre',
            'processing_time_text' => 'Half a day from receipt of application, if no supplementary documents are required and there are no special circumstances',
            'validity_text' => 'Not reliably confirmed exact',
            'application_method' => 'In person at any NIA service centre, with the application form, entry permit, and fee',
            'interview_required' => 'Not described as requiring a formal interview — an in-person documentary process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'NTD 300',
            'application_centre' => 'National Immigration Agency (NIA) service centre',
            'authority_name' => 'National Immigration Agency, Taiwan (immigration.gov.tw)',
            'authority_url' => 'https://www.immigration.gov.tw/media/103227/application-instructions-for-visitor-visa-extension.pdf',
            'eligibility_html' => '<p>Visitor visa holders should apply within 15 days before their current permitted stay expires, bringing the application form, their entry permit, and the NTD 300 fee. Required supporting documents vary by the original purpose of stay.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Overstay Risk</h4><p>Overstaying results in a fine ranging from NT$10,000 to NT$50,000 and a re-entry ban of at least one year, up to seven years.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Within the 15-Day Window</h4><p>Before your current permitted stay expires, at any NIA service centre.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Avoid Overstaying</h4><p>Fines range from NT$10,000 to NT$50,000, with a re-entry ban of 1 to 7 years.</p><p>Our consultants can help you confirm which supporting documents apply to your original visa purpose.</p>',
            'seo_title' => 'Taiwan Visa Extension for Indians | NIA Extension of Stay',
            'meta_description' => 'Need more time in Taiwan? See the NIA extension-of-stay process, fee and overstay penalties, via VisaAgency.in.',
            'og_title' => 'Taiwan Visa Extension for Indians — NIA Extension of Stay',
            'og_description' => 'Need more time in Taiwan? See the NIA extension-of-stay process, fee and overstay penalties, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Application form', 'mandatory'],
                ['Basic Documents', 'Entry permit', 'mandatory'],
            ],
            'steps' => [
                ['Apply Within 15 Days of Expiry', 'At any National Immigration Agency service centre.'],
                ['Pay the NTD 300 Fee', 'Processing takes half a day if complete and straightforward.'],
            ],
            'faqs' => [
                ['How much does a Taiwan visa extension cost?', 'NTD 300.'],
                ['What happens if I overstay?', 'A fine of NT$10,000 to NT$50,000 and a re-entry ban of 1 to 7 years.'],
            ],
            'fees' => [
                ['Visitor Visa Extension of Stay', 'NTD 300', 1, 'TWD', 'As researched, official NIA fee'],
            ],
            'source' => [
                'authority' => 'National Immigration Agency, Taiwan (immigration.gov.tw)',
                'url' => 'https://www.immigration.gov.tw/media/103227/application-instructions-for-visitor-visa-extension.pdf',
                'notes' => 'Phase 3A research: official immigration.gov.tw PDF directly confirms the NIA extension process, fee and overstay penalties. Confidence: High.',
            ],
        ],
    ];
}
