<?php
/**
 * Phase 3A -- Medical Visa gap-closure research for 13 of the 21 Tier-B cells
 * that remained generic after Phase 3, following a controlled, small-batch
 * WebSearch re-research pass (see scratchpad/phase3a/RESEARCH_AUDIT.md). 8
 * cells (bangladesh, fiji, mexico, morocco, myanmar, russia, seychelles,
 * tanzania) still had zero genuine country-specific evidence after this pass
 * and remain generic -- not forced to researched status merely to close the
 * gap. Preserves the Hong Kong (no dedicated category, honest negative
 * outcome), Norway (residence permit vs. visa for >90 days) and Hungary
 * (short-stay visa vs. separate residence permit) governance distinctions
 * established during research.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_phase3a_medical(): array
{
    return [
        [
            'page_slug' => 'argentina-medical-visa',
            'country_slug' => 'argentina',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Medical treatment entry under the "persons entering for medical treatment" transitory-resident subcategory, per Argentine immigration law',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Argentine immigration law explicitly recognises "persons entering for medical treatment" as one of its transitory (short-term) visa subcategories, alongside tourists and other short-stay entrants. Under Executive Decree 366/2025, applicants must submit a sworn declaration of their purpose of entry and confirm they hold health insurance to cover their medical needs during the stay.</p>',
            'typical_stay' => 'Not reliably confirmed exact; governed by the transitory-resident framework',
            'entry_type' => 'Embassy of the Argentine Republic in New Delhi (for residents outside Maharashtra) or the Consulate General of the Argentine Republic in Mumbai (for Maharashtra residents)',
            'processing_time_text' => 'Not reliably confirmed exact',
            'validity_text' => 'Governed by the transitory (short-term) resident framework',
            'application_method' => 'In advance, via the Argentine Embassy (New Delhi) or Consulate General (Mumbai), depending on place of residence in India',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Embassy of Argentina, New Delhi, or Consulate General of Argentina, Mumbai',
            'authority_name' => 'Ministry of Foreign Affairs, International Trade and Worship of Argentina (Cancillería)',
            'authority_url' => 'https://cgmum.cancilleria.gob.ar',
            'eligibility_html' => '<p>Indian nationals travelling to Argentina specifically for medical treatment can apply under the "persons entering for medical treatment" transitory-resident subcategory, explicitly recognised in Argentine immigration law alongside tourism and other short-term purposes.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Health Insurance Declaration</h4><p>Per Executive Decree 366/2025, applicants must submit a sworn statement confirming their purpose of entry and that they hold health insurance to address their medical needs during the stay.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Through the Correct Mission for Your State</h4><p>If you reside in Maharashtra, apply through the Consulate General in Mumbai; all other Indian residents apply through the Embassy in New Delhi.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm Current Fee and Processing Details</h4><p>These were not reliably established in research — confirm directly with the relevant Argentine mission before applying.</p><p>Our consultants can help you confirm which mission handles your application and the current documentary requirements.</p>',
            'seo_title' => 'Argentina Medical Visa for Indians | Medical Treatment Entry',
            'meta_description' => 'Travelling to Argentina for medical treatment? See the transitory-resident medical treatment category and India application venues, via VisaAgency.in.',
            'og_title' => 'Argentina Medical Visa for Indians — Medical Treatment Entry',
            'og_description' => 'Travelling to Argentina for medical treatment? See the transitory-resident medical treatment category and India application venues, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport', 'mandatory'],
                ['Supporting Documents', 'Sworn declaration of purpose of entry', 'mandatory'],
                ['Supporting Documents', 'Proof of health insurance covering medical needs', 'mandatory'],
            ],
            'steps' => [
                ['Identify Your Application Venue', 'Embassy in New Delhi, or Consulate General in Mumbai if you reside in Maharashtra.'],
                ['Prepare Your Sworn Declaration', 'Confirming medical-treatment purpose and health insurance coverage.'],
                ['Apply in Advance of Travel', 'Through the appropriate Argentine mission.'],
            ],
            'faqs' => [
                ['Does Argentina have a medical treatment visa category?', 'Yes — "persons entering for medical treatment" is an explicit transitory-resident subcategory under Argentine immigration law.'],
                ['Where do Indian applicants apply?', 'The Embassy in New Delhi, or the Consulate General in Mumbai for Maharashtra residents.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Foreign Affairs, International Trade and Worship of Argentina (Cancillería)',
                'url' => 'https://cgmum.cancilleria.gob.ar',
                'notes' => 'Phase 3A research: official cancilleria.gob.ar pages confirm medical treatment as an explicit transitory-visa subcategory (per current Argentine immigration law and Executive Decree 366/2025) and the India-specific application venues. Fee and processing-time detail were not located. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'brazil-medical-visa',
            'country_slug' => 'brazil',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'VITEM II (Temporary Visa II, health treatment) for stays over 90 days; a separate "Health Treatment" visitor-visa (VIVIS) subtype exists for shorter stays',
            'visa_subclass_code' => 'VITEM II',
            'intro_html' => '<p>Brazil recognises medical/health treatment as an explicit visa purpose through two distinct products: VITEM II, a temporary visa for health treatment lasting longer than 90 days (up to 24 months initial stay, open to all nationalities), and a separate "Health Treatment" subtype under the short-stay VIVIS visitor-visa category for shorter treatment periods. The two are genuinely different legal mechanisms and should not be conflated.</p>',
            'typical_stay' => 'VITEM II: initial stay up to 24 months. VIVIS Health Treatment: short-stay visitor terms (exact cap not independently confirmed)',
            'entry_type' => 'Brazilian Consulate in India (New Delhi/Mumbai) or via the relevant Brazilian MFA (gov.br/mre) consular portal',
            'processing_time_text' => 'Approximately 30 days typical, per Brazilian MFA consular guidance (confirmed for the Lisbon mission; India-specific timeline not independently confirmed)',
            'validity_text' => 'VITEM II: up to 24 months initial. VIVIS Health Treatment: short-stay terms',
            'application_method' => 'Consular Authority application; documents include valid travel document, proof of sufficient means for treatment and maintenance, proof of transportation, and (for VITEM II) a criminal background certificate',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact for India; consult the Brazilian consular fee annex',
            'application_centre' => 'Brazilian Consulate serving India',
            'authority_name' => 'Ministry of Foreign Affairs of Brazil (gov.br/mre)',
            'authority_url' => 'https://www.gov.br/mre/pt-br/consulado-lisboa/servicos-consulares/vistos-destinados-a-estrangeiros-para-entrada-no-brasil/visto-temporario-ii-tratamento-de-saude',
            'eligibility_html' => '<p>Applicants must prove sufficient means to cover treatment and maintenance costs during their stay. VITEM II is open to all nationalities and does not require an underlying treaty relationship.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Two Distinct Products — Do Not Conflate</h4><p>VITEM II (temporary visa, &gt;90 days, up to 24-month initial stay) is a genuinely different legal product from the VIVIS "Health Treatment" short-stay visitor-visa subtype. Confirm with the consulate which applies to your treatment duration.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Confirm Which Product Fits Your Treatment Duration</h4><p>Short treatment (under 90 days) likely falls under VIVIS Health Treatment; longer treatment uses VITEM II.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply Through the Brazilian Consulate</h4><p>Serving India, with documents proving financial means and (for VITEM II) a police clearance certificate.</p><p>Our consultants can help you confirm the correct visa product and current documentary checklist.</p>',
            'seo_title' => 'Brazil Medical Visa for Indians | VITEM II Health Treatment',
            'meta_description' => 'Planning medical treatment in Brazil? See the VITEM II temporary visa and short-stay VIVIS Health Treatment options, via VisaAgency.in.',
            'og_title' => 'Brazil Medical Visa for Indians — VITEM II Health Treatment',
            'og_description' => 'Planning medical treatment in Brazil? See the VITEM II temporary visa and short-stay VIVIS Health Treatment options, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport/travel document', 'mandatory'],
                ['Financial Documents', 'Proof of sufficient means to cover treatment and maintenance', 'mandatory'],
                ['Travel Documents', 'Proof of means of entry/exit transportation', 'mandatory'],
                ['Supporting Documents', 'Criminal background certificate (VITEM II only)', 'conditional'],
                ['Supporting Documents', 'International immunization certificate, if required by ANVISA', 'conditional'],
            ],
            'steps' => [
                ['Confirm Your Treatment Duration', 'To determine whether VITEM II or VIVIS Health Treatment applies.'],
                ['Apply at the Brazilian Consulate', 'Serving your place of residence in India.'],
                ['Submit Financial and Supporting Documents', 'Proving ability to cover treatment and maintenance costs.'],
            ],
            'faqs' => [
                ['What is VITEM II?', 'A Brazilian temporary visa for health treatment lasting over 90 days, with an initial stay of up to 24 months, open to all nationalities.'],
                ['Is there a shorter-stay medical option?', 'Yes — a "Health Treatment" subtype exists under the VIVIS short-stay visitor-visa category.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Foreign Affairs of Brazil (gov.br/mre)',
                'url' => 'https://www.gov.br/mre/pt-br/consulado-lisboa/servicos-consulares/vistos-destinados-a-estrangeiros-para-entrada-no-brasil/visto-temporario-ii-tratamento-de-saude',
                'notes' => 'Phase 3A research: official gov.br/mre consular pages (consulado-lisboa, consulado-londres) directly confirm both VITEM II and the VIVIS Health Treatment visitor-visa subtype, corroborated by VFS Global\'s official VITEM II checklist. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'czech-republic-medical-visa',
            'country_slug' => 'czech-republic',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'required',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Schengen short-stay (Type C) visa, medical-treatment purpose',
            'visa_subclass_code' => null,
            'intro_html' => '<p>The Czech Republic, as a Schengen member, issues short-stay Type C visas for medical treatment. Applicants need a certificate from a medical doctor or institution confirming the need for specific treatment, and an official document from the receiving Czech medical institution confirming the treatment can be performed and the patient will be accepted.</p>',
            'typical_stay' => 'Up to 90 days within any 180-day period (Schengen short-stay cap)',
            'entry_type' => 'VFS Global Czech Republic visa application centres in India (16 locations)',
            'processing_time_text' => 'Standard Schengen processing timelines apply; apply well in advance of planned treatment',
            'validity_text' => 'Up to 90 days within any 180-day period',
            'application_method' => 'Via VFS Global Czech Republic centres in India, under the Schengen short-stay visa process',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Required — standard Schengen biometric enrolment applies to Type C visa applicants',
            'government_fee_text' => 'Standard Schengen visa fee applies; confirm current amount with VFS Global/the Czech mission',
            'application_centre' => 'VFS Global Czech Republic centres, India',
            'authority_name' => 'Czech Ministry of Foreign Affairs (mzv.gov.cz) / VFS Global Czech Republic-India',
            'authority_url' => 'https://mzv.gov.cz',
            'eligibility_html' => '<p>Applicants must provide a medical certificate establishing the need for treatment, plus an official acceptance document from the receiving Czech medical institution. Overseas travel medical insurance valid across the Schengen area, covering at least EUR 30,000, is mandatory.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Financial Proof</h4><p>A personal bank statement for the last three months, with original bank seal and signature, is required.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Through VFS Global</h4><p>Czech Republic maintains 16 VFS Global visa centres across India for Schengen visa applications, including medical-treatment purpose.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Secure Schengen-Wide Insurance First</h4><p>Minimum EUR 30,000 coverage, ideally taken out in India, covering your full treatment period.</p><p>Our consultants can help you assemble the medical-institution documentation this category requires.</p>',
            'seo_title' => 'Czech Republic Medical Visa for Indians | Schengen Treatment Visa',
            'meta_description' => 'Need medical treatment in the Czech Republic? See the Schengen Type C medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Czech Republic Medical Visa for Indians — Schengen Treatment Visa',
            'og_description' => 'Need medical treatment in the Czech Republic? See the Schengen Type C medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (10 years or less old, 3+ months validity beyond stay)', 'mandatory'],
                ['Medical Documents', 'Doctor/medical institution certificate confirming need for treatment', 'mandatory'],
                ['Medical Documents', 'Official acceptance document from the receiving Czech medical institution', 'mandatory'],
                ['Financial Documents', 'Bank statement, last 3 months, bank-sealed and signed', 'mandatory'],
                ['Travel Documents', 'Schengen-wide travel medical insurance, minimum EUR 30,000', 'mandatory'],
            ],
            'steps' => [
                ['Obtain Medical Certification', 'From your doctor and the receiving Czech medical institution.'],
                ['Secure Schengen Travel Insurance', 'Minimum EUR 30,000 coverage for your full stay.'],
                ['Apply at a VFS Global Centre', 'One of 16 locations across India.'],
                ['Complete Biometric Enrolment', 'As required for Schengen Type C visas.'],
            ],
            'faqs' => [
                ['Does the Czech Republic issue a dedicated medical visa?', 'It issues a Schengen short-stay (Type C) visa under the medical-treatment purpose, not a separate visa product.'],
                ['Is biometric enrolment required?', 'Yes, standard for Schengen Type C applications.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Czech Ministry of Foreign Affairs (mzv.gov.cz) / VFS Global Czech Republic-India',
                'url' => 'https://mzv.gov.cz',
                'notes' => 'Phase 3A research: official mzv.gov.cz documentation on medical-treatment Schengen visa requirements, corroborated by VFS Global\'s official India-specific checklist. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'denmark-medical-visa',
            'country_slug' => 'denmark',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Schengen short-stay (Type C) visa, medical-treatment purpose, via ApplyVisa.um.dk',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Denmark issues short-stay Schengen visas for medical treatment through its Ministry of Foreign Affairs (um.dk) ApplyVisa portal. Applicants need an official document from the receiving Danish medical institution confirming it can perform the treatment and will accept the patient, including a cost estimate, plus a medical certificate from the applicant\'s own doctor.</p>',
            'typical_stay' => 'Up to 90 days within any 180-day period (Schengen short-stay cap)',
            'entry_type' => 'Application via ApplyVisa.um.dk and the relevant Danish mission/VFS Global centre',
            'processing_time_text' => 'Not reliably confirmed exact; apply well in advance of planned treatment',
            'validity_text' => 'Up to 90 days within any 180-day period',
            'application_method' => 'Online via ApplyVisa.um.dk, with supporting documents submitted through the Danish mission or VFS Global',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Standard Schengen visa fee applies; confirm current amount with the Danish mission',
            'application_centre' => 'ApplyVisa.um.dk / Danish mission or VFS Global centre serving India',
            'authority_name' => 'Ministry of Foreign Affairs of Denmark (um.dk)',
            'authority_url' => 'https://um.dk',
            'eligibility_html' => '<p>Applicants need official confirmation from the receiving Danish medical institution that it can perform the specific treatment and will accept the patient, including the expected cost of treatment, plus a medical certificate from a doctor or institution in the applicant\'s country of residence.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Documentation Note</h4><p>The requirements located in research are drawn from Denmark\'s harmonised medical-treatment checklist format used across its missions worldwide (confirmed for Bangladesh/Kenya/Vietnam postings); an India-specific version of this checklist was not independently located, though the same Danish MFA (um.dk) rules apply.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Online via ApplyVisa.um.dk</h4><p>Submit supporting documents through the Danish mission or VFS Global centre serving your location in India.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Secure Full Documentation First</h4><p>Both the receiving institution\'s acceptance/cost confirmation and your referring doctor\'s certificate are required before applying.</p><p>Our consultants can help you confirm the current India-specific checklist with the Danish mission.</p>',
            'seo_title' => 'Denmark Medical Visa for Indians | Schengen Treatment Visa',
            'meta_description' => 'Need medical treatment in Denmark? See the Schengen medical-purpose visa process via ApplyVisa.um.dk for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Denmark Medical Visa for Indians — Schengen Treatment Visa',
            'og_description' => 'Need medical treatment in Denmark? See the Schengen medical-purpose visa process via ApplyVisa.um.dk for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (issued within 10 years, 3+ months validity, 2+ blank pages)', 'mandatory'],
                ['Medical Documents', 'Receiving Danish medical institution\'s acceptance confirmation + cost estimate', 'mandatory'],
                ['Medical Documents', 'Referring doctor/institution\'s medical certificate', 'mandatory'],
                ['Financial Documents', 'Proof of full or partial prepayment, if relevant', 'conditional'],
                ['Travel Documents', 'Schengen-wide travel medical insurance, minimum EUR 30,000', 'mandatory'],
            ],
            'steps' => [
                ['Secure Treatment Acceptance', 'From the receiving Danish medical institution, with a cost estimate.'],
                ['Obtain Your Referring Doctor\'s Certificate', 'From your doctor/institution in India.'],
                ['Apply via ApplyVisa.um.dk', 'And submit documents through the Danish mission or VFS Global.'],
            ],
            'faqs' => [
                ['Does Denmark have a separate medical treatment visa?', 'No — it is a Schengen short-stay (Type C) visa issued under the medical-treatment purpose.'],
                ['Is the checklist India-specific?', 'The requirements follow Denmark\'s harmonised medical-treatment format used globally; an India-specific version was not independently located, though the same um.dk rules apply.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Foreign Affairs of Denmark (um.dk)',
                'url' => 'https://um.dk',
                'notes' => 'Phase 3A research: official um.dk \'document-checklist-medical-treatment.pdf\' and the harmonised checklist format confirmed used across Danish missions (Bangladesh, Kenya, Vietnam). India-specific document not directly located — disclosed as the harmonised/global rule, same precedent as the EU Article 33 generic-rule treatment. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'finland-medical-visa',
            'country_slug' => 'finland',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Schengen short-stay (Type C) visa, medical-treatment purpose',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Finland issues short-stay Schengen visas for medical treatment, following the EU-harmonised documentation standard: an invitation letter from the healthcare provider (naming the patient, diagnosis and treatment plan) and proof of financial means to cover the treatment and related expenses.</p>',
            'typical_stay' => 'Up to 90 days within any 180-day period (Schengen short-stay cap)',
            'entry_type' => 'Finnish visa application centre/VFS Global location serving India',
            'processing_time_text' => 'Not reliably confirmed exact; apply well in advance of planned treatment',
            'validity_text' => 'Up to 90 days within any 180-day period',
            'application_method' => 'Via the Finnish mission or VFS Global centre serving India, under the Schengen short-stay visa process',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Standard Schengen visa fee applies; confirm current amount with the Finnish mission',
            'application_centre' => 'VFS Global Finland centre, India',
            'authority_name' => 'European Migration Network (EMN) official documentation / VFS Global Finland',
            'authority_url' => null,
            'eligibility_html' => '<p>Applicants need an invitation letter from the Finnish healthcare provider giving the patient\'s full name, date of birth, passport number, diagnosis and treatment plan, plus pre-payment or other proof of sufficient means to cover treatment and related expenses (including insurance coverage).</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Documentation Note</h4><p>This requirement set reflects the EU-harmonised short-stay medical-treatment visa rule (confirmed via an EMN/European Migration Network official document and a VFS Global checklist for a different Finnish mission); a Finland-India-specific document was not independently located, though the same EU-wide rule applies to all Schengen member states including Finland.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Secure Your Healthcare Invitation Letter First</h4><p>This must name you specifically and set out your diagnosis and treatment plan before you apply.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply Through the Finnish Mission or VFS Global</h4><p>Serving your location in India.</p><p>Our consultants can help you confirm the current India-specific checklist with the Finnish mission.</p>',
            'seo_title' => 'Finland Medical Visa for Indians | Schengen Treatment Visa',
            'meta_description' => 'Need medical treatment in Finland? See the EU-harmonised Schengen medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Finland Medical Visa for Indians — Schengen Treatment Visa',
            'og_description' => 'Need medical treatment in Finland? See the EU-harmonised Schengen medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (3+ months validity beyond stay, 2+ blank pages)', 'mandatory'],
                ['Medical Documents', 'Invitation letter from the Finnish healthcare provider (name, diagnosis, treatment plan)', 'mandatory'],
                ['Financial Documents', 'Pre-payment or proof of sufficient means for treatment and related expenses', 'mandatory'],
                ['Travel Documents', 'Schengen-wide travel medical insurance, minimum EUR 30,000', 'mandatory'],
            ],
            'steps' => [
                ['Obtain Your Healthcare Invitation Letter', 'From the Finnish institution providing treatment.'],
                ['Arrange Financial Proof and Insurance', 'Covering treatment and related expenses.'],
                ['Apply Through the Finnish Mission or VFS Global', 'Serving your location in India.'],
            ],
            'faqs' => [
                ['Does Finland have a dedicated medical treatment visa?', 'No — it is a Schengen short-stay (Type C) visa issued under the medical-treatment purpose, per the EU-harmonised rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'European Migration Network (EMN) official documentation / VFS Global Finland',
                'url' => null,
                'notes' => 'Phase 3A research: an official EMN (EU agency, Croatian contact point) document on short-term visas for planned medical treatment confirms the EU-harmonised rule, corroborated by a VFS Global official Finland checklist (for a different VAC location, not India-specific). No direct migri.fi/um.fi or Finland-India-specific source located. Confidence: Medium.',
            ],
        ],
        [
            'page_slug' => 'greece-medical-visa',
            'country_slug' => 'greece',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'required',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Schengen short-stay (Type C) visa, medical-treatment purpose',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Greece issues short-stay Schengen visas for medical treatment, documented directly by the Greek Ministry of Foreign Affairs (mfa.gr). Applicants need a letter from a doctor or hospital in India confirming the need for treatment, plus a confirmation letter from the Greek hospital or medical institution accepting them.</p>',
            'typical_stay' => 'Up to 90 days within any 180-day period (Schengen short-stay cap)',
            'entry_type' => 'Greek mission or authorised visa application centre in India',
            'processing_time_text' => 'Standard processing 7 to 15 working days; apply at least 15 days before departure',
            'validity_text' => 'Up to 90 days within any 180-day period',
            'application_method' => 'Via the Greek mission or authorised visa application centre in India, under the Schengen short-stay visa process',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Required — biometric data submission is mandatory for Schengen Type C applicants',
            'government_fee_text' => 'Standard Schengen visa fee applies; confirm current amount with the Greek mission',
            'application_centre' => 'Greek mission/authorised visa centre, India',
            'authority_name' => 'Hellenic Ministry of Foreign Affairs (mfa.gr)',
            'authority_url' => 'https://www.mfa.gr',
            'eligibility_html' => '<p>Applicants need a letter from a doctor or hospital in India confirming the need for medical treatment in Greece, plus a confirmation letter from the receiving Greek hospital or medical institution. Financial proof covering medical and related expenses throughout treatment is also required.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Accommodation</h4><p>If not staying in a hospital for the full treatment period, confirmation from an accommodation provider or a private host\'s invitation letter (with the host\'s passport copy) is required.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply at Least 15 Days Before Departure</h4><p>Standard processing takes 7 to 15 working days for Greek Schengen applications.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Gather Both Medical Letters</h4><p>From your doctor/hospital in India and the receiving hospital/institution in Greece.</p><p>Our consultants can help you prepare the full documentary checklist for this category.</p>',
            'seo_title' => 'Greece Medical Visa for Indians | Schengen Treatment Visa',
            'meta_description' => 'Need medical treatment in Greece? See the official mfa.gr Schengen medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Greece Medical Visa for Indians — Schengen Treatment Visa',
            'og_description' => 'Need medical treatment in Greece? See the official mfa.gr Schengen medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport', 'mandatory'],
                ['Medical Documents', 'Doctor/hospital letter from India confirming need for treatment', 'mandatory'],
                ['Medical Documents', 'Confirmation letter from the receiving Greek hospital/institution', 'mandatory'],
                ['Financial Documents', 'Proof of ability to pay medical and related expenses', 'mandatory'],
                ['Accommodation Documents', 'Hotel reservation or private host invitation letter, if not hospital-housed', 'conditional'],
            ],
            'steps' => [
                ['Obtain Both Medical Letters', 'From your India-based doctor and the receiving Greek institution.'],
                ['Arrange Accommodation Proof', 'Unless staying in hospital for the full treatment.'],
                ['Apply at Least 15 Days Before Departure', 'Via the Greek mission or authorised visa centre.'],
                ['Complete Biometric Enrolment', 'Mandatory for Schengen Type C applicants.'],
            ],
            'faqs' => [
                ['How long does processing take?', 'Standard processing is 7 to 15 working days.'],
                ['Is biometric data required?', 'Yes, mandatory for Schengen Type C visa applications.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Hellenic Ministry of Foreign Affairs (mfa.gr)',
                'url' => 'https://www.mfa.gr',
                'notes' => 'Phase 3A research: official mfa.gr documents (D_MEDICAL_TREATMENT.doc, Procedures_entry_visa) directly confirm the medical-treatment Schengen visa requirements. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'hong-kong-medical-visa',
            'country_slug' => 'hong-kong',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'No dedicated medical treatment visa — medical treatment is permitted under the ordinary conditions of stay for visitors, with or without an entry visa',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Hong Kong does not issue a separate medical treatment visa. The Hong Kong Government explicitly confirms that visitors may receive medical treatment in Hong Kong without any prior special application, regardless of whether their nationality requires a visa/entry permit for Hong Kong, as long as the ordinary conditions of stay for visitors are observed.</p>',
            'typical_stay' => 'Governed by the visitor\'s ordinary permitted stay (duration depends on visa/entry-permit status, not on the medical purpose)',
            'entry_type' => 'No separate application needed for the medical-treatment purpose itself; governed by the applicant\'s underlying visit-visa/entry-permit status',
            'processing_time_text' => 'Not applicable — no dedicated medical-visa application process exists',
            'validity_text' => 'Tied to the visitor\'s underlying visa/entry-permit validity, not a separate medical-visa product',
            'application_method' => 'Not applicable — no dedicated medical visa exists; apply for the ordinary Hong Kong visit visa/entry permit appropriate to your nationality if one is required',
            'interview_required' => 'Not required — no dedicated medical-visa application exists',
            'biometric_required' => 'Not required — no dedicated medical-visa application exists',
            'government_fee_text' => 'Not applicable — no dedicated medical-visa fee exists',
            'application_centre' => 'Not applicable; Hong Kong Immigration Department (immd.gov.hk) for any underlying visit visa',
            'authority_name' => 'Government of the Hong Kong Special Administrative Region (info.gov.hk)',
            'authority_url' => 'https://www.info.gov.hk/gia/general/202305/31/P2023053100498.htm',
            'eligibility_html' => '<p>Hong Kong\'s official government position (info.gov.hk) is explicit: no prior application is needed for visitors to receive medical treatment in Hong Kong, regardless of whether they are required to apply for an entry visa or not, provided the ordinary conditions of stay for visitors are observed — no employment, no joining a business, no enrolling as a student.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>This Is a Genuine, Researched Finding — Not a Gap</h4><p>Hong Kong simply does not operate a separate \'Medical Visa\' product; medical treatment is one of the purposes already covered by ordinary visitor conditions of stay.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Confirm Your Own Entry-Visa Requirement First</h4><p>Indian passport holders should separately confirm whether they need a Hong Kong visit visa/entry permit for their nationality, via immd.gov.hk — this is independent of the medical-treatment purpose, which needs no separate application either way.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Observe Ordinary Visitor Conditions</h4><p>No employment, no business activity, no enrolling as a student, for the duration of your visit.</p><p>Our consultants can help you confirm your underlying visa/entry-permit requirement as an Indian passport holder.</p>',
            'seo_title' => 'Hong Kong Medical Visa for Indians | No Separate Visa Needed',
            'meta_description' => 'Planning medical treatment in Hong Kong? See why no dedicated medical visa exists and what applies instead, via VisaAgency.in.',
            'og_title' => 'Hong Kong Medical Visa for Indians — No Separate Visa Needed',
            'og_description' => 'Planning medical treatment in Hong Kong? See why no dedicated medical visa exists and what applies instead, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Underlying Entry Requirement', 'As an Indian passport holder, via immd.gov.hk — independent of the medical purpose.'],
                ['Travel Under Ordinary Visitor Conditions', 'No separate medical-visa application is needed.'],
            ],
            'faqs' => [
                ['Does Hong Kong have a dedicated medical treatment visa?', 'No — the Hong Kong Government confirms medical treatment is permitted under ordinary visitor conditions of stay, with no separate application needed.'],
                ['Do I still need an entry visa for Hong Kong as an Indian national?', 'That depends on your underlying nationality-based visa/entry-permit requirement, which is separate from and unaffected by the medical purpose.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Government of the Hong Kong Special Administrative Region (info.gov.hk)',
                'url' => 'https://www.info.gov.hk/gia/general/202305/31/P2023053100498.htm',
                'notes' => 'Phase 3A research: official info.gov.hk government press release explicitly confirms no prior application is needed for visitors to receive medical treatment in Hong Kong, regardless of entry-visa status, subject to ordinary visitor conditions of stay. Genuine, honest "no dedicated category" outcome, not a gap. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'hungary-medical-visa',
            'country_slug' => 'hungary',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Short-stay Schengen Type C visa, medical-treatment purpose; a separate, longer-stay Residence Permit for Medical Treatment also exists as a different legal product',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Hungary maintains two genuinely distinct mechanisms for medical treatment, confirmed by the Hungarian Embassy in New Delhi: a short-stay Schengen Type C visa under the medical-treatment purpose (per VFS Global\'s official "Checklist C Medical treatment"), and a separate, longer-stay Residence Permit for Medical Treatment (a different legal instrument entirely, documented in the Embassy\'s own "RESIDENCE PERMIT FOR MEDICAL TREATMENT" guidance). These should not be conflated.</p>',
            'typical_stay' => 'Schengen C visa: up to 90 days within any 180-day period. Residence Permit for Medical Treatment: longer-term, governed by residence-permit rules',
            'entry_type' => 'Hungarian Embassy, New Delhi (newdelhi.mfa.gov.hu / delhi.mfa.gov.hu), or VFS Global Hungary centres in India',
            'processing_time_text' => 'Standard Schengen timelines for the C visa; residence-permit processing is typically longer (not independently confirmed exact)',
            'validity_text' => 'Schengen C visa: up to 90 days within any 180-day period. Residence Permit: longer-term, per Hungarian residence-permit rules',
            'application_method' => 'Short-stay: via VFS Global Hungary centres in India, under the Schengen short-stay process. Longer-stay: residence-permit application via the Hungarian Embassy, New Delhi',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Standard Schengen visa fee for the C visa; residence-permit fee not reliably confirmed',
            'application_centre' => 'Hungarian Embassy, New Delhi, or VFS Global Hungary centres, India',
            'authority_name' => 'Embassy of Hungary, New Delhi (newdelhi.mfa.gov.hu)',
            'authority_url' => 'https://newdelhi.mfa.gov.hu',
            'eligibility_html' => '<p>For a short-stay medical visit, applicants use the Schengen Type C visa under the medical-treatment purpose. For treatment expected to exceed the 90-day Schengen cap, a separate Residence Permit for Medical Treatment is required — this is a different legal mechanism with its own documentary requirements, including a certificate from the receiving institution confirming coverage of the treatment, evidence of subsistence, and the certified address of accommodation in Hungary.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Conflate the Two Products</h4><p>The Hungarian Embassy in New Delhi maintains these as separate, distinctly-documented processes.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Confirm Which Product Your Treatment Duration Requires</h4><p>Short-stay (under 90 days): Schengen Type C visa, medical-treatment purpose, via VFS Global. Longer-stay: Residence Permit for Medical Treatment, via the Hungarian Embassy, New Delhi directly.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>India-Specific Source</h4><p>Both processes are documented directly by the Hungarian Embassy in New Delhi.</p><p>Our consultants can help you determine which of the two distinct mechanisms applies to your treatment plan.</p>',
            'seo_title' => 'Hungary Medical Visa for Indians | Schengen Visa & Residence Permit',
            'meta_description' => 'Need medical treatment in Hungary? See the distinct short-stay Schengen visa and longer-stay Residence Permit options for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Hungary Medical Visa for Indians — Schengen Visa & Residence Permit',
            'og_description' => 'Need medical treatment in Hungary? See the distinct short-stay Schengen visa and longer-stay Residence Permit options for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport, issued within the previous 10 years, 3+ months remaining validity, 2+ blank pages', 'mandatory'],
                ['Medical Documents', 'Certificate from the receiving health institution confirming expected treatment coverage', 'mandatory'],
                ['Financial Documents', 'Bank account balance statement or employer/tax-authority income certification', 'mandatory'],
                ['Supporting Documents', 'Certified address of expected accommodation in Hungary (Residence Permit route)', 'conditional'],
                ['Supporting Documents', 'Police clearance certificate (Residence Permit route)', 'conditional'],
            ],
            'steps' => [
                ['Determine Your Treatment Duration', 'To identify whether the Schengen C visa or the Residence Permit applies.'],
                ['Secure Institutional Confirmation', 'From the receiving Hungarian medical institution.'],
                ['Apply Through the Correct Channel', 'VFS Global for the short-stay visa, or the Hungarian Embassy New Delhi directly for the Residence Permit.'],
            ],
            'faqs' => [
                ['Does Hungary have one medical visa product?', 'No — a short-stay Schengen Type C medical-treatment visa and a separate, longer-stay Residence Permit for Medical Treatment both exist as distinct legal mechanisms.'],
                ['Where do Indian applicants apply?', 'Via VFS Global Hungary centres (short-stay) or directly through the Hungarian Embassy, New Delhi (Residence Permit).'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Embassy of Hungary, New Delhi (newdelhi.mfa.gov.hu)',
                'url' => 'https://newdelhi.mfa.gov.hu',
                'notes' => 'Phase 3A research: official Hungarian Embassy New Delhi documents directly confirm BOTH the short-stay Schengen C "Checklist C Medical treatment" (via VFS Global) AND a separate "RESIDENCE PERMIT FOR MEDICAL TREATMENT" document — India-specific, official source. Governance distinction preserved per research audit. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'jordan-medical-visa',
            'country_slug' => 'jordan',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Treatment-purpose entry via the Jordanian Ministry of Interior electronic visa system',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Jordan\'s Ministry of Interior electronic visa system explicitly supports treatment-purpose entry. A Jordanian medical provider must substantiate the treatment or appointment as part of the application, and the approved stay is limited to the medical purpose for which entry was granted.</p>',
            'typical_stay' => 'Limited to the approved medical purpose; exact cap not reliably confirmed',
            'entry_type' => 'Jordan Ministry of Interior\'s electronic visa portal (eservices.moi.gov.jo)',
            'processing_time_text' => 'Not reliably confirmed exact',
            'validity_text' => 'Limited to the approved medical purpose',
            'application_method' => 'Online via the Ministry of Interior\'s e-visa system (eservices.moi.gov.jo)',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Jordan Ministry of Interior e-visa portal',
            'authority_name' => 'Jordan Ministry of Interior (moi.gov.jo)',
            'authority_url' => 'https://moi.gov.jo',
            'eligibility_html' => '<p>Applicants need a Jordanian medical provider to substantiate the treatment or appointment, financial resources to cover treatment and living costs, and a valid passport. The approved stay is limited to the purpose for which entry was granted — this is not an open-ended tourist stay.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Secure Your Jordanian Medical Provider\'s Confirmation First</h4><p>This substantiates your treatment-purpose entry application.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Apply Online</h4><p>Via the Ministry of Interior\'s electronic visa system.</p><p>Our consultants can help you confirm the current documentary checklist with moi.gov.jo.</p>',
            'seo_title' => 'Jordan Medical Visa for Indians | Treatment-Purpose e-Visa',
            'meta_description' => 'Travelling to Jordan for medical treatment? See the Ministry of Interior treatment-purpose e-visa process for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Jordan Medical Visa for Indians — Treatment-Purpose e-Visa',
            'og_description' => 'Travelling to Jordan for medical treatment? See the Ministry of Interior treatment-purpose e-visa process for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport', 'mandatory'],
                ['Financial Documents', 'Proof of resources to cover treatment and living costs', 'mandatory'],
                ['Medical Documents', 'Substantiation of treatment/appointment from a Jordanian medical provider', 'mandatory'],
            ],
            'steps' => [
                ['Secure Treatment Substantiation', 'From a Jordanian medical provider.'],
                ['Apply Online', 'Via the Ministry of Interior\'s e-visa system.'],
                ['Travel Within Your Approved Purpose', 'The stay is limited to the medical purpose granted.'],
            ],
            'faqs' => [
                ['Does Jordan support medical treatment entry?', 'Yes — the Ministry of Interior\'s electronic visa system explicitly supports treatment-purpose entry.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Jordan Ministry of Interior (moi.gov.jo)',
                'url' => 'https://moi.gov.jo',
                'notes' => 'Phase 3A research: official Jordan MOI e-visa portal (eservices.moi.gov.jo) confirms treatment-purpose entry is supported. Fee/processing-time detail not located. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'norway-medical-visa',
            'country_slug' => 'norway',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'For treatment over 90 days: a Residence Permit for Medical Treatment (not a visa), via UDI. For treatment under 90 days: the harmonised Schengen short-stay medical-treatment process',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Norway maintains two genuinely distinct mechanisms, confirmed directly by the Norwegian Directorate of Immigration (UDI): treatment expected to last more than 90 days requires an advance Residence Permit application (a different legal instrument from a visa, valid up to one year maximum, with an accompanying-person permit also available), while treatment under 90 days follows the standard, harmonised Schengen short-stay medical-treatment checklist process used across Norwegian missions.</p>',
            'typical_stay' => 'Residence Permit route: up to 1 year maximum. Short-stay Schengen route: up to 90 days within any 180-day period',
            'entry_type' => 'Royal Norwegian Embassy, New Delhi (handles India, Nepal, Sri Lanka, Maldives and Bhutan) or VFS Global locations in India',
            'processing_time_text' => 'Not reliably confirmed exact for either route',
            'validity_text' => 'Residence Permit route: up to 1 year. Short-stay Schengen route: up to 90 days within 180 days',
            'application_method' => 'Residence Permit: advance application processed by the Royal Norwegian Embassy, New Delhi. Short-stay: via VFS Global under the Schengen short-stay process',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact for either route',
            'application_centre' => 'Royal Norwegian Embassy, New Delhi, or VFS Global locations in India',
            'authority_name' => 'Norwegian Directorate of Immigration (UDI) / Royal Norwegian Embassy, New Delhi',
            'authority_url' => 'https://www.udi.no/en/want-to-apply/medical-treatment-for-citizens-of-countries-outside-the-eueea-area/',
            'eligibility_html' => '<p>For treatment exceeding 90 days, applicants must have an offer of medical treatment from a Norwegian institution, pay using their own funds or public funds from their home country, and the hospital must confirm the treatment will not negatively affect services for patients living in Norway. The expected treatment duration must be under one year, and the applicant must not be subject to an entry ban. An accompanying person can also be granted a matching residence permit.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Conflate the Two Mechanisms</h4><p>UDI explicitly treats medical treatment over 90 days as a Residence Permit matter, not a visa — a different legal product from the short-stay Schengen process used for shorter treatment.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Applications from India Go Through New Delhi</h4><p>The Royal Norwegian Embassy in New Delhi specifically handles applications from India (plus Nepal, Sri Lanka, Maldives and Bhutan), via VFS locations.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm Which Route Applies</h4><p>Based on your expected treatment duration — under or over 90 days.</p><p>Our consultants can help you determine whether the Residence Permit or short-stay Schengen route fits your treatment plan.</p>',
            'seo_title' => 'Norway Medical Visa for Indians | Residence Permit & Schengen Visa',
            'meta_description' => 'Need medical treatment in Norway? See the distinct Residence Permit (over 90 days) and short-stay Schengen options for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Norway Medical Visa for Indians — Residence Permit & Schengen Visa',
            'og_description' => 'Need medical treatment in Norway? See the distinct Residence Permit (over 90 days) and short-stay Schengen options for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Medical Documents', 'Offer of medical treatment from a Norwegian institution', 'mandatory'],
                ['Financial Documents', 'Proof of ability to pay using own funds or public funds from India', 'mandatory'],
                ['Supporting Documents', 'Hospital confirmation treatment will not displace local patients (Residence Permit route)', 'conditional'],
                ['Supporting Documents', 'Proof applicant is not subject to a Norway/Schengen entry ban', 'mandatory'],
            ],
            'steps' => [
                ['Determine Your Treatment Duration', 'To identify whether the Residence Permit or short-stay Schengen route applies.'],
                ['Secure Your Treatment Offer', 'From the Norwegian medical institution.'],
                ['Apply Through the Royal Norwegian Embassy, New Delhi', 'Which handles applications from India directly.'],
            ],
            'faqs' => [
                ['Is Norway medical treatment handled as a visa?', 'For treatment over 90 days, it is a Residence Permit, not a visa — a different legal mechanism. Under 90 days follows the standard short-stay Schengen process.'],
                ['Can someone accompany me?', 'Yes — an accompanying person can also be granted a matching residence permit for treatment over 90 days.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Norwegian Directorate of Immigration (UDI) / Royal Norwegian Embassy, New Delhi',
                'url' => 'https://www.udi.no/en/want-to-apply/medical-treatment-for-citizens-of-countries-outside-the-eueea-area/',
                'notes' => 'Phase 3A research: official udi.no page directly confirms the >90-day Residence Permit mechanism and India-specific routing via the Royal Norwegian Embassy New Delhi; norway.no harmonised checklists (for other missions) confirm the <90-day short-stay Schengen process also exists. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'poland-medical-visa',
            'country_slug' => 'poland',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Schengen short-stay (Type C) visa, medical-treatment purpose',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Poland issues short-stay Schengen visas for medical treatment, documented directly through official Polish government (gov.pl) attachments. Applicants need a certificate from a medical doctor or institution confirming the need for treatment, an official acceptance document from the receiving Polish medical institution, and proof of pre-payment of the treatment.</p>',
            'typical_stay' => 'Up to 90 days within any 180-day period (Schengen short-stay cap)',
            'entry_type' => 'Polish mission or authorised visa application centre in India',
            'processing_time_text' => 'Not reliably confirmed exact; apply well in advance of planned treatment',
            'validity_text' => 'Up to 90 days within any 180-day period',
            'application_method' => 'Via the Polish mission or authorised visa application centre in India, under the Schengen short-stay visa process',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Standard Schengen visa fee applies; confirm current amount with the Polish mission',
            'application_centre' => 'Polish mission/authorised visa centre, India',
            'authority_name' => 'Government of Poland (gov.pl)',
            'authority_url' => 'https://www.gov.pl',
            'eligibility_html' => '<p>Applicants need a doctor/institution certificate confirming the need for specific treatment, an official document from the receiving Polish medical institution confirming acceptance, and proof of pre-payment of the treatment. Travel medical insurance (TMI) must be issued by a company from Poland\'s list of approved Indian insurance companies, with coverage of at least EUR 30,000 valid for the entire Schengen-area stay. Proof of accommodation availability and bank statements from the last 3 months (stamped and signed) are also required.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Use an Approved Indian Insurer</h4><p>Poland requires travel medical insurance from a company on its approved list of Indian insurers — handwritten certificates are not accepted.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Gather Both Medical Documents</h4><p>Your own doctor\'s certificate and the receiving Polish institution\'s acceptance confirmation.</p><p>Our consultants can help you confirm the current approved-insurer list and documentary checklist.</p>',
            'seo_title' => 'Poland Medical Visa for Indians | Schengen Treatment Visa',
            'meta_description' => 'Need medical treatment in Poland? See the official gov.pl Schengen medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Poland Medical Visa for Indians — Schengen Treatment Visa',
            'og_description' => 'Need medical treatment in Poland? See the official gov.pl Schengen medical-purpose visa requirements for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (10 years or less old, 3+ months validity, 2+ blank pages)', 'mandatory'],
                ['Medical Documents', 'Doctor/institution certificate confirming need for treatment', 'mandatory'],
                ['Medical Documents', 'Receiving Polish institution\'s acceptance confirmation', 'mandatory'],
                ['Financial Documents', 'Proof of pre-payment of the treatment', 'mandatory'],
                ['Financial Documents', 'Bank statements, last 3 months, stamped and signed', 'mandatory'],
                ['Travel Documents', 'Travel medical insurance from an approved Indian insurer, minimum EUR 30,000', 'mandatory'],
            ],
            'steps' => [
                ['Obtain Both Medical Documents', 'From your doctor and the receiving Polish institution.'],
                ['Secure Approved-Insurer Travel Insurance', 'Minimum EUR 30,000 coverage, approved Indian insurer only.'],
                ['Apply Through the Polish Mission or Visa Centre', 'Serving your location in India.'],
            ],
            'faqs' => [
                ['Does Poland require pre-payment proof?', 'Yes — proof of pre-payment of the treatment is a documented requirement.'],
                ['Can I use any travel insurer?', 'No — Poland requires a policy from its approved list of Indian insurance companies.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Government of Poland (gov.pl)',
                'url' => 'https://www.gov.pl',
                'notes' => 'Phase 3A research: official gov.pl attachment documents directly confirm the medical-treatment Schengen visa requirements, including the approved-Indian-insurer rule. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'portugal-medical-visa',
            'country_slug' => 'portugal',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'E1 — Temporary Stay Visa for Medical Treatment Purposes',
            'visa_subclass_code' => 'E1',
            'intro_html' => '<p>Portugal operates a specifically named national visa product for this purpose: the E1 Temporary Stay Visa for Medical Treatment, confirmed across multiple official VFS Global one-pager checklists and the Portuguese MFA\'s official visa portal (vistos.mne.gov.pt). Applicants need valid travel insurance covering necessary medical expenses, including urgent assistance and possible repatriation.</p>',
            'typical_stay' => 'Governed by the national temporary-stay visa terms (exact cap not independently confirmed)',
            'entry_type' => 'Portuguese Embassy, Consulate, or authorised visa application centre in India',
            'processing_time_text' => 'Not reliably confirmed exact',
            'validity_text' => 'Governed by the E1 Temporary Stay Visa terms',
            'application_method' => 'Via the Portuguese Embassy, Consulate, or authorised visa application centres in India',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Portuguese Embassy/Consulate or authorised visa centre, India',
            'authority_name' => 'Portuguese Ministry of Foreign Affairs (vistos.mne.gov.pt)',
            'authority_url' => 'https://vistos.mne.gov.pt',
            'eligibility_html' => '<p>Applicants submit a completed national visa application, 2 passport photographs, a passport valid for at least 3 months beyond the intended stay, and valid travel insurance covering necessary medical expenses including urgent assistance and repatriation.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Cooperation Agreement Provision</h4><p>For patients travelling under bilateral Cooperation Agreements, proof of means of subsistence and accommodation may be replaced by a statement from the applicant\'s country\'s Embassy in Lisbon — this provision\'s applicability to India specifically was not independently confirmed.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Through the Portuguese Mission</h4><p>All Indian travellers must obtain a visa before entering Portugal — apply through the Embassy, Consulate, or an authorised visa centre.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Secure Full Travel Medical Insurance</h4><p>Covering urgent medical assistance and possible repatriation for your full stay.</p><p>Our consultants can help you confirm the current E1 documentary checklist with the Portuguese mission.</p>',
            'seo_title' => 'Portugal Medical Visa for Indians | E1 Temporary Stay Visa',
            'meta_description' => 'Need medical treatment in Portugal? See the E1 Temporary Stay Visa for Medical Treatment Purposes for Indian applicants, via VisaAgency.in.',
            'og_title' => 'Portugal Medical Visa for Indians — E1 Temporary Stay Visa',
            'og_description' => 'Need medical treatment in Portugal? See the E1 Temporary Stay Visa for Medical Treatment Purposes for Indian applicants, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (3+ months validity beyond stay)', 'mandatory'],
                ['Basic Documents', '2 passport-sized photographs', 'mandatory'],
                ['Travel Documents', 'Valid travel insurance covering medical expenses, urgent assistance and repatriation', 'mandatory'],
                ['Supporting Documents', 'Embassy-in-Lisbon statement in lieu of subsistence/accommodation proof (Cooperation Agreement cases)', 'conditional'],
            ],
            'steps' => [
                ['Confirm Your Treatment Arrangements', 'With the receiving Portuguese medical institution.'],
                ['Secure Travel Medical Insurance', 'Covering urgent assistance and repatriation.'],
                ['Apply at the Portuguese Mission', 'Embassy, Consulate, or authorised visa centre in India.'],
            ],
            'faqs' => [
                ['What is the E1 visa?', 'Portugal\'s named national visa product: the Temporary Stay Visa for Medical Treatment Purposes.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Portuguese Ministry of Foreign Affairs (vistos.mne.gov.pt)',
                'url' => 'https://vistos.mne.gov.pt',
                'notes' => 'Phase 3A research: multiple official VFS Global one-pager checklists (UAE, UK, Qatar missions) explicitly name the "E1 — Temporary Stay Visa for Medical Treatment Purposes" product, corroborated by the official Portuguese MFA visa portal. India-specific checklist not directly located; the product and its core requirements are confirmed. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'sweden-medical-visa',
            'country_slug' => 'sweden',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'conditional',
            'official_visa_name' => 'Schengen short-stay (Type C) visa, medical-treatment purpose',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Sweden issues short-stay Schengen visas for medical treatment, documented through an India-specific official checklist published by the Swedish Ministry for Foreign Affairs for its New Delhi mission. Applicants need a certificate from a medical doctor or institution confirming the need for treatment, an official acceptance document from the receiving Swedish institution, and correspondence between the sending and receiving doctors.</p>',
            'typical_stay' => 'Up to 90 days within any 180-day period (Schengen short-stay cap)',
            'entry_type' => 'Embassy of Sweden, New Delhi, or VFS Global Sweden centres in India',
            'processing_time_text' => 'Not reliably confirmed exact; apply well in advance of planned treatment',
            'validity_text' => 'Up to 90 days within any 180-day period',
            'application_method' => 'Via VFS Global Sweden centres in India, under the Schengen short-stay visa process',
            'interview_required' => 'May be required by the Embassy of Sweden in New Delhi on a case-by-case basis',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Standard Schengen visa fee applies; confirm current amount with VFS Global/the Swedish mission',
            'application_centre' => 'VFS Global Sweden centres, India',
            'authority_name' => 'Embassy of Sweden, New Delhi (Swedish Ministry for Foreign Affairs)',
            'authority_url' => 'https://api.swedenabroad.com/globalassets/ambassader/indien-new-delhi/documents/sweden-medical-checklist.pdf',
            'eligibility_html' => '<p>Applicants need a certificate from a medical doctor or institution confirming the need for specific treatment in Sweden, an official acceptance document from the receiving Swedish institution, proof of pre-payment of treatment, and correspondence between the sending (Indian) doctor and the receiving Swedish institution. Return-ticket flight reservations are required, along with intra-Schengen travel proof if visiting multiple Schengen states.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>India-Specific Documentation</h4><p>This checklist is published specifically for applicants applying via the Embassy of Sweden, New Delhi — a genuinely India-specific official source, not a generic harmonised template.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>An India-Specific Official Checklist Exists</h4><p>Published directly by the Embassy of Sweden, New Delhi, covering exactly this process for Indian applicants.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Be Prepared for a Possible Interview</h4><p>The Embassy of Sweden, New Delhi may request additional documents or call applicants for an interview.</p><p>Our consultants can help you assemble the full India-specific medical-treatment checklist.</p>',
            'seo_title' => 'Sweden Medical Visa for Indians | Schengen Treatment Visa',
            'meta_description' => 'Need medical treatment in Sweden? See the India-specific Embassy checklist for the Schengen medical-purpose visa, via VisaAgency.in.',
            'og_title' => 'Sweden Medical Visa for Indians — Schengen Treatment Visa',
            'og_description' => 'Need medical treatment in Sweden? See the India-specific Embassy checklist for the Schengen medical-purpose visa, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (no handwritten passports or manually-altered post-01/04/2010 passports accepted)', 'mandatory'],
                ['Medical Documents', 'Doctor/institution certificate confirming need for treatment', 'mandatory'],
                ['Medical Documents', 'Receiving Swedish institution\'s acceptance confirmation', 'mandatory'],
                ['Medical Documents', 'Correspondence between the sending (India) doctor and receiving Swedish institution', 'mandatory'],
                ['Financial Documents', 'Proof of pre-payment of treatment', 'mandatory'],
                ['Travel Documents', 'Return-ticket flight reservation; intra-Schengen travel proof if applicable', 'mandatory'],
            ],
            'steps' => [
                ['Obtain Medical Documentation', 'From your India-based doctor and the receiving Swedish institution, including their correspondence.'],
                ['Secure Travel and Insurance Documents', 'Return ticket plus Schengen-wide medical insurance of EUR 30,000+.'],
                ['Apply via VFS Global Sweden', 'Be prepared for a possible Embassy interview.'],
            ],
            'faqs' => [
                ['Is this checklist India-specific?', 'Yes — published directly by the Embassy of Sweden, New Delhi, for applicants in India.'],
                ['Could I be called for an interview?', 'Yes — the Embassy of Sweden, New Delhi may request an interview or additional documents.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Embassy of Sweden, New Delhi (Swedish Ministry for Foreign Affairs)',
                'url' => 'https://api.swedenabroad.com/globalassets/ambassader/indien-new-delhi/documents/sweden-medical-checklist.pdf',
                'notes' => 'Phase 3A research: an India-New-Delhi-specific official Swedish MFA checklist document was directly located, corroborated by migrationsverket.se. The strongest Medical finding of this phase — genuinely India-specific, not a generic harmonised template. Confidence: High.',
            ],
        ],
    ];
}
