<?php
/**
 * Phase 3 -- Medical Visa research for 12 of 33 Tier-B countries (expanding
 * Phase 2B Medical coverage); 15 countries had zero search coverage and 6 more
 * (argentina, bangladesh, brazil, hong-kong, jordan, myanmar) returned only
 * reverse-direction noise (India's own inbound medical-visa content for
 * foreign patients, not the target country's outbound process) and were
 * correctly excluded rather than miswritten -- both groups left at generic
 * status, disclosed as a known gap.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_tierb_medical(): array
{
    return [
        [
            'page_slug' => 'austria-medical-visa',
            'country_slug' => 'austria',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'conditional',
            'interview_status' => 'conditional',
            'official_visa_name' => 'Medical treatment handled under the standard Schengen "C" visa with "medical treatment" as declared purpose (<=90 days); national "D" visa needed beyond 90 days. No separately branded "Austrian medical visa" confirmed by an official source',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Austria does not maintain a separately-branded medical visa — Indian nationals travelling for medical treatment declare "medical treatment" as the purpose on the standard Schengen "C" visa (up to 90 days) or, for longer ongoing treatment, the national "D" visa. This was found via secondary sources, not confirmed on an official Austrian government page.</p>',
            'typical_stay' => 'Up to 90 days/180-day period on the "C" visa; national "D" visa needed beyond 90 days',
            'entry_type' => 'VFS Global Austria centre in India (standard Schengen channel) — not explicitly confirmed for the medical sub-type',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Up to 90 days/180-day period ("C"); "D" visa required beyond that',
            'application_method' => 'VFS Global Austria centre in India — not explicitly confirmed for the medical sub-type',
            'interview_required' => 'Conditional (general Schengen rule)',
            'biometric_required' => 'Conditional (general Schengen rule)',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'VFS Global',
            'authority_name' => 'Austrian Embassy/Consulate in India',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals travelling to Austria for medical treatment declare this purpose on the standard Schengen visa application, requiring a hospital appointment/treatment confirmation (per secondary sources, not officially confirmed), proof of pre-payment or sufficient funds for treatment cost, and travel medical insurance of at least EUR 30,000 covering evacuation/repatriation.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Declare "Medical Treatment" as Your Purpose</h4><p>Apply via the standard Schengen Type C (or national D visa for longer treatment) process, declaring medical treatment as your purpose and including your hospital appointment confirmation.</p><p>Our consultants can help you prepare the necessary documentation for your Austria medical-treatment visa application.</p>',
            'seo_title' => 'Austria Medical Treatment Visa for Indians | Schengen Route',
            'meta_description' => 'Travelling to Austria for medical treatment? See how the standard Schengen visa covers this for Indian nationals, via VisaAgency.in.',
            'og_title' => 'Austria Medical Treatment Visa for Indians — Schengen Route',
            'og_description' => 'Travelling to Austria for medical treatment? See how the standard Schengen visa covers this for Indian nationals, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport valid 3+ months beyond intended stay', 'mandatory'],
                ['Medical Documents', 'Proof of hospital appointment/treatment plan', 'conditional'],
                ['Supporting Documents', 'Proof of pre-payment or sufficient funds for treatment cost', 'mandatory'],
                ['Supporting Documents', 'Travel medical insurance, minimum EUR 30,000 coverage including evacuation/repatriation', 'mandatory'],
            ],
            'steps' => [
                ['Obtain Your Hospital Appointment Confirmation', 'From the Austrian medical institution.'],
                ['Apply via the Standard Schengen Process', 'Declaring medical treatment as your purpose.'],
                ['For Treatment Beyond 90 Days: Apply for the National D Visa', 'Instead of the standard Type C.'],
            ],
            'faqs' => [
                ['Does Austria have a dedicated medical visa?', 'No — medical treatment is declared as a purpose on the standard Schengen Type C or national D visa.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Austrian Embassy/Consulate in India',
                'url' => null,
                'notes' => 'Researched via WebSearch; all data from secondary sites (godigit, sbnri, reliancegeneral, bajajfinserv); no official Austrian (.gv.at) page was retrieved.',
            ],
        ],
        [
            'page_slug' => 'azerbaijan-medical-visa',
            'country_slug' => 'azerbaijan',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Dedicated — Azerbaijan’s e-Visa explicitly lists "medical" as one of three permitted purposes (tourism, business, medical)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Azerbaijan’s e-Visa explicitly lists "medical" as one of its three permitted purposes (alongside tourism and business), making this a genuinely confirmed, dedicated medical-purpose entry route for Indian nationals — processed entirely online.</p>',
            'typical_stay' => 'e-Visa valid 90 days from issue; max continuous stay 30 days per entry',
            'entry_type' => 'Online e-visa portal (ASAN Visa)',
            'processing_time_text' => 'Standard ~3 days; urgent service ~3 hours (secondary sources — not confirmed specific to medical category)',
            'validity_text' => 'Valid 90 days from issue; max continuous stay 30 days',
            'application_method' => 'Online e-visa portal (ASAN Visa, likely evisa.gov.az)',
            'interview_required' => 'Not required',
            'biometric_required' => 'Not required',
            'government_fee_text' => 'Not reliably confirmed for the medical category specifically',
            'application_centre' => 'Online via ASAN Visa',
            'authority_name' => 'State Migration Service of Azerbaijan / ASAN Visa',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals travelling to Azerbaijan for medical treatment can select "medical" as the stated purpose on the standard e-Visa application, requiring only a digital passport bio-page, proof of accommodation, payment, and an email address — no explicit hospital-invitation document was confirmed as mandatory.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Select "Medical" as Your Purpose on the e-Visa</h4><p>This is a genuinely confirmed, dedicated entry purpose — apply online with your passport bio-page and accommodation proof.</p><p>Our consultants can help you complete your medical-purpose e-Visa application for Azerbaijan.</p>',
            'seo_title' => 'Azerbaijan Medical Visa for Indians | Dedicated e-Visa Purpose',
            'meta_description' => 'Travelling to Azerbaijan for medical treatment? See the dedicated "medical" purpose on the e-Visa for Indian nationals, via VisaAgency.in.',
            'og_title' => 'Azerbaijan Medical Visa for Indians — Dedicated e-Visa Purpose',
            'og_description' => 'Travelling to Azerbaijan for medical treatment? See the dedicated "medical" purpose on the e-Visa for Indian nationals, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Digital passport bio-page', 'mandatory'],
                ['Supporting Documents', 'Proof of accommodation', 'mandatory'],
            ],
            'steps' => [
                ['Apply Online', 'Selecting "medical" as your e-Visa purpose.'],
                ['Submit Your Passport Bio-Page and Accommodation Proof', 'No explicit hospital-invitation document confirmed as mandatory.'],
            ],
            'faqs' => [
                ['Does Azerbaijan have a dedicated medical visa?', 'Yes — "medical" is one of three explicitly listed e-Visa purposes.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'State Migration Service of Azerbaijan / ASAN Visa',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official URL was directly retrieved for this specific purpose-category confirmation — secondary travel-agency sources were used.',
            ],
        ],
        [
            'page_slug' => 'belgium-medical-visa',
            'country_slug' => 'belgium',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'conditional',
            'interview_status' => 'conditional',
            'official_visa_name' => 'Medical treatment handled under the standard Schengen "C" visa with "medical treatment" as declared purpose (<=90 days); national "D" visa needed beyond 90 days. No separately branded "Belgian medical visa" confirmed by an official source',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Belgium does not maintain a separately-branded medical visa — medical treatment is declared as a purpose on the standard Schengen "C" visa (up to 90 days) or the national "D" visa for longer treatment. This pattern mirrors Austria’s approach, found via secondary sources rather than confirmed officially for Belgium specifically.</p>',
            'typical_stay' => 'Up to 90 days/180-day period ("C"); "D" visa required beyond that',
            'entry_type' => 'VFS Global Belgium centre in India (standard Schengen channel) — not explicitly confirmed for the medical sub-type',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Up to 90 days/180-day period ("C"); "D" visa required beyond that',
            'application_method' => 'VFS Global Belgium centre in India — not explicitly confirmed for the medical sub-type',
            'interview_required' => 'Conditional (general Schengen rule)',
            'biometric_required' => 'Conditional (general Schengen rule)',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'VFS Global',
            'authority_name' => 'Belgian Embassy/Consulate in India',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals travelling to Belgium for medical treatment declare this purpose on the standard Schengen visa application, requiring a passport valid 6 months beyond stay with 2+ blank pages, travel health insurance of at least EUR 30,000 across the Schengen area, 2 recent photos, copies of previous visas, and a cover letter stating the purpose of visit and itinerary.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Declare "Medical Treatment" as Your Purpose</h4><p>Apply via the standard Schengen Type C (or national D visa for longer treatment) process, with a clear cover letter stating your medical purpose and itinerary.</p><p>Our consultants can help you prepare a complete documentation package for your Belgium medical visit.</p>',
            'seo_title' => 'Belgium Medical Treatment Visa for Indians | Schengen Route',
            'meta_description' => 'Travelling to Belgium for medical treatment? See how the standard Schengen visa covers this for Indian nationals, via VisaAgency.in.',
            'og_title' => 'Belgium Medical Treatment Visa for Indians — Schengen Route',
            'og_description' => 'Travelling to Belgium for medical treatment? See how the standard Schengen visa covers this for Indian nationals, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport valid 6 months beyond stay, 2+ blank pages', 'mandatory'],
                ['Supporting Documents', 'Travel health insurance, minimum EUR 30,000 coverage across Schengen', 'mandatory'],
                ['Basic Documents', '2 recent photos, copies of previous visas', 'mandatory'],
                ['Supporting Documents', 'Cover letter stating purpose of visit and itinerary', 'mandatory'],
            ],
            'steps' => [
                ['Prepare Your Cover Letter', 'Clearly stating your medical purpose and itinerary.'],
                ['Apply via the Standard Schengen Process', 'With your insurance and previous-visa copies.'],
                ['For Treatment Beyond 90 Days: Apply for the National D Visa', 'Instead of the standard Type C.'],
            ],
            'faqs' => [
                ['Does Belgium have a dedicated medical visa?', 'No — medical treatment is declared as a purpose on the standard Schengen Type C or national D visa.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Belgian Embassy/Consulate in India',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Belgian source was found for the correct direction — content found (indianembassybrussels.gov.in "Checklist for Medical Visa.pdf") was India’s own inbound medical visa checklist for Belgian nationals, filtered out as reverse-direction.',
            ],
        ],
        [
            'page_slug' => 'bhutan-medical-visa',
            'country_slug' => 'bhutan',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'No dedicated medical visa — Indian citizens need no visa for Bhutan, only an Entry Permit, which covers any purpose including medical treatment',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Bhutan has no dedicated medical visa category — the same free Entry Permit that Indian citizens use for any purpose covers medical treatment as well, with officials potentially requesting a health certificate/medical exam on arrival in some cases.</p>',
            'typical_stay' => 'Initial Entry Permit allows up to 7 days in select regions; extension mechanism for medical treatment not reliably confirmed',
            'entry_type' => 'On arrival at Paro International Airport or Phuentsholing border, or online pre-arrival permit system',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Initial permit up to 7 days in select regions',
            'application_method' => 'On arrival at Paro International Airport or Phuentsholing border, or online pre-arrival permit system',
            'interview_required' => 'Not required (entry permit, not consular visa)',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'No fee for the Entry Permit itself. A Sustainable Development Fee (SDF) applies broadly to tourists; Indian nationals pay a different concessional rate, with the exact current figure not reliably confirmed in this research pass',
            'application_centre' => 'Entry point (border/airport)',
            'authority_name' => 'Department of Immigration, Royal Government of Bhutan',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals visiting Bhutan for medical treatment need only the standard free Entry Permit, using a valid Indian ID/passport — no separate medical-specific document was found as mandatory. Since Indians are visa-exempt for Bhutan under the India-Bhutan bilateral arrangement, this is itself the main India-specific fact for this category.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>No Separate Medical Visa Needed</h4><p>Your Entry Permit covers medical treatment just as it covers any other purpose — though officials might ask for a health certificate on arrival in some cases, per unconfirmed secondary sources.</p><p>Our consultants can help you prepare for a smooth entry regardless of your travel purpose.</p>',
            'seo_title' => 'Bhutan Medical Treatment for Indians | No Visa Required',
            'meta_description' => 'Travelling to Bhutan for medical treatment? Indian citizens need no visa, only an Entry Permit, via VisaAgency.in.',
            'og_title' => 'Bhutan Medical Treatment for Indians — No Visa Required',
            'og_description' => 'Travelling to Bhutan for medical treatment? Indian citizens need no visa, only an Entry Permit, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid Indian ID/passport for Entry Permit', 'mandatory'],
            ],
            'steps' => [
                ['Arrive With Valid Identity Documents', 'No visa needed for any purpose, including medical treatment.'],
                ['Receive Your Entry Permit', 'On the spot at the airport or border.'],
            ],
            'faqs' => [
                ['Do Indian citizens need a medical visa for Bhutan?', 'No — the same treaty-based visa-free Entry Permit covers medical treatment.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Department of Immigration, Royal Government of Bhutan',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Bhutanese government source was directly retrieved — secondary sources did not clearly separate the Indian-national SDF rate from the general rate for other tourists.',
            ],
        ],
        [
            'page_slug' => 'cambodia-medical-visa',
            'country_slug' => 'cambodia',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'A distinct Medical Visa category is reported to exist for Cambodia (separate from Tourist/Business e-visa and visa-on-arrival), generally single-entry, valid up to 30 days — per secondary sources only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Cambodia is reported to maintain a distinct Medical Visa category, separate from the Tourist/Business e-visa and visa-on-arrival, generally single-entry and valid up to 30 days — though this was found only via secondary sources and could not be confirmed officially in this research pass.</p>',
            'typical_stay' => 'Single entry, up to 30 days; extendability not confirmed',
            'entry_type' => 'Not clearly distinguished — possibly via Cambodian Embassy/Consulate for the dedicated Medical Visa, vs. e-visa portal/VOA for general entry covering medical visits',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Single entry, up to 30 days',
            'application_method' => 'Not clearly distinguished — possibly via Cambodian Embassy/Consulate, or e-visa portal/VOA',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'Not reliably confirmed precisely',
            'authority_name' => 'Ministry of Foreign Affairs and International Cooperation, Cambodia / General Department of Immigration',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals travelling to Cambodia for medical treatment are reported to need this distinct Medical Visa category, requiring a recommendation letter from a Cambodian hospital or doctor, plus relevant medical records (per secondary sources, not officially confirmed). Sources are inconsistent about whether "medical" needs this distinct visa vs. being covered under the general VOA/e-visa.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Verify Which Route Applies to You</h4><p>Sources are inconsistent about whether Cambodia requires this distinct Medical Visa or simply covers medical visits under the general tourist/business routes — confirm directly before travel.</p><p>Our consultants can help you verify the current route for your Cambodia medical visit.</p>',
            'seo_title' => 'Cambodia Medical Visa for Indians | Reported Dedicated Category',
            'meta_description' => 'Travelling to Cambodia for medical treatment? See a reported dedicated Medical Visa category, flagged for direct verification, via VisaAgency.in.',
            'og_title' => 'Cambodia Medical Visa for Indians — Reported Dedicated Category',
            'og_description' => 'Travelling to Cambodia for medical treatment? See a reported dedicated Medical Visa category, flagged for direct verification, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (6+ months validity)', 'mandatory'],
                ['Basic Documents', 'Recent passport photo', 'mandatory'],
                ['Medical Documents', 'Recommendation letter from Cambodian hospital/doctor', 'conditional'],
                ['Medical Documents', 'Relevant medical records', 'conditional'],
                ['Supporting Documents', 'Proof of sufficient funds, onward travel/accommodation', 'mandatory'],
            ],
            'steps' => [
                ['Obtain a Hospital/Doctor Recommendation Letter', 'If pursuing the dedicated Medical Visa route.'],
                ['Verify Which Entry Route Applies', 'Sources are inconsistent — confirm directly.'],
            ],
            'faqs' => [
                ['Does Cambodia have a dedicated medical visa?', 'A distinct category is reported, but this is secondary-sourced only — confirm directly before travel.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Foreign Affairs and International Cooperation, Cambodia / General Department of Immigration',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Cambodian source was retrieved — secondary sources only, with inconsistency about whether a distinct visa or general purpose-declaration applies.',
            ],
        ],
        [
            'page_slug' => 'china-medical-visa',
            'country_slug' => 'china',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'No dedicated medical-treatment visa category found. Indian citizens require a visa for China generally (standard categories such as "L" tourist / "F"/"M" business); no separate medical-purpose visa surfaced in correct-direction results',
            'visa_subclass_code' => null,
            'intro_html' => '<p>No dedicated medical-treatment visa category was found for China in correct-direction research — Indian citizens require a visa for China generally, through standard categories such as the "L" tourist visa or "F"/"M" business visas, with no separate medical-purpose visa confirmed.</p>',
            'typical_stay' => 'Not reliably confirmed for medical purpose specifically',
            'entry_type' => 'In-person submission at the Chinese Visa Application Service Centre, Embassy of China (New Delhi), or Consulates (Mumbai/Kolkata)',
            'processing_time_text' => 'General standard processing approximately 4 working days (not medical-specific; secondary source)',
            'validity_text' => 'Not reliably confirmed for medical purpose specifically',
            'application_method' => 'In-person submission at the Chinese Visa Application Service Centre, Embassy of China (New Delhi), or Consulates (Mumbai/Kolkata)',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'General (non-medical-specific) China visa fee per secondary source: approximately ₹2,900 single entry; approximately ₹8,800 one-year multiple entry — not confirmed applicable to any medical-purpose application',
            'application_centre' => 'Chinese Visa Application Service Centre',
            'authority_name' => 'Embassy of the People’s Republic of China, New Delhi (and Consulates in Mumbai, Kolkata)',
            'authority_url' => null,
            'eligibility_html' => '<p>No distinct medical-purpose eligibility criteria were found for China — Indian nationals seeking medical treatment would need to use one of the standard visa categories, requiring a passport valid 6+ months, proof of accommodation, itinerary, and financial statements.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Confirm Directly With the Chinese Embassy/Consulate</h4><p>No dedicated medical-purpose category was confirmed — recommend direct confirmation with the Chinese Embassy/Consulate in India regarding the most appropriate standard visa category for your treatment visit.</p><p>Our consultants can help you determine the best visa category for your China medical visit.</p>',
            'seo_title' => 'China Medical Treatment for Indians | No Dedicated Category Found',
            'meta_description' => 'Travelling to China for medical treatment? We disclose that no dedicated medical visa category was found, via VisaAgency.in.',
            'og_title' => 'China Medical Treatment for Indians — No Dedicated Category Found',
            'og_description' => 'Travelling to China for medical treatment? We disclose that no dedicated medical visa category was found, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport (6+ months validity)', 'mandatory'],
                ['Supporting Documents', 'Proof of accommodation, itinerary, financial statements', 'mandatory'],
            ],
            'steps' => [
                ['Confirm the Appropriate Standard Visa Category', 'Directly with the Chinese Embassy/Consulate.'],
                ['Apply In Person', 'At the Chinese Visa Application Service Centre.'],
            ],
            'faqs' => [
                ['Does China have a dedicated medical visa?', 'No dedicated category was confirmed — recommend direct confirmation with the Chinese Embassy/Consulate.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Embassy of the People’s Republic of China, New Delhi (and Consulates in Mumbai, Kolkata)',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Chinese-government source confirmed a medical-specific category — content found (eoibeijing.gov.in "Medical visa" page) was India’s own inbound medical visa info for Chinese nationals, filtered out as reverse-direction.',
            ],
        ],
        [
            'page_slug' => 'georgia-medical-visa',
            'country_slug' => 'georgia',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Secondary sources state Indians seeking medical treatment "should apply for a medical visa," but no official Georgian government source was retrieved confirming this as a distinct named category',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Secondary sources state Indians seeking medical treatment in Georgia "should apply for a medical visa," but no official Georgian government source confirmed this as a genuinely distinct named category — Georgia’s immigration framework is generally believed to use a unified e-Visa requiring purpose declaration, rather than a separately branded "medical visa."</p>',
            'typical_stay' => 'Not reliably confirmed in this research pass',
            'entry_type' => 'Likely Georgia’s e-Visa portal (evisa.mfa.gov.ge) — not directly confirmed',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Not reliably confirmed in this research pass',
            'application_method' => 'Likely Georgia’s e-Visa portal — not directly confirmed',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'Not reliably confirmed precisely',
            'authority_name' => 'Ministry of Foreign Affairs of Georgia',
            'authority_url' => null,
            'eligibility_html' => '<p>No distinct, officially-confirmed medical-visa eligibility criteria were found — secondary sources mention a "health condition form with medical history" as part of the application, but this is unverified and could be a generic/templated claim rather than Georgia-specific fact. Treat with caution.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Treat the "Medical Visa" Label With Caution</h4><p>No official source confirms a genuinely distinct Georgian medical-visa category — your medical travel is likely handled via the general e-Visa with purpose declaration. Verify directly before assuming a separate process.</p><p>Our consultants can help you confirm the current entry route for your Georgia medical visit.</p>',
            'seo_title' => 'Georgia Medical Treatment for Indians | Category Status Unclear',
            'meta_description' => 'Travelling to Georgia for medical treatment? We disclose unclear/unconfirmed information about a "medical visa" category, via VisaAgency.in.',
            'og_title' => 'Georgia Medical Treatment for Indians — Category Status Unclear',
            'og_description' => 'Travelling to Georgia for medical treatment? We disclose unclear/unconfirmed information about a "medical visa" category, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport (6+ months validity)', 'mandatory'],
                ['Supporting Documents', 'Photographs, flight tickets, accommodation details, travel insurance, financial proof', 'mandatory'],
            ],
            'steps' => [
                ['Verify the Actual Applicable Route', 'No official source confirms a genuinely distinct medical visa category.'],
                ['Apply via the General e-Visa', 'If no dedicated category applies.'],
            ],
            'faqs' => [
                ['Does Georgia have a dedicated medical visa?', 'This is unclear — secondary sources mention it but no official source confirms it as genuinely distinct from the general e-Visa.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Foreign Affairs of Georgia',
                'url' => null,
                'notes' => 'Researched via WebSearch; all sources were SEO/travel-insurance blogs (bajajfinserv, visago.dev, almahadtravels); no official Georgian government page retrieved. The "health condition form" claim is unverified.',
            ],
        ],
        [
            'page_slug' => 'israel-medical-visa',
            'country_slug' => 'israel',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Secondary sources vaguely mention "medical or business visa" options but do not confirm a distinct, separately named Israeli medical-treatment visa category; medical treatment is plausibly handled under Israel’s general visitor (B/2-type) visa with purpose declared',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Israel does not appear to maintain a distinct, separately named medical-treatment visa — secondary sources vaguely mention "medical or business visa" options, but medical travel is plausibly handled under Israel’s general visitor (B/2-type) visa with purpose declared, though this was not officially confirmed.</p>',
            'typical_stay' => 'Not reliably confirmed in this research pass',
            'entry_type' => 'Pre-departure application required — Indians are not eligible for visa-on-arrival in Israel',
            'processing_time_text' => 'General visa processing cited as 7–15 working days (not confirmed as medical-specific)',
            'validity_text' => 'Not reliably confirmed in this research pass',
            'application_method' => 'Application via Israeli Embassy/Consulate or its outsourced visa partner in India',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'Israeli Embassy/Consulate or outsourced visa partner',
            'authority_name' => 'Embassy of Israel, New Delhi',
            'authority_url' => null,
            'eligibility_html' => '<p>No distinct, officially-confirmed medical-visa eligibility criteria were found — the general visitor (B/2-type) visa, with medical purpose declared, is the plausible route, requiring a passport valid 6+ months beyond stay, valid international health/travel insurance, and a cover letter explaining the purpose of the visit.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>No Visa-on-Arrival — Apply in Advance</h4><p>Indians are not eligible for visa-on-arrival in Israel — apply via the Israeli Embassy/Consulate or its outsourced visa partner, with a clear cover letter explaining your medical purpose.</p><p>Our consultants can help you confirm the appropriate visa category for your Israel medical visit.</p>',
            'seo_title' => 'Israel Medical Treatment for Indians | General Visitor Visa Route',
            'meta_description' => 'Travelling to Israel for medical treatment? See the general visitor-visa route with medical purpose declared, via VisaAgency.in.',
            'og_title' => 'Israel Medical Treatment for Indians — General Visitor Visa Route',
            'og_description' => 'Travelling to Israel for medical treatment? See the general visitor-visa route with medical purpose declared, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport valid 6+ months beyond stay', 'mandatory'],
                ['Supporting Documents', 'Valid international health/travel insurance', 'mandatory'],
                ['Supporting Documents', 'Cover letter explaining purpose of visit', 'mandatory'],
            ],
            'steps' => [
                ['Prepare Your Cover Letter', 'Explaining your medical purpose.'],
                ['Apply In Advance', 'No visa-on-arrival for Indians.'],
            ],
            'faqs' => [
                ['Does Israel have a dedicated medical visa?', 'No official confirmation of a distinct category was found — medical purpose is plausibly declared on the general visitor visa.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Embassy of Israel, New Delhi',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official source was found — secondary sources only (reliancegeneral, bajajfinserv, btwvisas).',
            ],
        ],
        [
            'page_slug' => 'kazakhstan-medical-visa',
            'country_slug' => 'kazakhstan',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Dedicated — Kazakhstan reportedly has a distinct "Medical Treatment" e-Visa (category code "C12") specifically for treatment, consultations, or check-ups at a Kazakh clinic/hospital (secondary sources only; not officially confirmed)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Kazakhstan reportedly maintains a distinct "Medical Treatment" e-Visa category (code "C12") specifically for treatment, consultations or check-ups at a Kazakh clinic or hospital — found via secondary sources only, not officially confirmed, with a genuine conflict on stay duration disclosed below.</p>',
            'typical_stay' => 'CONFLICT — one source states the C12 visa allows up to 90 days (single entry, $80 fee); another states it is issued for up to 180 days (single or multiple entry)',
            'entry_type' => 'Online e-visa application (likely evisa.gov.kz, not directly confirmed)',
            'processing_time_text' => 'E-visas typically 3–5 business days (general figure, not medical-specific)',
            'validity_text' => 'CONFLICT — 90 days vs 180 days across sources, not reconciled',
            'application_method' => 'Online e-visa application (likely evisa.gov.kz, not directly confirmed)',
            'interview_required' => 'Not required (e-visa)',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: $80 USD (approximately ₹6,800) per one secondary source',
            'application_centre' => 'Online e-visa application',
            'authority_name' => 'e-visa authority of Kazakhstan',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals seeking treatment, consultations, or check-ups at a Kazakh clinic or hospital are reported to qualify for the C12 Medical Treatment e-Visa, implied by the purpose-specific nature of the visa (named clinic/hospital), though an explicit "invitation letter" requirement was not spelled out verbatim in retrieved text. Documents include a valid passport, visa application form, passport photos, travel itinerary and proof of accommodation.</p><p><strong>Stay-duration conflict disclosed:</strong> sources disagree on whether the C12 visa permits up to 90 days or up to 180 days — this was not reconciled from an official source in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Verify the Current Stay-Duration Limit</h4><p>Because sources genuinely conflict on whether the C12 Medical Treatment e-Visa allows 90 or 180 days, confirm the current figure via the official Kazakhstan e-visa portal before finalizing your treatment plans.</p><p>Our consultants can help you verify the current terms of the C12 Medical Treatment e-Visa.</p>',
            'seo_title' => 'Kazakhstan Medical Treatment e-Visa (C12) for Indians',
            'meta_description' => 'Travelling to Kazakhstan for medical treatment? See the C12 Medical Treatment e-Visa, with a disclosed stay-duration conflict, via VisaAgency.in.',
            'og_title' => 'Kazakhstan Medical Treatment e-Visa (C12) for Indians',
            'og_description' => 'Travelling to Kazakhstan for medical treatment? See the C12 Medical Treatment e-Visa, with a disclosed stay-duration conflict, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport', 'mandatory'],
                ['Basic Documents', 'Visa application form, passport photos', 'mandatory'],
                ['Supporting Documents', 'Travel itinerary, proof of accommodation', 'mandatory'],
            ],
            'steps' => [
                ['Apply for the C12 Medical Treatment e-Visa', 'Online, naming the treating Kazakh clinic/hospital.'],
                ['Pay the Fee', 'As researched, USD 80.'],
                ['Verify Your Permitted Stay Duration', 'Sources conflict on 90 vs 180 days — confirm directly.'],
            ],
            'faqs' => [
                ['Does Kazakhstan have a dedicated medical visa?', 'Yes — the C12 "Medical Treatment" e-Visa, reported via secondary sources only.'],
                ['How long can I stay?', 'Sources conflict (90 vs. 180 days) — confirm the current figure before travel.'],
            ],
            'fees' => [
                ['C12 Medical Treatment e-Visa', 'USD 80', 1, 'USD', 'As researched; approximately ₹6,800'],
            ],
            'source' => [
                'authority' => 'e-visa authority of Kazakhstan',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Kazakhstan government source was directly retrieved — secondary sources only (eurasia.travel, visarun.ai, blog.wego.com); a genuine stay-duration conflict is disclosed rather than resolved.',
            ],
        ],
        [
            'page_slug' => 'philippines-medical-visa',
            'country_slug' => 'philippines',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'A distinct "Medical Treatment Visa" (temporary-visitor sub-category) appears to exist for the Philippines, requiring proof of treatment necessity and approval from a registered Philippine hospital',
            'visa_subclass_code' => null,
            'intro_html' => '<p>The Philippines appears to maintain a distinct Medical Treatment Visa (a temporary-visitor sub-category), requiring proof of treatment necessity and approval from a registered Philippine hospital — moderate confidence, since the Philippine Embassy, New Delhi appeared among retrieved sources, suggesting at least partial official backing, though the exact descriptive text was a search-engine synthesis rather than a directly quoted official passage.</p>',
            'typical_stay' => 'Maximum stay of 59 days',
            'entry_type' => 'Philippine Embassy/Consulate (New Delhi) or Bureau of Immigration visa-waiver processing — not fully distinguished',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Maximum stay of 59 days',
            'application_method' => 'Philippine Embassy/Consulate (New Delhi) or Bureau of Immigration visa-waiver processing',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'Philippine Embassy/Consulate, New Delhi',
            'authority_name' => 'Philippine Bureau of Immigration / Department of Foreign Affairs (Philippine Embassy, New Delhi)',
            'authority_url' => 'https://newdelhipe.dfa.gov.ph',
            'eligibility_html' => '<p>Indian nationals seeking medical treatment in the Philippines require a letter of confirmation of treatment/appointment from a Philippine medical/wellness institution, plus proof of medical condition, proof of financial capacity, health insurance (if any), and proof of accommodation.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Companion/Escort Rules</h4><p>An escort/companion is authorized via a permission letter from the medical institution to escort the patient — handled through the hospital’s own permission letter rather than a separately named "attendant visa" product. For unaccompanied minors, a parental/guardian permission letter is required.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Obtain Your Hospital’s Confirmation Letter</h4><p>A letter of confirmation of treatment/appointment from a Philippine medical/wellness institution, plus proof of your medical condition, forms the core of your application.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Travelling With a Companion</h4><p>Your companion is authorized via a permission letter from the medical institution itself — there is no separately-named "attendant visa."</p><p>Our consultants can help you assemble the hospital confirmation and supporting financial documentation.</p>',
            'seo_title' => 'Philippines Medical Treatment Visa for Indians | 59-Day Stay Cap',
            'meta_description' => 'Travelling to the Philippines for medical treatment? See the Medical Treatment Visa and companion rules for Indian patients, via VisaAgency.in.',
            'og_title' => 'Philippines Medical Treatment Visa for Indians — 59-Day Stay Cap',
            'og_description' => 'Travelling to the Philippines for medical treatment? See the Medical Treatment Visa and companion rules for Indian patients, via VisaAgency.in.',
            'documents' => [
                ['Medical Documents', 'Letter of confirmation of treatment/appointment from a Philippine medical institution', 'mandatory'],
                ['Medical Documents', 'Proof of medical condition', 'mandatory'],
                ['Supporting Documents', 'Proof of financial capacity, health insurance, proof of accommodation', 'mandatory'],
                ['Companion Documents', 'Permission letter from the medical institution to escort the patient', 'conditional'],
                ['Companion Documents', 'Parental/guardian permission letter (unaccompanied minors)', 'conditional'],
            ],
            'steps' => [
                ['Obtain Your Hospital Confirmation Letter', 'From the treating Philippine medical institution.'],
                ['Gather Financial and Accommodation Proof', 'As supporting documentation.'],
                ['Apply at the Philippine Embassy/Consulate', 'New Delhi.'],
            ],
            'faqs' => [
                ['Does the Philippines have a dedicated medical visa?', 'Yes, apparently — a Medical Treatment Visa sub-category, with moderate-confidence confirmation via the Philippine Embassy.'],
                ['Can a companion travel with the patient?', 'Yes — via a permission letter from the medical institution, not a separately named "attendant visa."'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Philippine Bureau of Immigration / Department of Foreign Affairs (Philippine Embassy, New Delhi)',
                'url' => 'https://newdelhipe.dfa.gov.ph',
                'notes' => 'Researched via WebSearch; the Philippine Embassy New Delhi link surfaced in results, giving moderate confidence, though descriptive detail (escort permission letters, 59-day cap) came via search-engine synthesis rather than a directly quoted official passage — not independently re-verified by opening the source URL.',
            ],
        ],
        [
            'page_slug' => 'taiwan-medical-visa',
            'country_slug' => 'taiwan',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Unclear / CONFLICT — one secondary source claims Indian passport holders can enter Taiwan without a visa for up to 30–90 days, conflicting with the general understanding that Taiwan’s visa-free access for Indians is historically conditional; no distinct medical-visa product was identified either way',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Research found a genuine conflict regarding Taiwan’s entry requirement for Indian medical travellers: one secondary source claims unconditional visa-free entry for 30–90 days, which conflicts with general background understanding that Taiwan’s visa-free access for Indians is historically conditional (tied to holding a visa from certain third countries, or limited-time pilot programs). No distinct medical-visa product was identified under either reading, and no official Taiwan Bureau of Consular Affairs (boca.gov.tw) page was retrieved.</p>',
            'typical_stay' => 'Not reliably confirmed; CONFLICTING claims found',
            'entry_type' => 'Not reliably confirmed',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'Not reliably confirmed; CONFLICTING claims found',
            'application_method' => 'Not reliably confirmed',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'Taiwan Bureau of Consular Affairs / Taipei Economic and Cultural Center, New Delhi',
            'authority_name' => 'Taiwan Bureau of Consular Affairs / Taipei Economic and Cultural Center, New Delhi',
            'authority_url' => null,
            'eligibility_html' => '<p><strong>Important caution:</strong> the claim that Indian passport holders can enter Taiwan without a visa for 30–90 days appears unreliable and should NOT be relied upon without direct confirmation via boca.gov.tw — it conflicts with Taiwan’s generally conditional visa-free access for Indian nationals. No distinct medical-treatment visa product was identified under either interpretation.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Do Not Rely on the "Visa-Free 30–90 Days" Claim</h4><p>This claim was explicitly flagged as unreliable in research — verify your actual entry requirement directly with the Taipei Economic and Cultural Center before planning medical treatment travel.</p><p>Our consultants can help you verify the current, genuine entry requirement for your Taiwan medical visit.</p>',
            'seo_title' => 'Taiwan Medical Treatment for Indians | Entry Requirement Disputed',
            'meta_description' => 'Travelling to Taiwan for medical treatment? We disclose a genuine conflict and flag an unreliable "visa-free" claim, via VisaAgency.in.',
            'og_title' => 'Taiwan Medical Treatment for Indians — Entry Requirement Disputed',
            'og_description' => 'Travelling to Taiwan for medical treatment? We disclose a genuine conflict and flag an unreliable "visa-free" claim, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Do Not Rely on the Visa-Free Claim', 'Explicitly flagged as unreliable in this research.'],
                ['Verify Directly via boca.gov.tw', 'Or the Taipei Economic and Cultural Center.'],
            ],
            'faqs' => [
                ['Can Indians enter Taiwan visa-free for medical treatment?', 'One source claims this, but it is flagged as unreliable and conflicts with Taiwan’s generally conditional access for Indians — verify directly.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Taiwan Bureau of Consular Affairs / Taipei Economic and Cultural Center, New Delhi',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official source was retrieved, and the key secondary claim found is explicitly flagged as unreliable/oversimplified — do not publish the "visa-free 30-90 days" claim without official confirmation.',
            ],
        ],
        [
            'page_slug' => 'uzbekistan-medical-visa',
            'country_slug' => 'uzbekistan',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'No distinct named "medical visa" category confirmed; Uzbekistan requires a general e-Visa for Indian citizens, and medical travel appears to be handled under that general e-Visa with supporting medical documentation',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Uzbekistan has no distinct named medical-visa category — Indian citizens seeking medical treatment use the general e-Visa, supported by documentation from the treating clinic/hospital, rather than a separately branded medical-visa product.</p>',
            'typical_stay' => 'Not reliably confirmed specific to medical purpose',
            'entry_type' => 'Online e-Visa application (Uzbekistan e-visa portal)',
            'processing_time_text' => 'As researched: 3 business days (general e-Visa processing time, not medical-specific)',
            'validity_text' => 'Not reliably confirmed specific to medical purpose',
            'application_method' => 'Online e-Visa application',
            'interview_required' => 'Not required',
            'biometric_required' => 'Not required (e-visa)',
            'government_fee_text' => 'As researched: $20 USD for the e-Visa (general figure, not confirmed as medical-specific)',
            'application_centre' => 'Online e-Visa portal',
            'authority_name' => 'Ministry of Foreign Affairs of Uzbekistan',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals seeking medical treatment in Uzbekistan use the general e-Visa, requiring a valid passport (6+ months validity), proof of sufficient funds, a valid/genuine reason for visit, no criminal record, and travel medical insurance (recommended, not mandatory). Documentation from the treating clinic/hospital confirming the appointment and nature of treatment is referenced as relevant supporting material, though not stated as a formally mandatory e-Visa document.</p><p>This is immigration/travel-document guidance only, not medical advice.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Use the General e-Visa for Medical Travel</h4><p>Apply via the standard e-Visa process (USD 20, 3 business days), supporting your application with documentation from your treating Uzbek clinic/hospital.</p><p>Our consultants can help you prepare supporting medical documentation for your e-Visa application.</p>',
            'seo_title' => 'Uzbekistan Medical Treatment for Indians | Via the General e-Visa',
            'meta_description' => 'Travelling to Uzbekistan for medical treatment? See how the general e-Visa covers this for Indian nationals, via VisaAgency.in.',
            'og_title' => 'Uzbekistan Medical Treatment for Indians — Via the General e-Visa',
            'og_description' => 'Travelling to Uzbekistan for medical treatment? See how the general e-Visa covers this for Indian nationals, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (6+ months validity)', 'mandatory'],
                ['Supporting Documents', 'Proof of sufficient funds', 'mandatory'],
                ['Medical Documents', 'Documentation from treating clinic/hospital confirming appointment and treatment nature', 'conditional'],
                ['Supporting Documents', 'Travel medical insurance (recommended, not mandatory)', 'recommended'],
            ],
            'steps' => [
                ['Obtain Clinic/Hospital Documentation', 'Confirming your appointment and treatment.'],
                ['Apply for the General e-Visa', 'USD 20, processed in approximately 3 business days.'],
            ],
            'faqs' => [
                ['Does Uzbekistan have a dedicated medical visa?', 'No — medical travel is handled under the general e-Visa with supporting clinic/hospital documentation.'],
            ],
            'fees' => [
                ['e-Visa fee', 'USD 20', 1, 'USD', 'As researched; general figure, not confirmed medical-specific'],
            ],
            'source' => [
                'authority' => 'Ministry of Foreign Affairs of Uzbekistan',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Uzbekistan government source was directly retrieved — secondary sources only (bajajfinserv, airindia.com visa-info page, visago.dev); uzbekembassy.in discussed growing medical cooperation generally but contained no visa-procedure specifics.',
            ],
        ],
    ];
}
