<?php
/**
 * Phase 3 -- Extension Visa research for 17 of 33 Tier-B countries (expanding
 * Phase 2D Extension coverage); 8 countries are fully researched findings, 9
 * more (the Schengen set
 * czech-republic/denmark/finland/greece/hungary/norway/poland/portugal/sweden)
 * rest on the same genuine, citable EU Visa Code Article 33
 * exceptional-circumstances rule already used as precedent in the Tier-A
 * Schengen-six Extension Visa records -- not fabricated, not independently
 * verified per-country. 16 countries had zero findings and are left at generic
 * status, disclosed as a known gap. The strict governance distinction (visa
 * extension / extension of stay / residence permit / visa renewal / status
 * change / new visa application) is preserved per-record.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_tierb_extension(): array
{
    return [
        [
            'page_slug' => 'argentina-visa-extension',
            'country_slug' => 'argentina',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of Stay — "prórroga de permanencia," a single exceptional extension granted by Dirección Nacional de Migraciones (DNM), under the August 2025 resolution easing entry for Indian passport holders holding a valid US visa',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Argentina offers an extension-of-stay mechanism — not a new visa — for Indian nationals who entered visa-free using a valid US visa in lieu of an AVE/consular visa, for tourism purposes with an initial stay up to 90 days. The Dirección Nacional de Migraciones "may grant" one single extension of the same duration; a change of migratory category is explicitly prohibited for these entrants. This mechanism is specifically tied to the August 2025 bilateral easing and may not apply to Indians entering via an ordinary Argentine visa/AVE route.</p>',
            'typical_stay' => 'One single extension, same duration as the original stay (approximately 90 extra days); not described as repeatable',
            'entry_type' => 'In-country only, via the Dirección Nacional de Migraciones',
            'processing_time_text' => 'Not reliably confirmed in this research pass',
            'validity_text' => 'One single extension, same duration as original stay (not a new visa)',
            'application_method' => 'In-country application to the Dirección Nacional de Migraciones (migraciones.gob.ar)',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'Dirección Nacional de Migraciones (DNM)',
            'authority_name' => 'Dirección Nacional de Migraciones (DNM), Argentina',
            'authority_url' => 'https://www.migraciones.gob.ar',
            'eligibility_html' => '<p>This extension applies specifically to Indian nationals who entered Argentina visa-free using a valid US visa in lieu of an AVE/consular visa, for tourism, with an initial stay up to 90 days — part of an India-specific August 2025 resolution. DNM "may grant" one single extension of the same duration; changing migratory category during this process is explicitly prohibited.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>This Is an Extension of Stay, Not a New Visa</h4><p>The same 90-day authorized period is extended once — you cannot change your migratory category during this process, and this specific mechanism is tied to the August 2025 bilateral easing for US-visa holders.</p><p>Our consultants can help you confirm whether your entry route qualifies for this extension.</p>',
            'seo_title' => 'Argentina Visa Extension for Indians | Single Stay Extension',
            'meta_description' => 'Need more time in Argentina? See the single extension-of-stay mechanism for Indian nationals who entered via the US-visa route, via VisaAgency.in.',
            'og_title' => 'Argentina Visa Extension for Indians — Single Stay Extension',
            'og_description' => 'Need more time in Argentina? See the single extension-of-stay mechanism for Indian nationals who entered via the US-visa route, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Entry Route Qualifies', 'This mechanism applies specifically to the August 2025 US-visa-based entry easing.'],
                ['Apply In-Country to DNM', 'For the single, same-duration extension.'],
            ],
            'faqs' => [
                ['Can I extend my stay in Argentina?', 'Yes, once, for approximately 90 additional days, if you entered via the August 2025 US-visa-based easing for Indian nationals.'],
                ['Can I change my visa category during this process?', 'No — this is explicitly prohibited for this entry route.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Dirección Nacional de Migraciones (DNM), Argentina',
                'url' => 'https://www.migraciones.gob.ar',
                'notes' => 'Researched via WebSearch; Argentine MFA portals (eindi.cancilleria.gob.ar, cmrea.cancilleria.gob.ar) referenced the resolution; DNM’s own site not directly read; a law-firm blog was used for procedural detail.',
            ],
        ],
        [
            'page_slug' => 'austria-visa-extension',
            'country_slug' => 'austria',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a Schengen visa under Article 33, EU Visa Code (Regulation 810/2009) — administered nationally by the competent Fremdenpolizeibehörde/Landespolizeidirektion, available only under exceptional circumstances',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Austria’s extension mechanism is governed by Article 33 of the EU Visa Code — available only under exceptional circumstances (force majeure, humanitarian reasons, or serious personal reasons) that arose after visa issuance, with the purpose of stay unchanged. This is not a routine process, and the total Schengen stay still cannot exceed 90 days in any 180-day period.</p>',
            'typical_stay' => 'Not reliably confirmed exact; total Schengen stay capped at 90/180 days regardless',
            'entry_type' => 'In-country only, at the local Austrian aliens police authority',
            'processing_time_text' => 'Must apply before expiry; Austria-specific processing time not reliably confirmed',
            'validity_text' => 'Total Schengen stay cannot exceed 90 days in any 180-day period regardless of extension',
            'application_method' => 'In-country, at the local Austrian aliens/immigration police authority',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'CONFLICT — no Austria-specific figure confirmed; secondary sources (via Germany’s equivalent rule) cite free for force majeure/humanitarian, EUR 30 for "important personal reasons"/late entry, while other secondary sources cite EUR 160 as a generic "national visa extension" fee',
            'application_centre' => 'Austrian aliens/immigration police (Fremdenpolizeibehörde)',
            'authority_name' => 'Austrian aliens/immigration police (Fremdenpolizeibehörde), Federal Ministry of the Interior',
            'authority_url' => null,
            'eligibility_html' => '<p>New circumstances must have arisen after visa issuance, with the purpose of stay unchanged; grounds are limited to force majeure, humanitarian reasons, or serious personal reasons — this is not a routine extension process available on request.</p><p><strong>Fee conflict disclosed:</strong> no Austria-specific figure was confirmed; secondary sources cite EUR 30 (via Germany’s parallel rule) versus EUR 160 (generic national visa extension fee) — neither Austria-official.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — you must demonstrate force majeure, a humanitarian reason, or a serious personal reason that arose after your visa was issued.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Fee Uncertainty</h4><p>Reported fees conflict (EUR 30 vs EUR 160) — confirm the current figure with the local Austrian aliens police authority.</p><p>Our consultants can help you assess whether your situation genuinely qualifies as exceptional circumstances.</p>',
            'seo_title' => 'Austria Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Austrian Schengen visa? See why this is limited to exceptional circumstances, via VisaAgency.in.',
            'og_title' => 'Austria Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Austrian Schengen visa? See why this is limited to exceptional circumstances, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Force majeure, humanitarian, or serious personal reasons.'],
                ['Apply at the Local Aliens Police Authority', 'Before your current visa expires.'],
            ],
            'faqs' => [
                ['Can I extend my Austrian Schengen visa?', 'Only under exceptional circumstances — force majeure, humanitarian reasons, or serious personal reasons that arose after issuance.'],
                ['What is the fee?', 'Sources conflict (EUR 30 vs EUR 160); no Austria-specific figure is confirmed.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Austrian aliens/immigration police (Fremdenpolizeibehörde), Federal Ministry of the Interior',
                'url' => null,
                'notes' => 'Researched via WebSearch; no Austria-specific official government page was confirmed — relies on EU Visa Code (official EU law) plus secondary/commercial sources; a genuine fee conflict is disclosed.',
            ],
        ],
        [
            'page_slug' => 'azerbaijan-visa-extension',
            'country_slug' => 'azerbaijan',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of temporary stay via the State Migration Service of the Republic of Azerbaijan (not a separate "extension visa" product)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Azerbaijan offers an in-country extension of temporary stay, administered by the State Migration Service, for holders of the ASAN e-visa (single-entry tourist e-visa, valid 90 days from issue, permitting a 30-day stay). Stays beyond 30 days require additional documentation. A genuine conflict exists in sources about whether extension beyond 30 days is a true in-country extension or actually requires leaving and reapplying via embassy — this is disclosed rather than resolved.</p>',
            'typical_stay' => 'Not reliably confirmed exact; applies to extending the 30-day e-visa stay',
            'entry_type' => 'In-country, via the State Migration Service; hotels commonly file the extension on the traveller’s behalf',
            'processing_time_text' => 'Apply at least 3 working days before the current permit expires',
            'validity_text' => 'Extends beyond the initial 30-day e-visa stay',
            'application_method' => 'State Migration Service; hotels commonly file on the traveller’s behalf; for longer extensions the applicant must personally submit a signed application',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed in this research pass',
            'application_centre' => 'State Migration Service of the Republic of Azerbaijan',
            'authority_name' => 'State Migration Service of the Republic of Azerbaijan',
            'authority_url' => null,
            'eligibility_html' => '<p><strong>Conflict disclosed:</strong> sources disagree on whether "extension beyond 30 days" is a genuine in-country stay extension or actually requires leaving and reapplying via the embassy — one secondary source mentions "visiting the embassy" for extensions beyond 30 days, which may actually mean applying for a new visa rather than a true in-country extension. This was not resolved in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Early — At Least 3 Working Days Before Expiry</h4><p>Hotels commonly file simple extensions on your behalf; for longer extensions, you must personally submit a signed application.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Verify Whether a True Extension Exists Beyond 30 Days</h4><p>Sources genuinely conflict on whether this is possible in-country or requires leaving and reapplying — confirm directly with the State Migration Service.</p><p>Our consultants can help you verify the current extension process for your specific stay length.</p>',
            'seo_title' => 'Azerbaijan Visa Extension for Indians | State Migration Service Route',
            'meta_description' => 'Need more time in Azerbaijan? See the extension-of-stay process, with a disclosed conflict on extensions beyond 30 days, via VisaAgency.in.',
            'og_title' => 'Azerbaijan Visa Extension for Indians — State Migration Service Route',
            'og_description' => 'Need more time in Azerbaijan? See the extension-of-stay process, with a disclosed conflict on extensions beyond 30 days, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Apply at Least 3 Working Days Before Expiry', 'Hotels can often file simple extensions on your behalf.'],
                ['For Longer Extensions: Submit a Signed Application Personally', 'Via the State Migration Service.'],
            ],
            'faqs' => [
                ['Can I extend my Azerbaijan e-visa stay?', 'Yes, for stays up to 30 days via the State Migration Service; extension beyond 30 days has conflicting reports on whether it is a true in-country extension or requires leaving and reapplying.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'State Migration Service of the Republic of Azerbaijan',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official azerbaijan.gov.az page was directly read — relies entirely on secondary/commercial travel sources; a genuine conflict on the beyond-30-day mechanism is disclosed.',
            ],
        ],
        [
            'page_slug' => 'bangladesh-visa-extension',
            'country_slug' => 'bangladesh',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Visa extension under Bangladesh Visa Rules-2006, processed by the Department of Immigration and Passports (DIP) — CONFLICTED for the tourist category specifically',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Bangladesh has a visa-extension mechanism under the Visa Rules-2006, processed by the Department of Immigration and Passports — but research found a genuine conflict specifically for the tourist category: one source states tourist/visit visas are "non-extendable and non-convertible," while another states an extension of up to one month can be obtained from DIP. Business visas (a different category) can be extended up to 3 years total, max 6 months per visit — this is a separately confirmed, different rule.</p>',
            'typical_stay' => 'CONFLICT for tourist category — one source says non-extendable, another says up to one month; business visa (different category): up to 3 years total, max 6 months per visit',
            'entry_type' => 'In-country only, at the DIP head office, Agargaon, Dhaka',
            'processing_time_text' => 'Secondary sources suggest applying 4–8 weeks ahead of expiry; processing cited as 1–2 weeks',
            'validity_text' => 'CONFLICT for tourist category; business visa: up to 3 years total, max 6 months per visit',
            'application_method' => 'DIP head office, Agargaon, Dhaka, via prescribed Form under Visa Rules-2006; an official portal dip.gov.bd exists but an online extension workflow was not independently confirmed',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'BDT 50 cited by one secondary source for a Visit/Tourist visa extension; another secondary source says fees follow a "reciprocity principle" tied to what a Bangladeshi citizen would pay for a visa to the traveller’s home country — CONFLICT, neither confirmed on an official DIP fee table',
            'application_centre' => 'Department of Immigration and Passports (DIP), Agargaon, Dhaka',
            'authority_name' => 'Department of Immigration and Passports (DIP), Government of Bangladesh',
            'authority_url' => 'https://dip.gov.bd',
            'eligibility_html' => '<p><strong>Conflict disclosed:</strong> whether tourist/visit visas can be extended at all is genuinely disputed across sources — one states non-extendable, another describes a process for up to one month. This was not resolved in this research pass. Business visas are a separately-confirmed, different category, extendable up to 3 years total.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Verify Your Tourist Visa’s Extendability Directly</h4><p>Because sources genuinely conflict on whether tourist/visit visas can be extended at all, confirm your specific situation directly with the DIP before assuming either position.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Business Visa Is Different</h4><p>If you hold a Business visa instead, a separately-confirmed extension path exists, up to 3 years total.</p><p>Our consultants can help you verify your tourist visa’s extendability with the DIP directly.</p>',
            'seo_title' => 'Bangladesh Visa Extension for Indians | Conflicting Guidance Disclosed',
            'meta_description' => 'Need more time in Bangladesh? We disclose a genuine conflict on whether tourist visas can be extended at all, via VisaAgency.in.',
            'og_title' => 'Bangladesh Visa Extension for Indians — Conflicting Guidance Disclosed',
            'og_description' => 'Need more time in Bangladesh? We disclose a genuine conflict on whether tourist visas can be extended at all, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Verify Whether Your Visa Type Is Extendable', 'Sources conflict for the tourist category specifically.'],
                ['If Extendable: Apply at the DIP Head Office', 'Agargaon, Dhaka, 4–8 weeks ahead of expiry.'],
            ],
            'faqs' => [
                ['Can I extend my Bangladesh tourist visa?', 'Sources genuinely conflict — one says non-extendable, another describes a one-month extension process. Verify directly with the DIP.'],
                ['What about a Business visa?', 'A separately-confirmed extension path exists, up to 3 years total, max 6 months per visit.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Department of Immigration and Passports (DIP), Government of Bangladesh',
                'url' => 'https://dip.gov.bd',
                'notes' => 'Researched via WebSearch; no official DIP page was directly read/verified — relies on secondary sources (legalseba.com, visaprocessinfos.com, bajajfinserv.in); a genuine conflict on tourist-visa extendability is disclosed.',
            ],
        ],
        [
            'page_slug' => 'belgium-visa-extension',
            'country_slug' => 'belgium',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a Schengen (short-stay) visa under Article 33, EU Visa Code — administered by the Immigration Office (Office des Étrangers/Dienst Vreemdelingenzaken), available only in exceptional circumstances',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Belgium’s extension mechanism follows Article 33 of the EU Visa Code — available only in exceptional circumstances where new facts arise after visa issuance, and the total Schengen stay cannot exceed 90 days within any 180-day period. This is not a routine process.</p>',
            'typical_stay' => 'Not reliably confirmed exact; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, via the Belgian Immigration Office or local immigration/commune office',
            'processing_time_text' => 'Must apply before current authorization expires; secondary source cites ~2–4 weeks processing',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, via the Belgian Immigration Office (dofi.ibz.be) or local immigration/commune office',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'EUR 160 cited by secondary/commercial sources (axa-schengen.com, evisa-card.com) for a "national visa" extension under exceptional circumstances — NOT independently confirmed on an official Belgian government fee page',
            'application_centre' => 'Belgian Immigration Office (Office des Étrangers)',
            'authority_name' => 'Immigration Office / Office des Étrangers (Belgium)',
            'authority_url' => 'https://dofi.ibz.be',
            'eligibility_html' => '<p>Extension requires exceptional circumstances — new facts arising after visa issuance — and cannot exceed the Schengen 90/180-day cap. The official authority (dofi.ibz.be) was identified in search results, though its fee page was not directly loaded.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — you must demonstrate new facts that arose after your visa was issued.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Fee Not Officially Confirmed</h4><p>A EUR 160 figure appears in commercial sources but is not independently confirmed on an official Belgian government page — verify directly.</p><p>Our consultants can help you assess whether your situation qualifies as an exceptional circumstance.</p>',
            'seo_title' => 'Belgium Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Belgian Schengen visa? See why this is limited to exceptional circumstances, via VisaAgency.in.',
            'og_title' => 'Belgium Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Belgian Schengen visa? See why this is limited to exceptional circumstances, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'New facts arising after visa issuance.'],
                ['Apply at the Immigration Office', 'Or your local commune office, before your current authorization expires.'],
            ],
            'faqs' => [
                ['Can I extend my Belgian Schengen visa?', 'Only under exceptional circumstances; this is not a routine process.'],
                ['What is the fee?', 'EUR 160 is cited by commercial sources, not independently confirmed officially.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Immigration Office / Office des Étrangers (Belgium)',
                'url' => 'https://dofi.ibz.be',
                'notes' => 'Researched via WebSearch; official authority identified (dofi.ibz.be) but fee schedule not directly verified — procedural detail from secondary sources.',
            ],
        ],
        [
            'page_slug' => 'bhutan-visa-extension',
            'country_slug' => 'bhutan',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => '"Prolongation" of the Entry Permit, via the Department of Immigration — an extension of stay, not a new visa',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Bhutan offers a "prolongation" of the free Indian entry permit, applied for in person at an Immigration Office — this extends the existing permit’s validity rather than issuing a new visa. The commonly-issued initial permit is 7 days (some sources say up to 15 days); travellers wanting a longer stay must apply in person.</p>',
            'typical_stay' => 'Not reliably confirmed precisely for Indian nationals',
            'entry_type' => 'In-country only, at a Department of Immigration office (Thimphu or regional offices)',
            'processing_time_text' => 'Recommended to apply 3–5 working days before the permit expires; overstay penalty amount not reliably confirmed',
            'validity_text' => 'Extends the existing Entry Permit; exact maximum not reliably confirmed for Indian nationals',
            'application_method' => 'In person at the Department of Immigration office, Thimphu, or regional immigration offices',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'The Indian entry permit itself is free. One secondary source cites a "$40 one-time visa fee" plus "$100/night Sustainable Development Fee" for extending a trip — but this almost certainly describes the general foreign-tourist regime, NOT the India-specific regime, whose SDF is set much lower and separately; the actual India-specific extension fee is NOT FOUND, and is deliberately not carried forward as confirmed to avoid misapplying the general-tourist figure to Indian nationals',
            'application_centre' => 'Department of Immigration, Thimphu, or regional immigration offices',
            'authority_name' => 'Department of Immigration, Royal Government of Bhutan',
            'authority_url' => null,
            'eligibility_html' => '<p>Indian nationals holding the free entry permit can apply in person at an Immigration Office to prolong their stay beyond the initial permitted period — recommended 3–5 working days before the permit expires. Permit validity is cited inconsistently (7 vs. 15 days) across sources.</p><p><strong>Fee caution:</strong> general-tourist regime fee figures ($40 + $100/night SDF) found in research almost certainly do NOT apply to Indian nationals, who benefit from a separate, lower concessional regime — this is the single biggest risk of fabrication/misapplication identified for this country, and that figure is deliberately NOT presented as "the" fee here.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply In Person Before Your Permit Expires</h4><p>Visit a Department of Immigration office 3–5 working days before your current permit expires to prolong your stay.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Assume the General-Tourist Fee Applies to You</h4><p>Figures found in research (USD 40 + $100/night SDF) describe the general foreign-tourist regime, not the separate, lower Indian-national concessional regime — confirm your actual applicable fee directly.</p><p>Our consultants can help you confirm the current India-specific extension fee before you travel.</p>',
            'seo_title' => 'Bhutan Visa Extension for Indians | Entry Permit Prolongation',
            'meta_description' => 'Need more time in Bhutan? See the Entry Permit prolongation process, with an important fee caution for Indian nationals, via VisaAgency.in.',
            'og_title' => 'Bhutan Visa Extension for Indians — Entry Permit Prolongation',
            'og_description' => 'Need more time in Bhutan? See the Entry Permit prolongation process, with an important fee caution for Indian nationals, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Apply In Person at an Immigration Office', 'Thimphu or a regional office, 3–5 working days before expiry.'],
                ['Confirm Your Actual Applicable Fee', 'The general-tourist fee figures found in research likely do not apply to you.'],
            ],
            'faqs' => [
                ['Can I extend my Bhutan entry permit?', 'Yes — a "prolongation" is available in person at an Immigration Office.'],
                ['What fee applies to Indian nationals?', 'Not reliably confirmed — figures found in research describe the general-tourist regime, which is a different, higher-fee regime than the Indian-national concessional rate.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Department of Immigration, Royal Government of Bhutan',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official .gov.bt source was directly read — secondary/commercial travel sources only, with the general-tourist fee figure explicitly NOT carried forward as the India-specific fee, since it is understood to describe a different, non-Indian regime.',
            ],
        ],
        [
            'page_slug' => 'brazil-visa-extension',
            'country_slug' => 'brazil',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => '"Prorrogação de estada" (extension of stay) — the same authorized period extended in-country, not a new visa, processed by the Polícia Federal (Setor de Estrangeiros)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Brazil offers an "extension of stay" (prorrogação de estada), processed by the Polícia Federal — available to visa-exempt/tourist entrants, with the combined stay (initial plus extension) capped at 180 days per 365-day period (typically structured as 90+90 days).</p>',
            'typical_stay' => 'Maximum combined stay of 180 days in any 365-day period, after which the traveller must leave Brazil',
            'entry_type' => 'In-country only, at the Polícia Federal office (Setor de Estrangeiros) nearest the place of stay',
            'processing_time_text' => 'Recommended to apply 2–3 weeks before current authorized stay expires',
            'validity_text' => 'Maximum combined stay of 180 days in any 365-day period',
            'application_method' => 'In-country, at the Polícia Federal office (Setor de Estrangeiros); payment via a GRU (Guia de Recolhimento da União) slip paid at Banco do Brasil',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'R$67 cited by one secondary source as an example figure, explicitly flagged by that same source as subject to change — UNCONFIRMED against any official Polícia Federal fee table, treat as approximate only',
            'application_centre' => 'Polícia Federal (Setor de Estrangeiros)',
            'authority_name' => 'Polícia Federal (Federal Police), Brazil — Setor de Estrangeiros',
            'authority_url' => 'https://www.gov.br/pf',
            'eligibility_html' => '<p>Visa-exempt/tourist entrants can apply for the extension, showing an onward/return ticket and sufficient funds. Whether this described visa-exempt/tourist process applies identically to Indian nationals who typically require an e-visa for Brazil, or whether the e-visa has its own separate extension rule, was not resolved in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Verify How This Applies to e-Visa Holders</h4><p>Since Indian nationals typically require an e-visa for Brazil (rather than being visa-exempt), confirm directly with the Polícia Federal whether this same extension process applies to you, or whether a different rule governs e-visa extensions.</p><p>Our consultants can help you verify your specific extension pathway as an Indian e-visa holder.</p>',
            'seo_title' => 'Brazil Visa Extension for Indians | Extension of Stay Process',
            'meta_description' => 'Need more time in Brazil? See the prorrogação de estada extension process, with a noted gap for Indian e-visa holders, via VisaAgency.in.',
            'og_title' => 'Brazil Visa Extension for Indians — Extension of Stay Process',
            'og_description' => 'Need more time in Brazil? See the prorrogação de estada extension process, with a noted gap for Indian e-visa holders, via VisaAgency.in.',
            'documents' => [
                ['Supporting Documents', 'Onward/return ticket, sufficient funds proof', 'mandatory'],
            ],
            'steps' => [
                ['Verify Your Applicable Process as an e-Visa Holder', 'Since Indians typically hold e-visas rather than being visa-exempt.'],
                ['Apply at the Polícia Federal', 'At least 2–3 weeks before your current stay expires.'],
                ['Pay via the GRU Slip', 'At Banco do Brasil.'],
            ],
            'faqs' => [
                ['Can I extend my stay in Brazil?', 'A visa-exempt/tourist extension process exists, up to a 180-day combined cap; whether this applies identically to Indian e-visa holders is unconfirmed.'],
            ],
            'fees' => [
                ['Extension of stay (estimated)', 'R$67', 1, 'BRL', 'As researched; explicitly flagged by its source as subject to change, unconfirmed officially'],
            ],
            'source' => [
                'authority' => 'Polícia Federal (Federal Police), Brazil — Setor de Estrangeiros',
                'url' => 'https://www.gov.br/pf',
                'notes' => 'Researched via WebSearch; partially official (gov.br/pf domain appeared for a related dispatch document) but extension fee schedule not directly read — most procedural detail from secondary sources (noonsite.com, expat.com, visamind.com).',
            ],
        ],
        [
            'page_slug' => 'cambodia-visa-extension',
            'country_slug' => 'cambodia',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => '"Visa extension"/"E-visa extension," processed at the (National Police) Immigration Department/Centre',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Cambodia offers a visa extension / e-visa extension process, available to e-visa and ordinary tourist-visa holders, administered at the National Police Immigration Centre/General Department of Immigration — tourist e-visa extension is capped at an additional 30 days.</p>',
            'typical_stay' => 'Tourist e-visa extension capped at an additional 30 days',
            'entry_type' => 'In-country, at the National Police Immigration Centre/General Department of Immigration (Phnom Penh); in practice often handled via licensed travel-agent intermediaries',
            'processing_time_text' => 'Processing approximately 2 days per secondary sources; days-before-expiry requirement and exact current overstay-fine rate not reliably confirmed',
            'validity_text' => 'Capped at 30 additional days; whether a further re-extension is possible is not reliably confirmed',
            'application_method' => 'National Police Immigration Centre/General Department of Immigration (Phnom Penh); in practice often handled via licensed travel-agent intermediaries',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'USD 25 cited for the e-visa extension processing fee — secondary-sourced, not verified against an official General Department of Immigration fee table',
            'application_centre' => 'National Police Immigration Centre/General Department of Immigration, Phnom Penh',
            'authority_name' => 'General Department of Immigration, Ministry of Interior, Kingdom of Cambodia',
            'authority_url' => null,
            'eligibility_html' => '<p>E-visa and ordinary tourist-visa holders can extend their stay by up to 30 additional days — Cambodia is known to charge a daily overstay fine, though the current rate was not confirmed in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Through Immigration or a Travel Agent</h4><p>As researched, the fee is approximately USD 25, with processing taking around 2 days — many travellers use licensed travel-agent intermediaries in practice.</p><p>Our consultants can help you arrange your extension through the appropriate channel.</p>',
            'seo_title' => 'Cambodia Visa Extension for Indians | 30-Day Extension',
            'meta_description' => 'Need more time in Cambodia? See the e-visa extension process, capped at 30 additional days, via VisaAgency.in.',
            'og_title' => 'Cambodia Visa Extension for Indians — 30-Day Extension',
            'og_description' => 'Need more time in Cambodia? See the e-visa extension process, capped at 30 additional days, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Apply at the Immigration Centre', 'Phnom Penh, or via a licensed travel-agent intermediary.'],
                ['Pay the Fee', 'As researched, approximately USD 25.'],
                ['Receive Your 30-Day Extension', 'Processing takes about 2 days.'],
            ],
            'faqs' => [
                ['Can I extend my Cambodia e-visa?', 'Yes, by up to 30 additional days, via the National Police Immigration Centre.'],
                ['What is the fee?', 'As researched, approximately USD 25.'],
            ],
            'fees' => [
                ['E-visa extension', 'USD 25', 1, 'USD', 'As researched; secondary-sourced'],
            ],
            'source' => [
                'authority' => 'General Department of Immigration, Ministry of Interior, Kingdom of Cambodia',
                'url' => null,
                'notes' => 'Researched via WebSearch; no official Cambodian government page was directly read — relies on secondary/commercial travel sources (bankbazaar.com, sbnri.com, akbartravels.com).',
            ],
        ],
        [
            'page_slug' => 'czech-republic-visa-extension',
            'country_slug' => 'czech-republic',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>The Czech Republic, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances (force majeure, humanitarian reasons, or serious personal reasons), not as a routine process. A Czech MFA page addressing "visa extension" was identified in research but not independently opened/read for Czech-specific procedural detail.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely the Foreign Police of the Czech Republic under the Ministry of Interior (not independently confirmed)',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely the Foreign Police under the Ministry of Interior (not independently confirmed this session)',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific; general Schengen figures are illustrative only, not Czech-confirmed',
            'application_centre' => 'Likely the Foreign Police of the Czech Republic (not independently confirmed)',
            'authority_name' => 'Czech Ministry of Foreign Affairs (MZV)',
            'authority_url' => 'https://mzv.gov.cz',
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. A Czech MFA page on "visa extension" was identified in search results but not opened/read in detail in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Czech-specific application process if your situation qualifies.</p>',
            'seo_title' => 'Czech Republic Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Czech Schengen visa? See the general EU exceptional-circumstances rule as applied in Czechia, via VisaAgency.in.',
            'og_title' => 'Czech Republic Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Czech Schengen visa? See the general EU exceptional-circumstances rule as applied in Czechia, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Czech Authority', 'Likely the Foreign Police under the Ministry of Interior.'],
            ],
            'faqs' => [
                ['Can I extend my Czech Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Czech Ministry of Foreign Affairs (MZV)',
                'url' => 'https://mzv.gov.cz',
                'notes' => 'Researched via WebSearch; a Czech MFA page on visa extension was identified in search listings but not opened/read in detail — this entry rests on the general EU Visa Code rule, not independently verified for Czechia.',
            ],
        ],
        [
            'page_slug' => 'denmark-visa-extension',
            'country_slug' => 'denmark',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Denmark, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Denmark-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely SIRI (Danish Agency for International Recruitment and Integration), not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely SIRI, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely SIRI (not independently confirmed)',
            'authority_name' => 'Likely SIRI (Danish Agency for International Recruitment and Integration)',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Denmark-specific source was consulted beyond the general EU rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Danish-specific application process if your situation qualifies.</p>',
            'seo_title' => 'Denmark Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Danish Schengen visa? See the general EU exceptional-circumstances rule as applied in Denmark, via VisaAgency.in.',
            'og_title' => 'Denmark Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Danish Schengen visa? See the general EU exceptional-circumstances rule as applied in Denmark, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Danish Authority', 'Likely SIRI.'],
            ],
            'faqs' => [
                ['Can I extend my Danish Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely SIRI (Danish Agency for International Recruitment and Integration)',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU Visa Code rule only, with no Denmark-specific source consulted.',
            ],
        ],
        [
            'page_slug' => 'finland-visa-extension',
            'country_slug' => 'finland',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Finland, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Finland-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely the Finnish Immigration Service (Migri), not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely Migri, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely Finnish Immigration Service (Migri), not independently confirmed',
            'authority_name' => 'Likely Finnish Immigration Service (Migri)',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Finland-specific source was consulted beyond the general EU rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Finnish-specific application process if your situation qualifies.</p>',
            'seo_title' => 'Finland Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Finnish Schengen visa? See the general EU exceptional-circumstances rule as applied in Finland, via VisaAgency.in.',
            'og_title' => 'Finland Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Finnish Schengen visa? See the general EU exceptional-circumstances rule as applied in Finland, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Finnish Authority', 'Likely Migri.'],
            ],
            'faqs' => [
                ['Can I extend my Finnish Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely Finnish Immigration Service (Migri)',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU Visa Code rule only, with no Finland-specific source consulted.',
            ],
        ],
        [
            'page_slug' => 'greece-visa-extension',
            'country_slug' => 'greece',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Greece, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Greece-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely the Greek Ministry of Migration and Asylum / local Aliens and Immigration Directorate, not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely the Greek Ministry of Migration and Asylum, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely Greek Ministry of Migration and Asylum, not independently confirmed',
            'authority_name' => 'Likely Greek Ministry of Migration and Asylum',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Greece-specific source was consulted beyond the general EU rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Greek-specific application process if your situation qualifies.</p>',
            'seo_title' => 'Greece Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Greek Schengen visa? See the general EU exceptional-circumstances rule as applied in Greece, via VisaAgency.in.',
            'og_title' => 'Greece Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Greek Schengen visa? See the general EU exceptional-circumstances rule as applied in Greece, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Greek Authority', 'Likely the Greek Ministry of Migration and Asylum.'],
            ],
            'faqs' => [
                ['Can I extend my Greek Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely Greek Ministry of Migration and Asylum',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU Visa Code rule only, with no Greece-specific source consulted.',
            ],
        ],
        [
            'page_slug' => 'hungary-visa-extension',
            'country_slug' => 'hungary',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Hungary, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Hungary-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely the National Directorate-General for Aliens Policing, not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely the National Directorate-General for Aliens Policing, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely National Directorate-General for Aliens Policing, not independently confirmed',
            'authority_name' => 'Likely National Directorate-General for Aliens Policing',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Hungary-specific source was consulted beyond the general EU rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Hungarian-specific application process if your situation qualifies.</p>',
            'seo_title' => 'Hungary Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Hungarian Schengen visa? See the general EU exceptional-circumstances rule as applied in Hungary, via VisaAgency.in.',
            'og_title' => 'Hungary Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Hungarian Schengen visa? See the general EU exceptional-circumstances rule as applied in Hungary, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Hungarian Authority', 'Likely the National Directorate-General for Aliens Policing.'],
            ],
            'faqs' => [
                ['Can I extend my Hungarian Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely National Directorate-General for Aliens Policing',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU Visa Code rule only, with no Hungary-specific source consulted.',
            ],
        ],
        [
            'page_slug' => 'norway-visa-extension',
            'country_slug' => 'norway',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only (Norway is Schengen-associated though not EU)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Norway, as a Schengen-associated state (though not EU), applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Norway-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely the Norwegian Directorate of Immigration (UDI), not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely UDI, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely Norwegian Directorate of Immigration (UDI), not independently confirmed',
            'authority_name' => 'Likely Norwegian Directorate of Immigration (UDI)',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU/Schengen-associated Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Norway-specific source was consulted beyond the general rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general Schengen rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Norwegian-specific application process if your situation qualifies.</p>',
            'seo_title' => 'Norway Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Norwegian Schengen visa? See the general exceptional-circumstances rule as applied in Norway, via VisaAgency.in.',
            'og_title' => 'Norway Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Norwegian Schengen visa? See the general exceptional-circumstances rule as applied in Norway, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general Schengen rule.'],
                ['Apply Through the Appropriate Norwegian Authority', 'Likely UDI.'],
            ],
            'faqs' => [
                ['Can I extend my Norwegian Schengen visa?', 'Only under exceptional circumstances, per the general Schengen rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely Norwegian Directorate of Immigration (UDI)',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU/Schengen-associated rule only, with no Norway-specific source consulted.',
            ],
        ],
        [
            'page_slug' => 'poland-visa-extension',
            'country_slug' => 'poland',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a Schengen visa — a Polish regional voivodeship office page was identified, but not opened/read in detail',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Poland, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances. A Polish source (a regional voivodeship office page) titled "extension of a schengen visa" appeared in search results but was not opened/read in detail in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely the regional Voivodeship Office (Urząd Wojewódzki) — suggested by the source found, but not independently confirmed in detail',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely the regional Voivodeship Office, not independently confirmed in detail',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely regional Voivodeship Office (suggested, unconfirmed)',
            'authority_name' => 'Likely regional Voivodeship Office (Urząd Wojewódzki)',
            'authority_url' => 'https://cudzoziemiec.bydgoszcz.pl',
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds. A Polish regional voivodeship office page (cudzoziemiec.bydgoszcz.pl) titled "extension of a schengen visa" was located in search results — only a page title was seen, not its content, so treat this as a lead rather than a confirmed finding.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you follow up on the regional Voivodeship Office lead found in research for Polish-specific detail.</p>',
            'seo_title' => 'Poland Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Polish Schengen visa? See the general EU exceptional-circumstances rule and a regional-office lead, via VisaAgency.in.',
            'og_title' => 'Poland Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Polish Schengen visa? See the general EU exceptional-circumstances rule and a regional-office lead, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Follow Up on the Regional Voivodeship Office Lead', 'Found in research but not independently verified in detail.'],
            ],
            'faqs' => [
                ['Can I extend my Polish Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely regional Voivodeship Office (Urząd Wojewódzki)',
                'url' => 'https://cudzoziemiec.bydgoszcz.pl',
                'notes' => 'Researched via WebSearch; a regional Polish office page was located in search listing but not opened/read — treat as a lead, not a confirmed finding; general EU Visa Code rule is the basis for this entry.',
            ],
        ],
        [
            'page_slug' => 'portugal-visa-extension',
            'country_slug' => 'portugal',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Portugal, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Portugal-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely AIMA (Agência para a Integração, Migrações e Asilo, which replaced SEF), not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely AIMA, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely AIMA, not independently confirmed',
            'authority_name' => 'Likely AIMA (Agência para a Integração, Migrações e Asilo)',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Portugal-specific source was consulted beyond the general EU rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Portuguese-specific application process (likely via AIMA) if your situation qualifies.</p>',
            'seo_title' => 'Portugal Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Portuguese Schengen visa? See the general EU exceptional-circumstances rule as applied in Portugal, via VisaAgency.in.',
            'og_title' => 'Portugal Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Portuguese Schengen visa? See the general EU exceptional-circumstances rule as applied in Portugal, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Portuguese Authority', 'Likely AIMA.'],
            ],
            'faqs' => [
                ['Can I extend my Portuguese Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely AIMA (Agência para a Integração, Migrações e Asilo)',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU Visa Code rule only, with no Portugal-specific source consulted.',
            ],
        ],
        [
            'page_slug' => 'sweden-visa-extension',
            'country_slug' => 'sweden',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Extension of a short-stay (Schengen) visa under EU Visa Code Article 33 — exceptional circumstances only',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Sweden, as a Schengen member, applies the general EU Visa Code Article 33 rule — extension is possible only under exceptional circumstances, not as a routine process, with Sweden-specific procedural detail not independently confirmed in this research pass.</p>',
            'typical_stay' => 'Not reliably confirmed country-specific; total Schengen stay capped at 90 days within any 180-day period',
            'entry_type' => 'In-country, likely Migrationsverket (the Swedish Migration Agency), not independently confirmed',
            'processing_time_text' => 'Not reliably confirmed country-specific',
            'validity_text' => 'Total Schengen stay capped at 90 days within any 180-day period',
            'application_method' => 'In-country, likely Migrationsverket, not independently confirmed this session',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed country-specific',
            'application_centre' => 'Likely Migrationsverket, not independently confirmed',
            'authority_name' => 'Likely Migrationsverket (Swedish Migration Agency)',
            'authority_url' => null,
            'eligibility_html' => '<p>Extension is limited to the general EU Visa Code exceptional-circumstances grounds — force majeure, humanitarian, or serious personal reasons. No Sweden-specific source was consulted beyond the general EU rule in this research pass.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Exceptional Circumstances Only</h4><p>This is not a routine process — the general EU Visa Code rule applies, requiring genuinely exceptional circumstances.</p><p>Our consultants can help you confirm the Swedish-specific application process (likely via Migrationsverket) if your situation qualifies.</p>',
            'seo_title' => 'Sweden Visa Extension for Indians | Exceptional Circumstances Only',
            'meta_description' => 'Hoping to extend your Swedish Schengen visa? See the general EU exceptional-circumstances rule as applied in Sweden, via VisaAgency.in.',
            'og_title' => 'Sweden Visa Extension for Indians — Exceptional Circumstances Only',
            'og_description' => 'Hoping to extend your Swedish Schengen visa? See the general EU exceptional-circumstances rule as applied in Sweden, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Circumstances Are Genuinely Exceptional', 'Per the general EU Visa Code rule.'],
                ['Apply Through the Appropriate Swedish Authority', 'Likely Migrationsverket.'],
            ],
            'faqs' => [
                ['Can I extend my Swedish Schengen visa?', 'Only under exceptional circumstances, per the general EU Visa Code Article 33 rule.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Likely Migrationsverket (Swedish Migration Agency)',
                'url' => null,
                'notes' => 'Researched via WebSearch; country-specific research was not completed this session — this entry rests on the general EU Visa Code rule only, with no Sweden-specific source consulted.',
            ],
        ],
    ];
}
