<?php
/**
 * Phase 3A -- Crew Visa gap-closure research for 6 of the 8 Tier-B cells that
 * remained generic after Phase 3. 2 cells (morocco, uzbekistan) still had zero
 * evidence and remain generic. Preserves the Russia case-split (airline crew
 * visa-free under a bilateral reciprocal pact; seafarers require a visa with
 * seaman's-contract documentation) established during research.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_phase3a_crew(): array
{
    return [
        [
            'page_slug' => 'myanmar-crew-visa',
            'country_slug' => 'myanmar',
            'category_slug' => 'crew-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Crew Visa (Visa on Arrival), via Myanmar immigration at designated international airports',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Myanmar issues a dedicated Crew Visa on arrival at Yangon, Mandalay and Nay Pyi Taw International Airports, available to ordinary and official passport holders. Airline crew need an invitation/recommendation letter from the local airline, plus permission/recognition from the relevant Myanmar Ministry.</p>',
            'typical_stay' => 'Up to 90 days, extendable',
            'entry_type' => 'Visa on Arrival at Yangon, Mandalay, or Nay Pyi Taw International Airport',
            'processing_time_text' => 'Processed on arrival',
            'validity_text' => 'Up to 90 days, extendable',
            'application_method' => 'On arrival, at designated international airports',
            'interview_required' => 'Not required — a documentary visa-on-arrival process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'India-specific: Rs. 3,500 (single entry, 90 days); Rs. 14,000 (multiple entry, 3 months)',
            'application_centre' => 'Yangon, Mandalay or Nay Pyi Taw International Airport immigration counter',
            'authority_name' => 'Consulate-General of the Republic of the Union of Myanmar / Myanmar Embassy network',
            'authority_url' => 'https://myanmarcgla.org/index.php/crew-visa',
            'eligibility_html' => '<p>Eligible applicants include ordinary and official passport holders. Required documents include a passport valid 6+ months with 3+ blank visa pages, 2 recent 2x2-inch photos, and a copy of the flight schedule/itinerary showing a round trip. Airline crew additionally need an invitation letter from the local airline (or recommendation for employment as a current crew member) and permission/recognition from the relevant Myanmar Ministry.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>India-Specific Fees Confirmed</h4><p>Single-entry Crew Visa: Rs. 3,500 for 90 days. Multiple-entry: Rs. 14,000 for 3 months.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Bring Your Airline\'s Invitation Letter</h4><p>Along with Ministry recognition documentation for the employing airline.</p><p>Our consultants can help you confirm the current documentary checklist for your specific crew role.</p>',
            'seo_title' => 'Myanmar Crew Visa for Indians | Visa on Arrival',
            'meta_description' => 'Working as airline crew to Myanmar? See the Crew Visa on Arrival process and India-specific fees, via VisaAgency.in.',
            'og_title' => 'Myanmar Crew Visa for Indians — Visa on Arrival',
            'og_description' => 'Working as airline crew to Myanmar? See the Crew Visa on Arrival process and India-specific fees, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport valid 6+ months with 3+ blank visa pages', 'mandatory'],
                ['Basic Documents', '2 recent photos, 2x2 inch, white background', 'mandatory'],
                ['Travel Documents', 'Copy of flight schedule/itinerary (round trip)', 'mandatory'],
                ['Supporting Documents', 'Invitation letter from the local airline (airline crew)', 'mandatory'],
                ['Supporting Documents', 'Ministry recognition of the employing airline', 'mandatory'],
            ],
            'steps' => [
                ['Prepare Airline Documentation', 'Invitation letter and Ministry recognition for your employing airline.'],
                ['Arrive at a Designated International Airport', 'Yangon, Mandalay, or Nay Pyi Taw.'],
                ['Obtain Your Crew Visa on Arrival', 'Pay the applicable India-specific fee.'],
            ],
            'faqs' => [
                ['What does a Myanmar Crew Visa cost for Indians?', 'Rs. 3,500 for single entry (90 days), or Rs. 14,000 for multiple entry (3 months).'],
                ['Where is it issued?', 'On arrival at Yangon, Mandalay, or Nay Pyi Taw International Airport.'],
            ],
            'fees' => [
                ['Crew Visa (single entry, 90 days)', 'Rs. 3,500', 1, 'INR', 'India-specific fee, as researched'],
                ['Crew Visa (multiple entry, 3 months)', 'Rs. 14,000', 1, 'INR', 'India-specific fee, as researched'],
            ],
            'source' => [
                'authority' => 'Consulate-General of the Republic of the Union of Myanmar / Myanmar Embassy network',
                'url' => 'https://myanmarcgla.org/index.php/crew-visa',
                'notes' => 'Phase 3A research: official Myanmar consular mission pages confirm the Crew Visa on Arrival process, documentation and India-specific fees. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'philippines-crew-visa',
            'country_slug' => 'philippines',
            'category_slug' => 'crew-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => '9(C) Seaman and Crew Members Visa',
            'visa_subclass_code' => '9(C)',
            'intro_html' => '<p>Foreign seafarers signed on to a vessel arriving at a Philippine port from outside Philippine territory are eligible for a non-immigrant 9(C) visa — issued either to an individual crew member or as a single crew-list visa covering all foreign crew of the arriving vessel.</p>',
            'typical_stay' => 'Tied to the vessel\'s stay/the employment contract; exact cap not independently confirmed',
            'entry_type' => 'Philippine Embassy/Consulate General in the applicant\'s country of origin or place of legal residence',
            'processing_time_text' => '5 working days following the embassy\'s acceptance of complete documentary requirements',
            'validity_text' => 'Tied to the vessel/employment arrangement',
            'application_method' => 'Via the Philippine Embassy/Consulate General serving the applicant\'s country of origin or legal residence',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Philippine Embassy/Consulate General, country of origin or legal residence',
            'authority_name' => 'Philippine Department of Foreign Affairs (dfa.gov.ph)',
            'authority_url' => 'https://guangzhoupcg.dfa.gov.ph/en/consular-services/visa-services/visa-general-information/9-c-seaman-and-crew-members-visa',
            'eligibility_html' => '<p>Required documents include a passport valid at least 6 months beyond the intended stay/trip completion, a completed Visa Application Form No. 2, one recent passport-style photograph, the applicant\'s Seaman\'s Book, and a letter from the employer or manning agency confirming the vessel and the Philippine port of boarding.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Application Venue</h4><p>Indian nationals should apply at the Philippine Embassy/Consulate General in India (their country of origin/legal residence) — some overseas posts have specific routing rules for nationals without local residence status, so confirm the correct venue for your situation.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Through the Philippine Mission in India</h4><p>As your country of origin/legal residence, this is your standard application venue.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Bring Your Seaman\'s Book and Employer Letter</h4><p>Confirming your vessel assignment and Philippine port of boarding.</p><p>Our consultants can help you confirm the current documentary checklist with the Philippine mission in India.</p>',
            'seo_title' => 'Philippines Crew Visa for Indians | 9(C) Seaman and Crew Visa',
            'meta_description' => 'Joining a vessel at a Philippine port? See the 9(C) Seaman and Crew Members Visa requirements for Indian seafarers, via VisaAgency.in.',
            'og_title' => 'Philippines Crew Visa for Indians — 9(C) Seaman and Crew Visa',
            'og_description' => 'Joining a vessel at a Philippine port? See the 9(C) Seaman and Crew Members Visa requirements for Indian seafarers, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport valid 6+ months beyond stay/trip completion', 'mandatory'],
                ['Basic Documents', 'Visa Application Form No. 2', 'mandatory'],
                ['Basic Documents', 'Recent photograph, 3.5cm x 4.5cm', 'mandatory'],
                ['Supporting Documents', 'Seaman\'s Book', 'mandatory'],
                ['Supporting Documents', 'Employer/manning-agency letter confirming vessel and port of boarding', 'mandatory'],
            ],
            'steps' => [
                ['Gather Your Seafarer Documentation', 'Seaman\'s Book and employer/manning-agency letter.'],
                ['Apply at the Philippine Mission in India', 'Your country of origin/legal residence.'],
                ['Receive Your Visa', '5 working days after complete documents are accepted.'],
            ],
            'faqs' => [
                ['What is the 9(C) visa?', 'The Philippines\' non-immigrant Seaman and Crew Members visa for foreign seafarers joining a vessel at a Philippine port.'],
                ['How long does processing take?', '5 working days from acceptance of complete documents.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Philippine Department of Foreign Affairs (dfa.gov.ph)',
                'url' => 'https://guangzhoupcg.dfa.gov.ph/en/consular-services/visa-services/visa-general-information/9-c-seaman-and-crew-members-visa',
                'notes' => 'Phase 3A research: official dfa.gov.ph consular pages (multiple missions) directly confirm the 9(C) visa process and documentation. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'russia-crew-visa',
            'country_slug' => 'russia',
            'category_slug' => 'crew-visa',
            'content_status' => 'researched',
            'biometric_status' => 'conditional',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Airline crew: visa-free entry under the India-Russia bilateral reciprocal agreement. Seafarers: a seafarer/crew visa is required, with seaman\'s-contract documentation',
            'visa_subclass_code' => null,
            'intro_html' => '<p>India and Russia maintain a bilateral agreement granting visa-free entry, stay and exit to the crew of chartered and scheduled flights of each country\'s designated airlines, on a reciprocal basis. This does NOT extend to maritime crew: Indian seafarers still require a Russian visa, documented with a seaman\'s contract and national seaman\'s certificate.</p>',
            'typical_stay' => 'Airline crew: governed by the reciprocal bilateral agreement, tied to flight duty. Seafarers: governed by the visa and seaman\'s contract terms',
            'entry_type' => 'Airline crew: visa-free, under the bilateral pact. Seafarers: visa application required',
            'processing_time_text' => 'Not reliably confirmed exact for the seafarer visa route',
            'validity_text' => 'Airline crew: tied to the bilateral reciprocal agreement. Seafarers: tied to the seaman\'s contract duration',
            'application_method' => 'Airline crew: no visa application needed (visa-free under the bilateral pact). Seafarers: standard Russian visa application with seafarer-specific documents',
            'interview_required' => 'Not required for either route, per available research',
            'biometric_required' => 'Required for the seafarer visa route; not applicable to visa-free airline crew',
            'government_fee_text' => 'Not applicable to visa-free airline crew; seafarer visa fee not reliably confirmed',
            'application_centre' => 'Not applicable for airline crew; Russian consular mission for seafarer visas',
            'authority_name' => 'Government of India / Government of the Russian Federation (bilateral aviation agreement)',
            'authority_url' => null,
            'eligibility_html' => '<p><strong>Airline crew</strong> flying for designated Indian or Russian airlines benefit from a reciprocal bilateral agreement providing visa-free entry, stay and exit. <strong>Seafarers</strong> are NOT covered by this agreement and must obtain a standard Russian visa, submitting a seaman\'s contract (original + copy, showing vessel name, rank, passport data, CDC number, and contract duration, signed by both applicant and vessel owner) and a national seaman\'s certificate (original + copy).</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Conflate the Two Crew Types</h4><p>The visa-free privilege applies only to airline crew under the specific bilateral pact — it does not extend to maritime crew.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Airline Crew: No Visa Needed</h4><p>Crew of designated airlines\' chartered/scheduled flights travel visa-free under the India-Russia bilateral agreement.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Seafarers: Visa Required</h4><p>Bring your seaman\'s contract and national seaman\'s certificate to apply for a standard Russian visa.</p><p>Our consultants can help you confirm which route applies to your specific crew role.</p>',
            'seo_title' => 'Russia Crew Visa for Indians | Airline Crew vs Seafarer Rules',
            'meta_description' => 'Flying or sailing to Russia as crew? See the visa-free airline-crew bilateral pact and the separate seafarer visa requirement, via VisaAgency.in.',
            'og_title' => 'Russia Crew Visa for Indians — Airline Crew vs Seafarer Rules',
            'og_description' => 'Flying or sailing to Russia as crew? See the visa-free airline-crew bilateral pact and the separate seafarer visa requirement, via VisaAgency.in.',
            'documents' => [
                ['Supporting Documents', 'Seaman\'s contract, original + copy (seafarers)', 'conditional'],
                ['Supporting Documents', 'National seaman\'s certificate, original + copy (seafarers)', 'conditional'],
            ],
            'steps' => [
                ['Confirm Your Crew Type', 'Airline crew are visa-free under the bilateral agreement; seafarers need a visa.'],
                ['Seafarers: Prepare Contract Documentation', 'Seaman\'s contract and national seaman\'s certificate.'],
                ['Seafarers: Apply at a Russian Consular Mission', 'Allow sufficient time before travel.'],
            ],
            'faqs' => [
                ['Do Indian airline crew need a Russian visa?', 'No — a bilateral reciprocal agreement grants visa-free entry, stay and exit for crew of designated airlines\' flights.'],
                ['Do Indian seafarers need a Russian visa?', 'Yes — the airline-crew visa-free agreement does not extend to maritime crew.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Government of India / Government of the Russian Federation (bilateral aviation agreement)',
                'url' => null,
                'notes' => 'Phase 3A research: the India-Russia bilateral reciprocal airline-crew visa-free agreement is confirmed via Indian government sources; the separate seafarer visa documentation requirement (seaman\'s contract, CDC number, seaman\'s certificate) confirmed via standard Russian visa-document sources. Case-distinguishing governance preserved. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'seychelles-crew-visa',
            'country_slug' => 'seychelles',
            'category_slug' => 'crew-visa',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Maritime Travel Authorisation (MTA), with an explicit exemption for crew who depart by air the same day',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Since 1 December, Seychelles\' Department of Immigration and Civil Status requires a Maritime Travel Authorisation (MTA) for all international passengers arriving by sea, including cruise ships and private yachts. Crucially, seafarers/crew disembarking from a vessel and departing Seychelles by air the same day are explicitly EXEMPT from this requirement — the MTA is only mandatory for crew who stay at a tourism establishment ashore.</p>',
            'typical_stay' => 'Governed by Seychelles\' general visa-free entry terms (up to 30 days) for crew who disembark and overnight ashore; same-day-departure crew need no authorisation at all',
            'entry_type' => 'MTA completed online, up to 30 days before arrival or at the last port of departure; not required for same-day-air-departure crew',
            'processing_time_text' => 'Online MTA completion, up to 30 days before arrival or at the last port of departure',
            'validity_text' => 'Tied to the specific voyage/arrival; same-day-departure crew are exempt entirely',
            'application_method' => 'Online travel authorisation/disembarkation information form (for crew staying ashore); no application needed for same-day-air-departure crew',
            'interview_required' => 'Not required',
            'biometric_required' => 'Not required',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Seychelles Department of Immigration and Civil Status (online MTA system)',
            'authority_name' => 'Seychelles Tourism Department / Department of Immigration and Civil Status (tourism.gov.sc)',
            'authority_url' => 'https://tourism.gov.sc',
            'eligibility_html' => '<p>Crew disembarking a vessel and departing Seychelles by air on the same day do not need to complete the Maritime Travel Authorisation at all. Crew (and other sea-arrival visitors) who will be staying at a tourism establishment ashore must complete the online travel authorisation/disembarkation form, up to 30 days before arrival or at their last port of departure.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Same-Day Air Departure? No Authorisation Needed</h4><p>Crew disembarking and flying out the same day are explicitly exempt from the Maritime Travel Authorisation.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Staying Ashore? Complete the Online MTA</h4><p>Up to 30 days before arrival or at your last port of departure.</p><p>Our consultants can help you confirm which MTA rule applies to your specific voyage plan.</p>',
            'seo_title' => 'Seychelles Crew Visa for Indians | Maritime Travel Authorisation',
            'meta_description' => 'Crewing a vessel to Seychelles? See the Maritime Travel Authorisation and its same-day-departure exemption, via VisaAgency.in.',
            'og_title' => 'Seychelles Crew Visa for Indians — Maritime Travel Authorisation',
            'og_description' => 'Crewing a vessel to Seychelles? See the Maritime Travel Authorisation and its same-day-departure exemption, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Departure Plan', 'Same-day air departure is exempt from the MTA entirely.'],
                ['If Staying Ashore, Complete the Online MTA', 'Up to 30 days before arrival or at your last port of departure.'],
            ],
            'faqs' => [
                ['Do all crew need a Maritime Travel Authorisation?', 'No — crew who disembark and depart Seychelles by air the same day are explicitly exempt.'],
                ['When was the MTA introduced?', 'Since 1 December, for all international passengers arriving by sea.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Seychelles Tourism Department / Department of Immigration and Civil Status (tourism.gov.sc)',
                'url' => 'https://tourism.gov.sc',
                'notes' => 'Phase 3A research: official tourism.gov.sc source directly confirms the MTA requirement and the explicit same-day-air-departure crew exemption. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'taiwan-crew-visa',
            'country_slug' => 'taiwan',
            'category_slug' => 'crew-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Visitor Visa for Seafarers, via the Taipei Economic and Cultural Office (TECO) network',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Taiwan\'s representative-office network (TECO/roc-taiwan.org) issues a "Visitor Visa for Seafarers" for maritime crew. The core mechanism requires a Letter of Guarantee from the Taiwan-based shipping agent, confirmation of the vessel\'s registration/Flagship Certificate, and the seafarer\'s own Seafarer\'s Identification and Seaman\'s Book.</p>',
            'typical_stay' => 'Not reliably confirmed exact',
            'entry_type' => 'Taipei Economic and Cultural Office (TECO) serving the applicant\'s country',
            'processing_time_text' => 'Not reliably confirmed exact',
            'validity_text' => 'Not reliably confirmed exact',
            'application_method' => 'Online form at visawebapp.boca.gov.tw, submitted with supporting documents through the relevant TECO office',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Not reliably confirmed exact',
            'application_centre' => 'Taipei Economic and Cultural Office (TECO) / National Immigration Agency',
            'authority_name' => 'Taipei Economic and Cultural Office (TECO) / roc-taiwan.org',
            'authority_url' => 'https://roc-taiwan.org/uploads/sites/76/2023/04/6.-20250307-updated-Visitor-Visa-for-Seafarers.pdf',
            'eligibility_html' => '<p>Core requirements include an online application via visawebapp.boca.gov.tw, two colour passport photos, a passport valid 6+ months, a Letter of Guarantee from the Taiwan shipping agent (naming the seafarer, vessel details, and the local shipping agent in the applicant\'s country), the Taiwanese shipping company\'s ROC-issued registration, the vessel\'s Flagship Certificate, and the seafarer\'s own Seafarer\'s Identification and Seaman\'s Book.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Document Found Is From a Different Mission</h4><p>The specific document located in research describes the Philippines-mission version of this harmonised TECO form (referencing a Philippines-based shipping agent and Filipino-issued Overseas Employment Certificate); these mission-specific agent/document names do not apply to India. Confirm the India-specific version of this requirement directly with the TECO office serving India.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Confirm the India-Specific Requirements With TECO</h4><p>The document located in research describes the Philippines-mission version of this harmonised form — your Taiwan shipping agent and TECO India office can confirm the exact India-specific paperwork.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Core Documents Apply Regardless</h4><p>Seafarer\'s Identification, Seaman\'s Book, and a Letter of Guarantee from your Taiwan shipping agent.</p><p>Our consultants can help you confirm the current India-specific checklist with TECO.</p>',
            'seo_title' => 'Taiwan Crew Visa for Indians | Visitor Visa for Seafarers',
            'meta_description' => 'Joining a vessel in Taiwan? See the Visitor Visa for Seafarers process via TECO for Indian crew, via VisaAgency.in.',
            'og_title' => 'Taiwan Crew Visa for Indians — Visitor Visa for Seafarers',
            'og_description' => 'Joining a vessel in Taiwan? See the Visitor Visa for Seafarers process via TECO for Indian crew, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Passport valid 6+ months', 'mandatory'],
                ['Basic Documents', '2 colour passport photos (45mm x 35mm)', 'mandatory'],
                ['Supporting Documents', 'Letter of Guarantee from the Taiwan shipping agent', 'mandatory'],
                ['Supporting Documents', 'Vessel\'s Flagship Certificate', 'mandatory'],
                ['Supporting Documents', 'Seafarer\'s Identification and Seaman\'s Book', 'mandatory'],
            ],
            'steps' => [
                ['Secure Your Letter of Guarantee', 'From your Taiwan-based shipping agent.'],
                ['Apply Online', 'Via visawebapp.boca.gov.tw.'],
                ['Submit Through TECO', 'The office serving your country/India.'],
            ],
            'faqs' => [
                ['What is the Visitor Visa for Seafarers?', 'Taiwan\'s dedicated crew visa product for maritime seafarers, issued through the TECO network.'],
                ['Is the process India-specific?', 'The document located in research describes the Philippines-mission version; confirm India-specific agent/paperwork details directly with TECO.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Taipei Economic and Cultural Office (TECO) / roc-taiwan.org',
                'url' => 'https://roc-taiwan.org/uploads/sites/76/2023/04/6.-20250307-updated-Visitor-Visa-for-Seafarers.pdf',
                'notes' => 'Phase 3A research: official roc-taiwan.org/TECO document confirms the Visitor Visa for Seafarers mechanism; the specific copy located serves the Philippines mission (harmonised document format, same precedent as Denmark/Norway Medical records), so Philippines-specific agent names are explicitly not carried over as India-specific. Confidence: Medium.',
            ],
        ],
        [
            'page_slug' => 'tanzania-crew-visa',
            'country_slug' => 'tanzania',
            'category_slug' => 'crew-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Crew/seafarer shore-leave pass, via the Tanzania Immigration Department',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Tanzania\'s Immigration Department issues a pass for crew members of ships arriving by sea who wish to disembark for sightseeing or other sufficient reasons while the vessel is in port, confirmed via the official immigration.go.tz "pass information" page. General requirements include a copy of the valid passport, a covering letter from the relevant institution, and the applicable fee for the pass type.</p>',
            'typical_stay' => 'Tied to the vessel\'s time in port',
            'entry_type' => 'Tanzania Immigration Department, at the port',
            'processing_time_text' => 'Not reliably confirmed exact',
            'validity_text' => 'Tied to the vessel\'s time in port',
            'application_method' => 'Via the Tanzania Immigration Department, with a covering letter and the required documents',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'Varies by pass type; exact current amount not reliably confirmed',
            'application_centre' => 'Tanzania Immigration Department (immigration.go.tz)',
            'authority_name' => 'Tanzania Immigration Department (immigration.go.tz)',
            'authority_url' => 'https://immigration.go.tz/index.php/97-pass-information',
            'eligibility_html' => '<p>Crew members of ships arriving by sea who wish to disembark for shore leave need a copy of their valid passport, a covering letter from their shipping company/institution, and payment of the relevant fee. More detailed seafarer documentation can include a signed letter of employment/contract with full seafarer details, job description, vessel name and flag, and the port/dates of boarding and disembarkation.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Arrange Your Covering Letter in Advance</h4><p>From your shipping company or employing institution, confirming your role and vessel details.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm the Current Pass Fee</h4><p>This varies by pass type and was not reliably confirmed in research.</p><p>Our consultants can help you confirm the current shore-leave pass requirements with the Tanzania Immigration Department.</p>',
            'seo_title' => 'Tanzania Crew Visa for Indians | Shore-Leave Pass',
            'meta_description' => 'Crewing a vessel calling at a Tanzanian port? See the shore-leave pass process for seafarers, via VisaAgency.in.',
            'og_title' => 'Tanzania Crew Visa for Indians — Shore-Leave Pass',
            'og_description' => 'Crewing a vessel calling at a Tanzanian port? See the shore-leave pass process for seafarers, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Copy of valid passport', 'mandatory'],
                ['Supporting Documents', 'Covering letter from the shipping company/institution', 'mandatory'],
                ['Supporting Documents', 'Signed letter of employment/contract with vessel and voyage details', 'conditional'],
            ],
            'steps' => [
                ['Prepare Your Covering Letter', 'From your shipping company or employing institution.'],
                ['Apply at the Tanzania Immigration Department', 'While your vessel is in port.'],
                ['Pay the Applicable Pass Fee', 'Which varies by pass type.'],
            ],
            'faqs' => [
                ['Can ship crew get shore leave in Tanzania?', 'Yes — the Immigration Department issues a pass for crew wishing to disembark while the vessel is in port.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Tanzania Immigration Department (immigration.go.tz)',
                'url' => 'https://immigration.go.tz/index.php/97-pass-information',
                'notes' => 'Phase 3A research: official immigration.go.tz "pass information" page confirms the crew/seafarer shore-leave pass system exists; exact fee not located. Confidence: Medium-High.',
            ],
        ],
    ];
}
