<?php
/**
 * Phase 3B -- Medical Visa gap-closure for 6 of the 8 Tier-B cells that
 * remained generic after Phase 3A, following a targeted authority-first
 * re-research pass (see scratchpad/phase3a/RESEARCH_AUDIT_3B.md). Morocco and
 * Seychelles still had zero defensible evidence after this second pass and
 * remain generic. Preserves the Myanmar (honest negative -- no dedicated
 * category exists) and Mexico (general Visitante visa, not a dedicated medical
 * visa) and Tanzania (general visa purpose vs. separate C-6 residence permit)
 * governance distinctions established during research.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_phase3b_medical(): array
{
    return [
        [
            'page_slug' => 'bangladesh-medical-visa',
            'country_slug' => 'bangladesh',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Medical Treatment Visa (M), with a companion Medical Attendant Visa (MA) for up to two accompanying attendants',
            'visa_subclass_code' => 'M',
            'intro_html' => '<p>Bangladesh issues a dedicated Medical Treatment Visa, category M, for patients travelling specifically for treatment, with a companion Medical Attendant Visa (MA) permitting up to two accompanying attendants. Applications are submitted through the official online MRV portal.</p>',
            'typical_stay' => 'Not reliably confirmed exact',
            'entry_type' => 'Bangladesh mission/consulate serving India, via the official MRV portal',
            'processing_time_text' => 'Processing time varies; confirm current timelines with the relevant Bangladesh authority',
            'validity_text' => 'Not reliably confirmed exact',
            'application_method' => 'Online via the official MRV visa portal (visa.gov.bd), with documents submitted to the Bangladesh mission',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: confirm the current fee with the official Bangladesh authority before applying or paying',
            'application_centre' => 'Bangladesh mission/consulate serving India',
            'authority_name' => 'Bangladesh Department of Immigration and Passports (dip.gov.bd) / official MRV portal (visa.gov.bd)',
            'authority_url' => 'https://visa.gov.bd',
            'eligibility_html' => '<p>Applicants for the M visa must have at least two blank passport pages, 6+ months passport validity, documented financial arrangements for the treatment visit, evidence of treatment or appointment acceptance from a Bangladesh medical provider, and medical reports/diagnosis. Up to two attendants may separately apply for the companion MA (Medical Attendant) visa.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm With the Official Authority</h4><p>Bangladesh immigration is administered through dip.gov.bd; applications are submitted via the official visa.gov.bd MRV portal — confirm current requirements directly, as the specific M/MA visa-code detail was drawn from secondary research corroborated by an official visa circular reference, not a directly-read primary government page.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Through the Official MRV Portal</h4><p>visa.gov.bd, with supporting hospital/treatment-acceptance documents.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Up to Two Attendants Can Accompany You</h4><p>Via the separate Medical Attendant (MA) visa category.</p><p>Our consultants can help you confirm the current M/MA documentary checklist and fee with the Bangladesh mission.</p>',
            'seo_title' => 'Bangladesh Medical Visa for Indians | Medical Treatment Visa (M)',
            'meta_description' => 'Travelling to Bangladesh for medical treatment? See the Medical Treatment Visa (M) and Medical Attendant Visa (MA) categories, via VisaAgency.in.',
            'og_title' => 'Bangladesh Medical Visa for Indians — Medical Treatment Visa (M)',
            'og_description' => 'Travelling to Bangladesh for medical treatment? See the Medical Treatment Visa (M) and Medical Attendant Visa (MA) categories, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport (6+ months validity, 2+ blank pages)', 'mandatory'],
                ['Medical Documents', 'Evidence of treatment/appointment acceptance from a Bangladesh medical provider', 'mandatory'],
                ['Medical Documents', 'Medical reports and diagnosis', 'mandatory'],
                ['Financial Documents', 'Documented financial arrangements for the treatment visit', 'mandatory'],
            ],
            'steps' => [
                ['Secure Treatment Acceptance', 'From a Bangladesh medical provider.'],
                ['Apply via the MRV Portal', 'visa.gov.bd, submitting documents to the Bangladesh mission.'],
                ['Arrange Attendant Visas If Needed', 'Up to two attendants under the separate MA category.'],
            ],
            'faqs' => [
                ['Does Bangladesh have a dedicated medical visa?', 'Yes — the Medical Treatment Visa (M), with a companion Medical Attendant Visa (MA) for up to two attendants.'],
                ['Where do I apply?', 'Through the official MRV portal (visa.gov.bd) and the Bangladesh mission serving India.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Bangladesh Department of Immigration and Passports (dip.gov.bd) / official MRV portal (visa.gov.bd)',
                'url' => 'https://visa.gov.bd',
                'notes' => 'Phase 3B research: M/MA visa-code naming corroborated by a Visa Circular reference (Visa_Circular_1655) and confirmation that dip.gov.bd/visa.gov.bd are the correct official portals; the specific page content was not directly read from the primary government site. Confidence: Medium.',
            ],
        ],
        [
            'page_slug' => 'fiji-medical-visa',
            'country_slug' => 'fiji',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Special Purpose Permit on Medical Grounds',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Fiji\'s Ministry of Immigration issues a Special Purpose Permit on Medical Grounds to non-citizens wishing to reside in Fiji and undergo medical treatment at a local hospital, on the recommendation of a certified medical practitioner.</p>',
            'typical_stay' => 'Tied to the recommended treatment period',
            'entry_type' => 'Application to the Director of Immigration, Fiji',
            'processing_time_text' => '21 working days',
            'validity_text' => 'Tied to the recommended treatment period',
            'application_method' => 'Prescribed application form submitted to the Director of Immigration',
            'interview_required' => 'Not required — a documentary application process',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: confirm the current application fee with the Fiji Ministry of Immigration before applying or paying',
            'application_centre' => 'Fiji Ministry of Immigration',
            'authority_name' => 'Fiji Ministry of Immigration (immigration.gov.fj)',
            'authority_url' => 'https://www.immigration.gov.fj/?p=1271',
            'eligibility_html' => '<p>Eligibility requires a recommendation letter from a registered medical practitioner. Required documents include a completed and signed application form, request letter, two recent passport photos, certified copy of birth certificate, certified copy of passport biodata page, a medical transfer letter from the Ministry of Health or a registered medical practitioner, confirmed airline/boat ticket, and a copy of the vaccination card.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Secure Your Medical Transfer Letter First</h4><p>From the Ministry of Health or a registered medical practitioner, confirming the recommended treatment.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Allow 21 Working Days</h4><p>For the Director of Immigration to process your application.</p><p>Our consultants can help you assemble the full documentary checklist for this permit.</p>',
            'seo_title' => 'Fiji Medical Visa for Indians | Special Purpose Permit on Medical Grounds',
            'meta_description' => 'Need medical treatment in Fiji? See the official Special Purpose Permit on Medical Grounds process, via VisaAgency.in.',
            'og_title' => 'Fiji Medical Visa for Indians — Special Purpose Permit on Medical Grounds',
            'og_description' => 'Need medical treatment in Fiji? See the official Special Purpose Permit on Medical Grounds process, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Completed and signed application form', 'mandatory'],
                ['Basic Documents', 'Certified copy of passport biodata page', 'mandatory'],
                ['Basic Documents', 'Certified copy of birth certificate', 'mandatory'],
                ['Basic Documents', '2 recent passport photographs', 'mandatory'],
                ['Supporting Documents', 'Request letter', 'mandatory'],
                ['Medical Documents', 'Medical transfer letter from Ministry of Health/registered medical practitioner', 'mandatory'],
                ['Travel Documents', 'Confirmed airline/boat ticket', 'mandatory'],
                ['Supporting Documents', 'Copy of vaccination card', 'mandatory'],
            ],
            'steps' => [
                ['Obtain a Medical Recommendation', 'From a registered medical practitioner.'],
                ['Submit the Prescribed Application Form', 'To the Director of Immigration, with all supporting documents.'],
                ['Allow 21 Working Days for Processing', 'Before your planned travel.'],
            ],
            'faqs' => [
                ['What is Fiji\'s medical treatment permit called?', 'The Special Purpose Permit on Medical Grounds, a named immigration product distinct from the general visitor permit.'],
                ['How long does processing take?', '21 working days.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Fiji Ministry of Immigration (immigration.gov.fj)',
                'url' => 'https://www.immigration.gov.fj/?p=1271',
                'notes' => 'Phase 3B research: official immigration.gov.fj directly confirms this named permit and its documentary requirements. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'mexico-medical-visa',
            'country_slug' => 'mexico',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'No separate dedicated Medical Visa — medical treatment is a permitted activity under the general Visitante (Visitor) visa',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Mexico does not appear to operate a separate, dedicated "Medical Visa" product. Instead, the general Visitante (Visitor) visa — issued via Mexican consular offices — permits a stay of up to 180 days, during which receiving medical treatment is one of the recognized non-remunerated activities. Applicants present an original medical certificate from a doctor/health institution in their home country.</p>',
            'typical_stay' => 'Up to 180 days under the Visitante visa',
            'entry_type' => 'Mexican Consular Office serving India, appointment via MiConsulado (citas.sre.gob.mx)',
            'processing_time_text' => 'Processing time varies; confirm current timelines with the Mexican consular office',
            'validity_text' => 'Up to 180 days, no permission to perform remunerated activities',
            'application_method' => 'Appointment via MiConsulado (citas.sre.gob.mx), presenting the original medical certificate and proof of fee payment at the Mexican Consular Office',
            'interview_required' => 'Not described as requiring a formal interview beyond the consular appointment',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: USD 62.00 (as of a January 2024 reference) — confirm the current fee with the Mexican consular office before applying or paying',
            'application_centre' => 'Mexican Consular Office serving India',
            'authority_name' => 'Secretaría de Relaciones Exteriores (SRE), Mexico / Mexican consular network',
            'authority_url' => 'https://consulmex.sre.gob.mx/atlanta/index.php/servicios-para-extranjeros/visas-eng',
            'eligibility_html' => '<p>There is no indication of a separate, dedicated medical-treatment visa category in Mexican immigration law — rather, the general Visitante visa (up to 180 days, no remunerated activity permitted) covers medical treatment as one of its recognized purposes. Applicants present an original medical certificate issued by a health institution or doctor in their country of origin, along with proof of fee payment, at the Mexican Consular Office.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Important Distinction</h4><p>This is separate from an unrelated Mexican bureaucratic process sometimes called "visado a certificado médico," which concerns stamping/validating a medical certificate for other immigration purposes (such as permanent residence applications) — not a medical-treatment travel visa. That process is not described here.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Book Your Appointment via MiConsulado</h4><p>citas.sre.gob.mx, presenting your original medical certificate and fee payment proof.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>No Separate "Medical Visa" Exists</h4><p>Medical treatment is a permitted activity under the general Visitante visa, not a distinct visa category.</p><p>Our consultants can help you confirm the current fee and documentary checklist with your nearest Mexican consular office.</p>',
            'seo_title' => 'Mexico Medical Visa for Indians | Visitante Visa for Medical Treatment',
            'meta_description' => 'Travelling to Mexico for medical treatment? See how the general Visitante visa covers this, not a separate medical visa, via VisaAgency.in.',
            'og_title' => 'Mexico Medical Visa for Indians — Visitante Visa for Medical Treatment',
            'og_description' => 'Travelling to Mexico for medical treatment? See how the general Visitante visa covers this, not a separate medical visa, via VisaAgency.in.',
            'documents' => [
                ['Medical Documents', 'Original medical certificate from a health institution/doctor in India', 'mandatory'],
                ['Financial Documents', 'Proof of fee payment', 'mandatory'],
            ],
            'steps' => [
                ['Obtain Your Medical Certificate', 'From a health institution or doctor in India.'],
                ['Book a MiConsulado Appointment', 'Via citas.sre.gob.mx.'],
                ['Present Documents at the Consular Office', 'Original medical certificate and fee payment proof.'],
            ],
            'faqs' => [
                ['Does Mexico have a dedicated medical treatment visa?', 'No — medical treatment is a permitted activity under the general Visitante (Visitor) visa, which allows a stay of up to 180 days.'],
                ['What is the fee?', 'As researched, USD 62.00 (January 2024 reference) — confirm the current fee directly.'],
            ],
            'fees' => [
                ['Visitante visa (medical treatment activity)', 'USD 62.00', 1, 'USD', 'As researched (January 2024 reference); confirm the current fee with the official authority before applying or paying'],
            ],
            'source' => [
                'authority' => 'Secretaría de Relaciones Exteriores (SRE), Mexico / Mexican consular network',
                'url' => 'https://consulmex.sre.gob.mx/atlanta/index.php/servicios-para-extranjeros/visas-eng',
                'notes' => 'Phase 3B research: official gob.mx/sre.gob.mx domains confirm the Visitante visa permits medical treatment as an activity; the unrelated "visado a certificado médico" bureaucratic process found in the same search is explicitly excluded to avoid conflation. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'myanmar-medical-visa',
            'country_slug' => 'myanmar',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'No dedicated Medical Visa category identified — only Tourist and Business eVisa are available via the official Myanmar eVisa portal',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Myanmar\'s official eVisa portal (evisa.moip.gov.mm), operated by the Ministry of Immigration and Population, offers only Tourist and Business eVisa categories. No dedicated Medical Visa mechanism was identified in official Myanmar immigration sources.</p>',
            'typical_stay' => 'Not applicable — no dedicated medical category exists',
            'entry_type' => 'Not applicable — no dedicated medical category exists',
            'processing_time_text' => 'Not applicable — no dedicated medical category exists',
            'validity_text' => 'Not applicable — no dedicated medical category exists',
            'application_method' => 'Not applicable — travellers needing medical treatment should confirm with Myanmar authorities whether the Tourist or Business eVisa, or another route, is appropriate for their circumstances',
            'interview_required' => 'Not required — no dedicated medical-visa application exists',
            'biometric_required' => 'Not required — no dedicated medical-visa application exists',
            'government_fee_text' => 'Not applicable — no dedicated medical-visa fee exists',
            'application_centre' => 'Not applicable; Ministry of Immigration and Population (evisa.moip.gov.mm) for Tourist/Business eVisa',
            'authority_name' => 'Ministry of Immigration and Population, Myanmar (evisa.moip.gov.mm)',
            'authority_url' => 'https://evisa.moip.gov.mm',
            'eligibility_html' => '<p>Myanmar\'s official eVisa system, administered by the Ministry of Immigration and Population, lists only Tourist and Business eVisa as available online categories. This research found no dedicated Medical Visa mechanism in official Myanmar sources.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>This Is a Genuine Researched Finding — Not a Gap</h4><p>Travellers needing medical treatment in Myanmar should confirm directly with Myanmar immigration authorities (or the nearest Myanmar mission) whether an existing visa category can accommodate their purpose, rather than assuming a dedicated medical pathway exists.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>No Dedicated Medical Category Exists</h4><p>Myanmar\'s official eVisa system offers only Tourist and Business eVisa — confirm with Myanmar authorities which route, if any, fits your medical-treatment purpose.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Assume Medical Treatment Is Automatically Covered</h4><p>Neither the Tourist nor Business eVisa is confirmed to specifically authorize medical treatment as a purpose.</p><p>Our consultants can help you confirm the most appropriate route directly with Myanmar immigration authorities before you travel.</p>',
            'seo_title' => 'Myanmar Medical Visa for Indians | No Dedicated Category Found',
            'meta_description' => 'Looking for a Myanmar medical treatment visa? See why none exists and what to confirm before travelling, via VisaAgency.in.',
            'og_title' => 'Myanmar Medical Visa for Indians — No Dedicated Category Found',
            'og_description' => 'Looking for a Myanmar medical treatment visa? See why none exists and what to confirm before travelling, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Confirm Your Situation With Myanmar Authorities', 'Since no dedicated medical visa category exists.'],
                ['Review the Tourist and Business eVisa Terms', 'Via evisa.moip.gov.mm, to assess whether either fits your purpose.'],
            ],
            'faqs' => [
                ['Does Myanmar have a medical treatment visa?', 'No dedicated category was found — the official eVisa portal lists only Tourist and Business eVisa.'],
                ['What should I do if I need medical treatment in Myanmar?', 'Confirm directly with Myanmar immigration authorities or the nearest Myanmar mission which existing route, if any, applies to your situation.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Immigration and Population, Myanmar (evisa.moip.gov.mm)',
                'url' => 'https://evisa.moip.gov.mm',
                'notes' => 'Phase 3B research: official moip.gov.mm eVisa portal confirms only Tourist and Business eVisa exist; this is an honest, officially-sourced negative finding, not an unresearched gap. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'russia-medical-visa',
            'country_slug' => 'russia',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => 'Entry for treatment purposes, via an invitation letter from a Russian medical organization submitted to the territorial unit of the Ministry of Internal Affairs (MVD)',
            'visa_subclass_code' => null,
            'intro_html' => '<p>A foreign citizen may enter Russia for treatment purposes with an invitation letter issued by a Russian medical organization (stating treatment purpose, applicant ID details, arrival/departure dates and diagnosis), which is submitted, for visa-required nationals, to the territorial unit of the Ministry of Internal Affairs (MVD). This is a purpose-based entry mechanism rather than a separately-branded "Medical Visa" product.</p>',
            'typical_stay' => 'Tied to the treatment period stated in the medical organization\'s invitation letter',
            'entry_type' => 'Via a Russian medical organization\'s invitation, processed through the territorial MVD unit',
            'processing_time_text' => 'Processing time varies; confirm current timelines with the relevant Russian authority',
            'validity_text' => 'Tied to the treatment period stated in the invitation letter',
            'application_method' => 'Invitation letter obtained from the Russian medical organization providing treatment, then submitted to the territorial unit of the Ministry of Internal Affairs (MVD)',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: confirm the current fee with the relevant Russian authority before applying or paying',
            'application_centre' => 'Territorial unit of the Ministry of Internal Affairs (MVD), per the medical organization\'s location',
            'authority_name' => 'Ministry of Internal Affairs of the Russian Federation (MVD) — legal basis per consultant.ru (official Russian legal database)',
            'authority_url' => null,
            'eligibility_html' => '<p>The invitation letter issued by the receiving Russian medical organization must state the treatment purpose, the applicant\'s identity details, arrival and departure dates, and the diagnosis. This invitation underpins the entry-for-treatment process at the territorial MVD unit. Providing false information or forged treatment-invitation documents carries criminal liability under Article 322 of the Russian Criminal Code.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Purpose-Based, Not a Separately-Named Visa</h4><p>This is implemented here as a researched medical-entry pathway, not overstated as a universally-named "Medical Visa" — the underlying mechanism is invitation- and visa-purpose-based.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Secure Your Medical Organization\'s Invitation Letter First</h4><p>This must state the treatment purpose, your ID details, planned dates, and diagnosis.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Submit It to the Territorial MVD Unit</h4><p>Corresponding to the medical organization\'s location.</p><p>Our consultants can help you confirm the current process and required documentation with the relevant Russian authority.</p>',
            'seo_title' => 'Russia Medical Visa for Indians | Treatment-Purpose Entry',
            'meta_description' => 'Travelling to Russia for medical treatment? See the invitation-letter-based entry process via the territorial MVD unit, via VisaAgency.in.',
            'og_title' => 'Russia Medical Visa for Indians — Treatment-Purpose Entry',
            'og_description' => 'Travelling to Russia for medical treatment? See the invitation-letter-based entry process via the territorial MVD unit, via VisaAgency.in.',
            'documents' => [
                ['Medical Documents', 'Invitation letter from the Russian medical organization (purpose, ID details, dates, diagnosis)', 'mandatory'],
            ],
            'steps' => [
                ['Secure a Treatment Invitation Letter', 'From the Russian medical organization providing treatment.'],
                ['Submit It to the Territorial MVD Unit', 'Corresponding to the medical organization\'s location.'],
            ],
            'faqs' => [
                ['Does Russia have a named "Medical Visa"?', 'The mechanism is purpose-based: an invitation letter from a Russian medical organization submitted to the territorial MVD unit, rather than a separately-branded visa product.'],
                ['What happens if the invitation documents are falsified?', 'Criminal liability applies under Article 322 of the Russian Criminal Code.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Ministry of Internal Affairs of the Russian Federation (MVD) — legal basis per consultant.ru (official Russian legal database)',
                'url' => null,
                'notes' => 'Phase 3B research: consultant.ru (an established official Russian legal-document database) confirms the invitation-letter/MVD mechanism and cites Criminal Code Article 322; no direct mvd.rf page was located. Confidence: Medium-High.',
            ],
        ],
        [
            'page_slug' => 'tanzania-medical-visa',
            'country_slug' => 'tanzania',
            'category_slug' => 'medical-visa',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'unknown',
            'official_visa_name' => '"Health treatment" is an explicit visa-issuable purpose under the general Tanzanian visa framework; a separate Residence Permit Class C-6 (Medical Treatment) exists for longer-term treatment',
            'visa_subclass_code' => 'C-6 (Residence Permit, for longer-term treatment only)',
            'intro_html' => '<p>Official Tanzania Immigration confirms that a visa may be granted for "visit, tourism, leisure, holiday, business, health treatment, attending conference, or any other related activities recognised by the Laws" — health treatment is explicitly one of the recognized general-visa purposes. For longer-term medical treatment, a distinct Residence Permit Class C-6 (Medical Treatment) exists as a separate legal mechanism.</p>',
            'typical_stay' => 'General visa: tied to the standard visa terms for the health-treatment purpose. Residence Permit C-6: for longer-term treatment, terms not independently confirmed',
            'entry_type' => 'Official Tanzania Immigration portal (immigration.go.tz / eservices.immigration.go.tz)',
            'processing_time_text' => 'Processing time varies; confirm current timelines with Tanzania Immigration',
            'validity_text' => 'General visa: standard visa validity terms. Residence Permit C-6: for longer-term treatment, terms not independently confirmed',
            'application_method' => 'Apply via the official Tanzania Immigration website (www.immigration.go.tz) ONLY, per the authority\'s own guidance; Residence Permit C-6 applications via eservices.immigration.go.tz',
            'interview_required' => 'Unknown — not clearly confirmed in available research',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: fees may apply; confirm the current fee directly with Tanzania Immigration before applying or paying',
            'application_centre' => 'Tanzania Immigration Department (immigration.go.tz)',
            'authority_name' => 'Tanzania Immigration Department (immigration.go.tz)',
            'authority_url' => 'https://immigration.go.tz/index.php/visa-and-pass-information',
            'eligibility_html' => '<p>For shorter visits, "health treatment" is one of the general purposes for which a Tanzanian visa may be issued, per official immigration.go.tz guidance. For longer-term medical treatment requiring residence, a separate Residence Permit Class C-6 (Medical Treatment) exists as a distinct legal mechanism — specific documented requirements for the C-6 permit were not independently confirmed in this research.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Visa vs. Residence Permit — Do Not Conflate</h4><p>The general visa (health-treatment purpose) and the Residence Permit C-6 are different legal products for different durations of stay.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Shorter Treatment: Apply for the General Visa</h4><p>Citing "health treatment" as your purpose, via the official immigration.go.tz portal.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Longer-Term Treatment: Ask About Residence Permit C-6</h4><p>A separate mechanism for extended medical treatment — confirm specific requirements directly with Tanzania Immigration.</p><p>Our consultants can help you determine which route fits your treatment duration.</p>',
            'seo_title' => 'Tanzania Medical Visa for Indians | Health Treatment Visa & C-6 Permit',
            'meta_description' => 'Need medical treatment in Tanzania? See the health-treatment visa purpose and the separate C-6 Residence Permit, via VisaAgency.in.',
            'og_title' => 'Tanzania Medical Visa for Indians — Health Treatment Visa & C-6 Permit',
            'og_description' => 'Need medical treatment in Tanzania? See the health-treatment visa purpose and the separate C-6 Residence Permit, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Determine Your Treatment Duration', 'To identify whether the general visa or Residence Permit C-6 applies.'],
                ['Apply via the Official Immigration Portal', 'www.immigration.go.tz, citing health treatment as your purpose.'],
            ],
            'faqs' => [
                ['Does Tanzania recognize medical treatment as a visa purpose?', 'Yes — "health treatment" is explicitly listed among the recognized purposes for which a Tanzanian visa may be granted.'],
                ['What about longer-term treatment?', 'A separate Residence Permit Class C-6 (Medical Treatment) exists for longer-term medical treatment, a different legal mechanism from the general visa.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Tanzania Immigration Department (immigration.go.tz)',
                'url' => 'https://immigration.go.tz/index.php/visa-and-pass-information',
                'notes' => 'Phase 3B research: official immigration.go.tz page directly lists health treatment as a recognized visa purpose; the C-6 Residence Permit code is corroborated by secondary research, not independently confirmed in full detail on the primary page. Confidence: High for the visa-purpose mechanism, Medium for the C-6 Residence Permit specifics.',
            ],
        ],
    ];
}
