<?php
/**
 * Phase 3B -- Extension Visa gap-closure for all 4 of the Tier-B cells that
 * remained generic after Phase 3A. Preserves the Morocco (short-stay police
 * extension vs. separate DGSN residence permit) governance distinction, and
 * excludes the implausible TZS 50-300 fee figures found for Tanzania rather
 * than publishing them.
 *
 * Loaded from visa_content_db() alongside the other seed files; each entry
 * upgrades the matching bulk-generic page in place via visa_seed_page() /
 * visa_seed_page_upgrade() -- it never overwrites a page that has already
 * moved past 'generic' status.
 */
function visa_seed_pages_def_batch_phase3b_extension(): array
{
    return [
        [
            'page_slug' => 'kazakhstan-visa-extension',
            'country_slug' => 'kazakhstan',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Visa extension, via Egov/Eqonaq migration-service notification; a separate Temporary Residence Permit (TRP), up to 1 year and extendable, exists for longer stays',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Kazakhstan\'s visa and migration framework, confirmed via the official gov.kz portal and the official legislation database (adilet.zan.kz), provides for visa extension — submitted 15 calendar days before the visa\'s expiry, typically tied to a renewed underlying contract. A separate Temporary Residence Permit (TRP) exists for foreigners staying up to one year, with the possibility of further extension.</p>',
            'typical_stay' => 'Temporary visa extension: up to 30 additional days, or a 14-day exit visa alternative. Temporary Residence Permit (TRP): up to 1 year, extendable',
            'entry_type' => 'In-country, via the Visa and Migration Portal (vmp.gov.kz) and Egov/Eqonaq migration-service notification',
            'processing_time_text' => 'Submit 15 calendar days before the visa\'s expiration; 30 business days before expiry when tied to a renewed labour contract',
            'validity_text' => 'Temporary visa extension: up to 30 additional days. TRP: up to 1 year, extendable',
            'application_method' => 'Via the Visa and Migration Portal (vmp.gov.kz) and Egov/Eqonaq migration-service notification; documents include passport, copy of passport and visa, photo, application form, labour contract (where applicable), and fingerprinting certificate',
            'interview_required' => 'Not described as requiring a formal interview — an online/documentary process',
            'biometric_required' => 'Unknown — a fingerprinting certificate is a listed document requirement, though this may reflect general migration registration rather than a confirmed biometric visa-extension step',
            'government_fee_text' => 'As researched: confirm the current fee with the official Kazakhstan authority before applying or paying',
            'application_centre' => 'Visa and Migration Portal (vmp.gov.kz) / Egov.kz',
            'authority_name' => 'Government of Kazakhstan (gov.kz) / Adilet legal information system (adilet.zan.kz)',
            'authority_url' => 'https://www.gov.kz/services/3170?lang=en',
            'eligibility_html' => '<p>Visa extension is available for holders needing additional time, typically tied to a renewed contract, with required documents including passport, copy of passport and visa, photo, application form, labour contract (where applicable), and a fingerprinting certificate. Separately, a Temporary Residence Permit (TRP) is available for foreigners or stateless persons temporarily staying in Kazakhstan for up to one year, with the possibility of further extension — a distinct, longer-term mechanism from the short-term visa extension.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply 15 Calendar Days Before Expiry</h4><p>Via the Visa and Migration Portal (vmp.gov.kz) or Egov/Eqonaq notification.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Longer Stays Use the TRP Route</h4><p>The Temporary Residence Permit is a separate mechanism, valid up to 1 year and extendable.</p><p>Our consultants can help you confirm which route — short-term extension or TRP — fits your situation.</p>',
            'seo_title' => 'Kazakhstan Visa Extension for Indians | Extension & Temporary Residence Permit',
            'meta_description' => 'Need more time in Kazakhstan? See the visa extension process and the separate Temporary Residence Permit route, via VisaAgency.in.',
            'og_title' => 'Kazakhstan Visa Extension for Indians — Extension & Temporary Residence Permit',
            'og_description' => 'Need more time in Kazakhstan? See the visa extension process and the separate Temporary Residence Permit route, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Valid passport', 'mandatory'],
                ['Basic Documents', 'Copy of passport and current visa', 'mandatory'],
                ['Basic Documents', 'Photo', 'mandatory'],
                ['Supporting Documents', 'Application form', 'mandatory'],
                ['Supporting Documents', 'Labour contract (where applicable)', 'conditional'],
                ['Supporting Documents', 'Fingerprinting certificate', 'mandatory'],
            ],
            'steps' => [
                ['Apply at Least 15 Calendar Days Before Expiry', 'Via vmp.gov.kz or Egov/Eqonaq.'],
                ['Submit Required Documents', 'Including passport copy, photo, and application form.'],
                ['Consider the TRP Route for Longer Stays', 'A separate mechanism valid up to 1 year, extendable.'],
            ],
            'faqs' => [
                ['How do I extend my stay in Kazakhstan?', 'Submit an extension application 15 calendar days before your visa expires, via vmp.gov.kz or Egov/Eqonaq.'],
                ['What if I need to stay longer than a short extension allows?', 'A separate Temporary Residence Permit (TRP), valid up to 1 year and extendable, is available.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Government of Kazakhstan (gov.kz) / Adilet legal information system (adilet.zan.kz)',
                'url' => 'https://www.gov.kz/services/3170?lang=en',
                'notes' => 'Phase 3B research: official gov.kz services page and the official Adilet legislation database both confirm the extension and TRP mechanisms. Confidence: High.',
            ],
        ],
        [
            'page_slug' => 'morocco-visa-extension',
            'country_slug' => 'morocco',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Two distinct mechanisms: (1) a 90-day tourist stay extension via local police headquarters, and (2) a separate Residence Permit (titre de séjour) via the DGSN for longer-term stays',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Morocco maintains two genuinely distinct mechanisms for staying longer, per official diplomatie.ma guidance and established Moroccan press reporting: a short-term tourist stay extension of up to 90 additional days, requested at the local police headquarters before the initial stay expires; and a separate Residence Permit (titre de séjour), issued by the Direction Générale de la Sûreté Nationale (DGSN), required for anyone remaining in Morocco beyond 90 days on any basis.</p>',
            'typical_stay' => 'Tourist extension: up to 90 additional days. Residence Permit: longer-term, per DGSN terms',
            'entry_type' => 'Tourist extension: local police headquarters. Residence Permit: DGSN',
            'processing_time_text' => 'Processing time varies; confirm current timelines with the local police headquarters (extension) or DGSN (residence permit)',
            'validity_text' => 'Tourist extension: up to 90 additional days. Residence Permit: longer-term, renewed annually per DGSN practice',
            'application_method' => 'Tourist extension: request submitted to local police headquarters before the initial stay expires. Residence Permit: application to the DGSN, requiring a legalized passport copy and recent photographs',
            'interview_required' => 'Not described as requiring a formal interview for either route',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: a Residence Permit renewal fee of approximately 100 Moroccan dirhams (MAD) has been reported; confirm the current fee for either route directly with the relevant Moroccan authority before applying or paying',
            'application_centre' => 'Local police headquarters (tourist extension) or DGSN (Residence Permit)',
            'authority_name' => 'Ministère des Affaires Étrangères, de la Coopération Africaine et des Marocains Résidant à l\'Étranger (diplomatie.ma) / Direction Générale de la Sûreté Nationale (DGSN)',
            'authority_url' => 'https://in.diplomatie.ma/en/contact-us',
            'eligibility_html' => '<p>Tourists wishing a short additional stay (up to 90 more days) submit a request to local police headquarters before their initial stay expires. Anyone needing to remain in Morocco beyond 90 days on any basis — not just tourism — requires a Residence Permit (titre de séjour) from the DGSN, which has required a medical certificate and criminal record for renewal, alongside a legalized passport copy and recent photographs.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Do Not Merge These Two Mechanisms</h4><p>The short-stay tourist extension and the DGSN Residence Permit are genuinely different legal products serving different durations and purposes — one is not a substitute description for the other.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Short Extra Stay: Local Police Headquarters</h4><p>For up to 90 additional days, before your initial stay expires.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Longer-Term Stay: DGSN Residence Permit</h4><p>A separate process (titre de séjour) required for any stay beyond 90 days, regardless of your original purpose of entry.</p><p>Our consultants can help you confirm which of these two distinct routes applies to your situation.</p>',
            'seo_title' => 'Morocco Visa Extension for Indians | Police Extension & DGSN Residence Permit',
            'meta_description' => 'Need more time in Morocco? See the 90-day police extension and the separate DGSN Residence Permit route, via VisaAgency.in.',
            'og_title' => 'Morocco Visa Extension for Indians — Police Extension & DGSN Residence Permit',
            'og_description' => 'Need more time in Morocco? See the 90-day police extension and the separate DGSN Residence Permit route, via VisaAgency.in.',
            'documents' => [
                ['Supporting Documents', 'Legalized passport copy (Residence Permit route)', 'conditional'],
                ['Supporting Documents', 'Recent identity photographs (Residence Permit route)', 'conditional'],
                ['Medical Documents', 'Medical certificate (Residence Permit renewal)', 'conditional'],
                ['Supporting Documents', 'Criminal record extract (Residence Permit renewal)', 'conditional'],
            ],
            'steps' => [
                ['Determine Which Route You Need', 'A short extension (≤90 days) or a longer-term Residence Permit.'],
                ['Short Extension: Apply at Local Police Headquarters', 'Before your initial stay expires.'],
                ['Longer-Term Stay: Apply to the DGSN for a Residence Permit', 'A separate, distinct legal process.'],
            ],
            'faqs' => [
                ['Can I extend my Morocco tourist stay?', 'Yes — up to 90 additional days, via a request to local police headquarters before your initial stay expires.'],
                ['What if I need to stay even longer?', 'A separate Residence Permit (titre de séjour) from the DGSN is required for any stay beyond 90 days — a different legal mechanism from the short-term extension.'],
            ],
            'fees' => [
                ['Residence Permit renewal (as researched)', 'MAD 100', 1, 'MAD', 'As researched; confirm the current fee with the DGSN before applying or paying — not independently verified on an official fee schedule'],
            ],
            'source' => [
                'authority' => 'Ministère des Affaires Étrangères, de la Coopération Africaine et des Marocains Résidant à l\'Étranger (diplomatie.ma) / Direction Générale de la Sûreté Nationale (DGSN)',
                'url' => 'https://in.diplomatie.ma/en/contact-us',
                'notes' => 'Phase 3B research: official diplomatie.ma confirms the general Moroccan visa framework; established Moroccan press (bladi.net, hespress.com, telquel.ma, demarchesmaroc.com) consistently describes the dual extension/residence-permit mechanism. No direct DGSN.gov.ma page was located. Confidence: Medium. Status remains researched, not verified.',
            ],
        ],
        [
            'page_slug' => 'tanzania-visa-extension',
            'country_slug' => 'tanzania',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'unknown',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Visa extension, in increments of approximately 3 months up to a cumulative 6-month maximum, via the Tanzania Immigration Department',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Official Tanzania Immigration confirms a visa extension mechanism allowing extensions in increments of approximately three months, up to a cumulative maximum of around six months, processed through the immigration office in Dar es Salaam.</p>',
            'typical_stay' => 'Increments of approximately 3 months, up to a cumulative maximum of approximately 6 months',
            'entry_type' => 'Immigration office, Dar es Salaam, or online via visa.immigration.go.tz',
            'processing_time_text' => 'Processing time varies; confirm current timelines with Tanzania Immigration',
            'validity_text' => 'Increments of approximately 3 months, cumulative maximum of approximately 6 months',
            'application_method' => 'Via the official Tanzania Immigration website (www.immigration.go.tz) ONLY, as advised by the authority, or in person at the Dar es Salaam immigration office',
            'interview_required' => 'Not described as requiring a formal interview',
            'biometric_required' => 'Unknown — not clearly confirmed in available research',
            'government_fee_text' => 'As researched: fees may apply; confirm the current fee directly with Tanzania Immigration before applying or paying',
            'application_centre' => 'Tanzania Immigration Department, Dar es Salaam, or visa.immigration.go.tz',
            'authority_name' => 'Tanzania Immigration Department (immigration.go.tz)',
            'authority_url' => 'https://www.immigration.go.tz',
            'eligibility_html' => '<p>Travellers wishing to extend their stay beyond the initial visa validity period can apply at the Immigration Department, with extensions subject to approval and justification for the extension request, granted in roughly 3-month increments up to a cumulative maximum of around 6 months.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Fee Caution</h4><p>Specific fee figures found in secondary research (in the range of TZS 50-300) appeared implausibly low for an official government fee and are deliberately not published here — confirm the current fee directly with Tanzania Immigration.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Early</h4><p>Start your extension process before your current visa expires, via visa.immigration.go.tz or the Dar es Salaam immigration office.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Confirm the Current Fee Directly</h4><p>Reported figures could not be reliably confirmed — check with Tanzania Immigration before applying or paying.</p><p>Our consultants can help you confirm the current extension process and fee.</p>',
            'seo_title' => 'Tanzania Visa Extension for Indians | 3-Month Increments, 6-Month Cap',
            'meta_description' => 'Need more time in Tanzania? See the visa extension process via the Dar es Salaam immigration office, via VisaAgency.in.',
            'og_title' => 'Tanzania Visa Extension for Indians — 3-Month Increments, 6-Month Cap',
            'og_description' => 'Need more time in Tanzania? See the visa extension process via the Dar es Salaam immigration office, via VisaAgency.in.',
            'documents' => [
            ],
            'steps' => [
                ['Start the Process Early', 'Before your current visa expires.'],
                ['Apply via the Official Portal or in Person', 'visa.immigration.go.tz or the Dar es Salaam immigration office.'],
                ['Confirm the Current Fee Directly', 'Reported figures could not be reliably confirmed.'],
            ],
            'faqs' => [
                ['How much can I extend my stay in Tanzania?', 'In increments of approximately 3 months, up to a cumulative maximum of approximately 6 months.'],
                ['What is the fee?', 'Fees may apply; confirm the current fee directly with Tanzania Immigration — reported figures found in research were not reliable enough to publish.'],
            ],
            'fees' => [
            ],
            'source' => [
                'authority' => 'Tanzania Immigration Department (immigration.go.tz)',
                'url' => 'https://www.immigration.go.tz',
                'notes' => 'Phase 3B research: official immigration.go.tz confirms the extension mechanism and increments; specific TZS fee figures (50-300) found in secondary sources are implausibly low and explicitly excluded rather than published. Confidence: High for the mechanism, fee deliberately omitted.',
            ],
        ],
        [
            'page_slug' => 'uzbekistan-visa-extension',
            'country_slug' => 'uzbekistan',
            'category_slug' => 'visa-extension',
            'content_status' => 'researched',
            'biometric_status' => 'not_required',
            'interview_status' => 'not_required',
            'official_visa_name' => 'Online visa extension via the Unified Interactive Public Services Portal, processed by the Department of Migration and Personalization under the Ministry of Internal Affairs',
            'visa_subclass_code' => null,
            'intro_html' => '<p>Foreign citizens and stateless persons in Uzbekistan can now submit visa extension applications online through the Unified Interactive Public Services Portal, under the "Citizenship" section, reviewed by the Department of Migration and Personalization under the Ministry of Internal Affairs.</p>',
            'typical_stay' => 'Extension duration depends on the state duty paid, ranging from a short extension (minimum tier) to up to 1 year',
            'entry_type' => 'Online, via the Unified Interactive Public Services Portal',
            'processing_time_text' => '15 working days for application review by the Department of Migration and Personalization; passport submitted to the local migration office within 3 working days after fee payment, returned with the extension sticker within 2 days after that',
            'validity_text' => 'Depends on the state duty tier selected, from the minimum (7 days) up to 1 year',
            'application_method' => 'Electronic form on the Unified Interactive Public Services Portal, with a passport/travel-document copy and a document confirming the reason for extension; submitted no later than 10 days before the visa\'s expiration date. A close relative or authorized representative (with notarized power of attorney) may submit on the applicant\'s behalf',
            'interview_required' => 'Not required — an online application process',
            'biometric_required' => 'Not required — an online application process',
            'government_fee_text' => 'As researched: state duty ranging from approximately USD 40 (up to 7 days) to approximately USD 160 (up to 1 year)',
            'application_centre' => 'Unified Interactive Public Services Portal / Department of Migration and Personalization, Ministry of Internal Affairs',
            'authority_name' => 'Department of Migration and Personalization, Ministry of Internal Affairs of Uzbekistan',
            'authority_url' => 'https://advice.uz/en/document/1580',
            'eligibility_html' => '<p>Applicants fill out an electronic form, attach a copy of their passport/travel document, and provide a document confirming the reason for the extension, submitted no later than 10 days before the current visa expires. A close relative who is an Uzbek citizen, or an authorized representative holding a notarized power of attorney, may submit the application on the foreign national\'s behalf. The Department of Migration and Personalization reviews applications within 15 working days; after the state duty is paid, the passport is submitted to the local migration office within 3 working days and returned with the extension sticker within 2 further days.</p><p>This is general immigration-document guidance, not a guarantee of approval.</p>',
            'indian_applicant_html' => '<h4 style=\'margin:0 0 10px;font-size:16px;\'>Apply Online at Least 10 Days Before Expiry</h4><p>Via the Unified Interactive Public Services Portal, "Citizenship" section.</p><h4 style=\'margin:20px 0 10px;font-size:16px;\'>Budget for the State Duty</h4><p>As researched, approximately USD 40 for a 7-day extension up to approximately USD 160 for a 1-year extension.</p><p>Our consultants can help you confirm the current state-duty tier and document requirements for your extension.</p>',
            'seo_title' => 'Uzbekistan Visa Extension for Indians | Online Extension via Public Services Portal',
            'meta_description' => 'Need more time in Uzbekistan? See the online visa extension process and state-duty fees, via VisaAgency.in.',
            'og_title' => 'Uzbekistan Visa Extension for Indians — Online Extension via Public Services Portal',
            'og_description' => 'Need more time in Uzbekistan? See the online visa extension process and state-duty fees, via VisaAgency.in.',
            'documents' => [
                ['Basic Documents', 'Copy of passport/travel document', 'mandatory'],
                ['Supporting Documents', 'Document confirming the reason for extension', 'mandatory'],
                ['Supporting Documents', 'Notarized power of attorney (if applying via a representative)', 'conditional'],
            ],
            'steps' => [
                ['Apply Online at Least 10 Days Before Expiry', 'Via the Unified Interactive Public Services Portal.'],
                ['Pay the Applicable State Duty', 'Ranging from approximately USD 40 to USD 160, depending on the extension duration.'],
                ['Submit Your Passport Within 3 Working Days', 'To the local migration office after payment.'],
                ['Receive Your Passport Back', 'With the extension sticker, within 2 further days.'],
            ],
            'faqs' => [
                ['Can I extend my Uzbekistan visa online?', 'Yes — via the Unified Interactive Public Services Portal, reviewed by the Department of Migration and Personalization.'],
                ['What does it cost?', 'As researched, a state duty ranging from approximately USD 40 (up to 7 days) to approximately USD 160 (up to 1 year).'],
            ],
            'fees' => [
                ['Visa extension state duty (up to 7 days)', 'USD 40', 1, 'USD', 'As researched; confirm current rate with the Ministry of Internal Affairs'],
                ['Visa extension state duty (up to 1 year)', 'USD 160', 1, 'USD', 'As researched; confirm current rate with the Ministry of Internal Affairs'],
            ],
            'source' => [
                'authority' => 'Department of Migration and Personalization, Ministry of Internal Affairs of Uzbekistan',
                'url' => 'https://advice.uz/en/document/1580',
                'notes' => 'Phase 3B research: official legal-advice portal (adliya.uz/advice.uz) confirms the mechanism, corroborated by kun.uz (established Uzbek news outlet, October 2025 reporting on the online extension feature). Confidence: High.',
            ],
        ],
    ];
}
